### ISSUE TITLE
Release odoc!

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#1004]

**Comment by jonludlam** [comment]
Done: odoc 2.3.0 released and available in opam-repository.

**Comment by jonludlam** [comment]
Oops, apologies, this is, in fact, not done! But it will be soon...

**Comment by olafhering** [comment]
5b0b056f7758f85cd49c756874aae874d375a0b7 fails to compile for me, like this:

````
[   36s] Command [268] exited with code 2:
[   36s] $ (cd _build/default && /usr/bin/ocamlc.opt -w -40 -g -w -18-53 -w -50 -g -bin-annot -I src/model/.odoc_model.objs/byte -I /usr/lib64/ocaml/astring -I /usr/lib64/ocaml/camlp-streams -I /usr/lib64/ocaml/compiler-libs -I /usr/lib64/ocaml/odoc-parser -I /usr/lib64/ocaml/result -intf-suffix .ml -no-alias-deps -open Odoc_model__ -o src/model/.odoc_model.objs/byte/odoc_model__Semantics.cmo -c -impl src/model/semantics.ml)
[   36s] File "src/model/semantics.ml", line 232, characters 26-66:
[   36s] 232 |   | { value = `Code_block { meta; delimiter = _; content; output }; location }
[   36s]                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[   36s] Error: This pattern should not be a record, the expected type is
[   36s]        (string Odoc_parser.Ast.with_location *
[   36s]         string Odoc_parser.Ast.with_location option)
[   36s]        option * string Odoc_parser.Ast.with_location
````
[odoc-2.3.0.txt](https://github.com/ocaml/odoc/files/12861245/odoc-2.3.0.txt)

**Comment by olafhering** [comment]
It turned out: the `odoc-parser` package in opam has outdated URLs. So it was not obvious that `odoc-parser` is now part of `odoc` itself. With that fixed, the package compiles again for me.

**Comment by Julow** [comment]
The source code and the dev-repo URLs are correct in opam-repository. Are you using the `homepage` URL to fetch the sources ?

**Comment by olafhering** [comment]
The old code is still in the referenced homepage URL. As a result I did not notice the update, and the merge into odoc.
