### ISSUE TITLE
Styling improvement suggestions

### ISSUE THREAD

**Issue by bobbypriambodo** [ocaml/odoc#102]
Hi! Thanks for working on such a great tool.

This is mostly a question: do you have planned/tracked improvements for the overall odoc styling (odoc.css) anywhere?

I strongly believe that browsing docs should be a pleasant experience. I really like the minimalistic approach taken by odoc. However, if you don't mind, I have several suggestions to improve the overall experience:

1. Slightly increase font size. Given that most web pages nowadays use big fonts, I think the size of odoc texts are a bit too small in comparison. This makes it slightly harder to read comfortably.

2. Slightly increase body width. Seeing as the current implementation uses `ex` unit, I think this is consequential from (1). I kind of understand the intent of having the pretty narrow width as it can reflect closely what's written on the `mli` files (and as reading texts that spans over the screen, like from ocamldoc, is definitely unwieldy), but not too narrow.

3. Center the body. This is mostly personal, but it bugs me a bit too much that the screen estate is not balanced... Perhaps the empty space is reserved for some kind of navigations (which, by the way, would also be a nice thing to have)? But if not, I think making it center-aligned can make it tidier in my opinion.

4. Last is not about screen estate, but still usability: put more contrast contrast on the signatures and their doc. The below screenshot is taken from [doc-ock documentation page](https://ocaml-doc.github.io/doc-ock/DocOck/index.html). The differentiator of the two is the font-face, and the doc (like the one for `build_resolver`) can easily be missed when skimming (signatures mistaken as doc and vice versa). Perhaps by using a different background color?

![screen shot 2018-01-23 at 10 18 58 am](https://user-images.githubusercontent.com/4920820/35256521-def0cdf2-0026-11e8-9ac8-6f55244507cc.png)

I think that's all I can think of now. My apologies if these points are already discussed somewhere, please point me there if so (and if available publicly). Hope these suggestions could be of some use.

**Comment by dbuenzli** [comment]
Regarding 1. something could maybe done depending on page width for people with large screens, but note that the font size is actually on the order of magnitude of the text you are currently reading on github. It's important to keep a good level of information density, larger fonts look cool but they are not information efficient and a usability pain, especially on laptops. In any case the stylesheet is done entirely relatively so you can adjust the font size to your taste by using the increase/decrease font functionality of your browser to adjust it to your taste and the layout should follow accordingly;  your browser should remember your preference across visits on the same website.

Regarding 2. the rationale is not the one you suppose, it only follows basic typographic conventions for legibility. It could maybe be expanded by a few `ex`es but not much more.

Regarding 3. I don't have a strong opinion on that one. Though one advantage of the current scheme is that you have a predictable place, regardless of your current browser page width, to look for content when you switch to an `odoc` generated page.

Regarding 4. I don't see a problem here. What you are skimming for is definitions not the doc string of definitions. So  skimming should first allow you to delineate module members "blocks" and then once this is done between the member and its doc string. I think the current stylesheet enables this reasonably without having to resort to other baroque framing cues, especially if all your members are documented (and they should).

**Comment by bobbypriambodo** [comment]
> It's important to keep a good level of information density, larger fonts look cool but they are not information efficient and a usability pain, especially on laptops

Agreed, and I'm by no means suggesting to make it needlessly big. Zooming in to 110% gives me a more comfortable view. I suppose it would be better when the docs are centralized, but as it's currently scattered about I would need to zoom in on each site. Again, this is not actually a dealbreaker, and I can live with that.

On 2 and 3, I can't help but notice the empty space, as shown in the following picture (docs for c-cube's sequence lib, on a 22-inch monitor):

![screenshot from 2018-01-23 16 25 02](https://user-images.githubusercontent.com/4920820/35267787-fb622322-0059-11e8-8c6a-fc026333113a.png)

I wonder if the current state is already the most optimal one. That said, odoc generated pages look great on mobile.

On 4, fair enough. I myself don't feel strongly about this one too. Just sounding the concerns I get when browsing several docs. Skimming e.g. sequence's docs is a more comfortable experience due to the members are nicely documented.

But what you've said are all fair points. With this issue I'm just wondering about the general opinion about the styling; and are there any not-so-apparent low hanging fruits that can be improved. (I'm also aware that this may undoubtedly lead to bikeshedding, but hopefully there's something we can take out of it.)

**Comment by dbuenzli** [comment]
> I suppose it would be better when the docs are centralized, but as it's currently scattered about I would need to zoom in on each site. Again, this is not actually a dealbreaker, and I can live with that.

Using `odig` makes it localized (besides while it's better to have a good default style sheet it would be good to leave a bit of alternative choice via https://github.com/dbuenzli/odig/issues/21).

I'll definitively have a look at choosing a different base font size for large screens when I get back to odig (which should be soonish). Basically the current design is based `14pt` if you use default browsers settings. I think that for larger screens `16pt` should be used.

**Comment by bobbypriambodo** [comment]
Ah, true. That sounds great, thanks!

I think my concerns have already been stated, and I'm quite content with the responses. I'll let you decide if you'd use this issue for tracking or close it so as to not clutter. Thanks again for your time.

**Comment by rizo** [comment]
Closing this. Many visual changes were made since this was opened.

@bobbypriambodo [Here're some examples](https://github.com/ocaml/odoc/pull/208#issue-220903691) of the current theme, if you still have any changes you'd like to make to the design, please do open new issues.
