### ISSUE TITLE
Table with missing closing bracket hangs

### ISSUE THREAD

**Issue by art-w** [ocaml/odoc#1043]
When using the new table syntax, incomplete markup appears to hang rather than signal a syntax error:

```ocaml
(** {t missing the closing bracket *)

(** also happens with {table with no closing bracket *)
```

According to `dune build --verbose @doc`, it seems to get stuck at this step: (and consummes 100% cpu with increasing memory?)

```
$ odoc compile -I . -I ../../_doc/_odoc/pkg/test --pkg test -o test.odoc test.cmti
```

In comparison, some of the other markup like `{1` or `{ul` report some weird warnings which are not hinting at the missing `}`, but they do not hang:

```ocaml
(** {ul {- foo} *)
```
```
File "test.mli", line 1, characters 16-17:
Warning: End of text is not allowed in '{ul ...}' (bulleted list).
```

(tested with odoc 2.3.1 and master)

**Comment by Julow** [comment]
Thanks to @lubegasimon for solving this issue :)
