### ISSUE TITLE
Any way to document ppxlib transformations?

### ISSUE THREAD

**Issue by davesnx** [ocaml/odoc#1055]
Hi odoc-team!

I would like to extend the documentation of one of my libs with the ppx hooks it exposes, would be very handy to have a way to add documentation via comments (or somehow) to describe those transformations with examples and whatnot, and make it show up into a odoc-site.

**Comment by jonludlam** [comment]
Would an mld file with code snippets (tested via mdx) be sufficient?

**Comment by Julow** [comment]
I also think .mld pages is the best fit. I'm not sure what else could automatized, even statically listing the hooks might not be possible.

**Comment by jonludlam** [comment]
Please reopen if this isn't sufficient.
