### ISSUE TITLE
New docstring parser doesn't recognize {:url}

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#109]
```
Failure("File \"re2/src/regex_intf.ml\", line 18, characters 24-26:\n'{:': bad markup")
```

**Comment by aantron** [comment]
We can have support for this, but I want to confirm: this is an intentional extension over ocamldoc syntax.

ocamldoc supports only `{{:url}...}`, where `...` must be non-empty. Right now, as an extension over ocamldoc, odoc supports `{{:url}}`, where it replaces the empty `...` by the text `url`.

**Comment by lpw25** [comment]
It's a bit hard to remember, as it was a while ago, but I think this was a deliberate extension. IIRC I added support for `{:...}` and `{{!...} ...}` to make the two kinds of references consistent.

**Comment by aantron** [comment]
Great, that's what I assumed, but I was being a bit conservative when working :) I'll add/restore `{:...}` support.
