### ISSUE TITLE
Annoying behaviour when records end with lists in code blocks

### ISSUE THREAD

**Issue by xvw** [ocaml/odoc#1093]
Let's consider this example:

```ocaml
{@ocaml[
type t = { foo: int list }
let x = {foo = [1;2;3]}
let k = 10
]}
```

It will produce:

```
[code
 type t = { foo; int list }
 let x = {foo = [1; 2; 3
]
let k = 10
]}  -- invisible
```

When writing code by hand, it's trivially fixable by adding, for example, small spaces. But if the code is an output of MDX or formatted by OCamlformat, it can be more annoying!

**Comment by panglesd** [comment]
Not sure if it solve this since it can be auto-generated as well, but similarly to ocaml's multiline string you can "name" the delimiters.

E.g:
```
{blibli@ocaml[
type t = { foo: int list }
let x = {foo = [1;2;3]}
let k = 10
]blibli}
```

**Comment by xvw** [comment]
It solve everything! Thank you very much!
