### ISSUE TITLE
Assertion failed in `src/docOckIdentEnv.ml", line 260`

### ISSUE THREAD

**Issue by ejgallego** [ocaml/odoc#111]
Using the tree at https://github.com/coq/coq/pull/6857 , if I do:
```
$ jbuilder build @doc
```
I get:
```
        odoc _doc/coq.clib/cArray.odoc (exit 2)
(cd _build/default/_doc/coq.clib && /home/egallego/.opam/4.06.1/bin/odoc compile -I ../../clib -I /home/egallego/.opam/4.06.1/lib/ocaml/threads --pkg coq.clib -o cArray.odoc ../../clib/.clib.objs/cArray.cmti)
odoc: internal error, uncaught exception:
      File "src/docOckIdentEnv.ml", line 260, characters 22-28: Assertion failed
      Raised at file "src/docOckIdentEnv.ml", line 260, characters 22-34
      Called from file "src/docOckCmi.ml", line 365, characters 18-42
      Called from file "src/docOckCmi.ml", line 359, characters 20-42
      Called from file "src/docOckCmi.ml", line 498, characters 16-46
      Called from file "src/docOckCmi.ml", line 907, characters 17-55
      Called from file "src/docOckCmi.ml", line 824, characters 36-66
      Called from file "src/docOckCmi.ml", line 887, characters 22-60
      Called from file "src/docOckCmi.ml", line 932, characters 17-57
      Called from file "src/docOckCmti.ml", line 592, characters 16-66
      Called from file "src/docOckCmti.ml", line 571, characters 17-47
      Called from file "src/docOckCmti.ml", line 603, characters 25-62
      Called from file "list.ml", line 111, characters 24-34
      Called from file "src/docOckCmti.ml", line 601, characters 4-135
      Called from file "src/docOckCmti.ml", line 443, characters 37-67
      Called from file "src/docOckCmti.ml", line 30, characters 19-24
      Called from file "src/docOckCmti.ml", line 488, characters 13-61
      Called from file "src/docOckCmti.ml", line 568, characters 20-65
      Called from file "src/docOckCmti.ml", line 603, characters 25-62
      Called from file "list.ml", line 111, characters 24-34
      Called from file "src/docOckCmti.ml", line 601, characters 4-135
      Called from file "src/docOckCmti.ml", line 610, characters 14-46
      Called from file "src/docOck.ml", line 54, characters 31-71
      Called from file "lib/compile.ml", line 21, characters 8-17
      Called from file "src/cmdliner_term.ml", line 27, characters 19-24
      Called from file "src/cmdliner.ml", line 106, characters 32-39
```
relevant packages: OCaml 4.06.1 + odoc 1.2.0

**Comment by aantron** [comment]
@ejgallego this is likely the same problem as in #103 and #110. To fix, try pinning `doc-ock` to `master`. You can also try odoc `master` instead, but that has some formatting changes in progress, and it might not render your docs as well.

**Comment by ejgallego** [comment]
Oh thanks, somehow I only searched for open issues. I am OK with the formatting changes, using odoc in Coq is really a work-in-progress so the first step is to get it running, then we'll have a lot of work in the Coq-side.

I am trying with `master`, let me know if I should also try in `doc-ock`.

**Comment by ejgallego** [comment]
`odoc` master works fine, thanks!

**Comment by ejgallego** [comment]
We want to move to master for sure, see coq/coq#7155 for the extremely preliminary plan to use `odoc` in Coq [it hasn't even decided whether we will switch yet]

**Comment by ejgallego** [comment]
By the way @aantron , is there an estimation on whether the next `odoc` version will be released?

That'd be great as we could start then using it in Coq [now it is blocked due to this bug]

**Comment by aantron** [comment]
@ejgallego, you should be able to avoid the bug by using odoc 1.2.0 and doc-ock 1.2.1.

Until a couple months ago, the offending code was residing in the separate doc-ock repo, so we fixed odoc 1.2.0 by doing a point release of doc-ock.

We can also release whatever we have now in odoc, if you would like some other things that are not in odoc 1.2.0.

**Comment by ejgallego** [comment]
Thanks for the info; it is not urgent, but we are going to discuss API documentation this week and I wanted to have an idea.

We will be happy to use whatever the recommended setup is.

**Comment by aantron** [comment]
I recommend odoc 1.2.0 and doc-ock 1.2.1 for now, odoc `master` is much less likely to be fully, stable due to large changes since 1.2.0.
