### ISSUE TITLE
Index generation when library has an ML file to control exports

### ISSUE THREAD

**Issue by stevebleazard** [ocaml/odoc#113]
Versions: odoc 1.2.0 and dev.

When I have a library ML file the generated library.html file contains links that point to the file itself and not the documentation for the library. Thus with the following files:

A private module `src/priv_module.ml`:
```ocaml
(** Private module *)

(** Some private function doc *)
let privfun () = ()
```
The public module `src/pub_module.ml`:
```ocaml
(** Public module *)

(** Some public function doc *)
let pubfun () = ()
```
A library ML file to only export the public module, `src/testlb.ml`:
```ocaml
module Pub_module = Pub_module
```
And the following `src/jbuild` file:
```
(jbuild_version 1)

(library
 ((name testlib)
  (public_name testlib)
  ))
```
Compilation works fine but when I generate the documentation via`jbuilder build @doc` the testlib/Testlib/index.html file has links to `testlib/Testlib/index.html#module-Pub_module` and not the module documentation. 

Changing `src/testlib.ml` to:
```ocaml
module Pub_module = Testlib__Pub_module
```
Fixes the issue but with larger libraries with multiple exported modules I get the following error during compilation:
```
Warning 49: no cmi file was found in path for module ...
```

**Comment by trefis** [comment]
Hi,

That one is actually a bug in jbuilder, which I reported in https://github.com/ocaml/dune/issues/651
I don't think a new release of jbuilder happened since it was fixed. Could you try pinning jbuilder to the git version and trying again?

**Comment by stevebleazard** [comment]
This improves things but you end up with the following tree ( > indicates a link):

testlib > Testlib__ >
  Priv_module > (pub module doc)
  Pub_module > (pub module doc)
  Testlib > Pub_module > (pub module doc) 

I would have expected testlib > Testlib > Pub_module > (pub module doc) at most given that this is pub doc only build.   This may still be a jbuilder issue

**Comment by stevebleazard** [comment]
This was an issue with jbuilder, closing the ticket. Thanks for the help
