### ISSUE TITLE
Bad parsing or ][ in block code

### ISSUE THREAD

**Issue by zoggy** [ocaml/odoc#1137]
The following code is silently parsed incorrectly by odoc:
```
{@json[
{
  "string": "] [",
  "string2": "][",
}
]}
```
The problem is with the `][` sequence, but a space between `]` and `[ ` is parsed correctly. Using `]\[` does not solve the problem, as the `\[`is kept in generated html.

**Comment by panglesd** [comment]
Indeed, the addition of the `{[ ...][ ...]}` syntax in https://github.com/ocaml-doc/odoc-parser/pull/17 broke any code containing `][`...

Maybe a fix where this syntax is only available with a delimiter? `{delim[ ... ]delim[ ... ]}`.

In the meantime, for your usecase, you can use a delimiter to avoid `][` be interpreted as an end to your code block:

```
{delim@json[
{
  "string": "] [",
  "string2": "][",
}
]delim}
```

(delimiters for odoc code blocks are similar to the OCaml `{delim| ... |delim}` for strings)

**Comment by zoggy** [comment]
Ah, thanks !
