### ISSUE TITLE
Displaying Comment twice

### ISSUE THREAD

**Issue by Fourchaux** [ocaml/odoc#114]
**Config** : odoc 1.2.0 (opam) - jbuilder 1.0+beta19.1 - OCaml 4.06.1+flambda

With this test.mli:
```ocaml
module Foo : sig
  val h : int (** Hello. *)
  val b : int (** Bonjour. *)
end

include module type of Foo
```
```
$ jbuilder build @doc  gives: 
```

```
Module Test

module Foo : sig ... end

include module type of Foo

val h : int
   Hello.

val b : int
   Hello.
   Bonjour.
```
with a superfluous 2nd 'Hello'.

**Note**: the display is correct with ocamldoc.

**Comment by lpw25** [comment]
This is the correct behaviour. The `hello` comment is in an ambiguous position and gets attached to both signature items. If you turn on warning 50 then the compiler will warn you about this case.

**Comment by lpw25** [comment]
Oh, and the solution is to add a blank line between the `h` and `b` signature items.

**Comment by Fourchaux** [comment]
Thanks you very much for this quick answer (AND the solution) 
:+1:
