### ISSUE TITLE
[Feature] Documentation coverage

### ISSUE THREAD

**Issue by Chris00** [ocaml/odoc#115]
If possible, it would [be nice](https://discuss.ocaml.org/t/ocaml-first-impressions/517/90) to be able to get a documentation coverage report from odoc.  This could be used by Camelus to give some recommendations when people submit PRs to the opam-repository.

**Comment by petr-tik** [comment]
Can someone please reopen this as it's still not done and I would like this feature enhancement? 

### Relevant prior art
rustdoc has a nightly (unstable) feature to report doc coverage on stdout and in JSON format. 

https://doc.rust-lang.org/rustdoc/unstable-features.html#--show-coverage-calculate-the-percentage-of-items-with-documentation

Given the odoc already depends  on yojson - both look doable without new deps. 
https://github.com/ocaml/odoc/blob/master/odoc.opam#L40
