### ISSUE TITLE
Non-existent documentation?

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#116]
odoc effectively has no readme file, and no documentation I can find. Am I missing something?

**Comment by lpw25** [comment]
There was this file:

  https://github.com/ocaml/odoc/blob/previous-master/lib/manual_usage.mld

which you see if you run odoc on itself. We used to host that at:

  https://ocaml-doc.github.io/

but the move between organisations seems to have broken that. You can still see the page
unstyled here:

https://ocaml.github.io/odoc/

**Comment by lpw25** [comment]
Baiscally the move between organisations has split the web site in half, leaving it useless.

**Comment by bluddy** [comment]
Aside from fixing this issue, it would be good to link to this site from the readme, and also to duplicate that first page in the readme.

**Comment by bluddy** [comment]
Scratch that -- this problem shows the fallacy of hosting this file in the first place. Just copying it to readme.md makes more sense.

**Comment by aantron** [comment]
@bluddy I added an initial [README](https://github.com/ocaml/odoc#readme) and a [`CONTRIBUTING.md`](https://github.com/ocaml/odoc/blob/master/CONTRIBUTING.md).

The README is a bit sparse, but there also doesn't seem to be that much useful information to put in it. Please let me know what you think, also you're welcome to PR anything you think should be in there.

**Comment by bluddy** [comment]
Nice job @aantron, especially on the `CONTRIBUTING.md`.

As for what to put in the readme, what kind of information does odoc support? Is it ocamldoc-style comments? Even if ocamldoc documents this stuff, we want to be independent of ocamldoc and its documentation.

Also, we probably want to mention odig, which is currently the easiest way to bulk create cross-referenced documentation (I think?)

**Comment by aantron** [comment]
[README updated](https://github.com/ocaml/odoc#readme).

**Comment by aantron** [comment]
Closing this. Work continues in #203 and #120.
