### ISSUE TITLE
Improve appearance

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#118]
Reading docs should be pleasant :) Good presentation guides the eye, and brings out the logical structure of content.

This issue is about the CSS and HTML. Basically, please submit PRs for any changes you'd like to make :) This applies to both tweaks, and more "global" layout changes. Also welcome are mockups, sketches, design discussion, and links to well-presented documentation from other languages or generators.

[`CONTRIBUTING.md` has a "Quick start" section][css-html] on CSS and HTML editing. For CSS, you might be able to get away without building odoc :)

Suggestions include:

- [ ] More thoroughly use a typographic grid.
- [ ] Use vertical whitespace more effectively for separating language elements, sections, etc.
- [ ] Adopt a color scheme.
- [ ] Figure out where to put tables of contents, introductory material, etc.

[css-html]: https://github.com/ocaml/odoc/blob/master/CONTRIBUTING.md#Quick_start

cc @pmetzger

**Comment by baransu** [comment]
For me, a great example of generated documentation is [ExDoc](https://github.com/elixir-lang/ex_doc) (and the whole https://hexdocs.pm) for example Ecto documentation: https://hexdocs.pm/ecto/Ecto.html. It's really high quality.
