### ISSUE TITLE
Add an upper-bound constraint on OCaml

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/odoc#1199]
odoc doesn't currently have an upper-bound constraint on its dependency towards OCaml. However it's a near certainty that it will be broken by the next version of the compiler.

To avoid myself and others having to do double the work in opam-repository (e.g. https://github.com/ocaml/opam-repository/pull/26640) I would encourage you to add the upper-bound constraints on your packages in both master and 2.4 branch

**Comment by kit-ty-kate** [comment]
Thanks! Could it be backported to the 2.4 branch as well just in case?

**Comment by Julow** [comment]
Yes: https://github.com/ocaml/odoc/pull/1201
Thanks for the issue :)

**Comment by kit-ty-kate** [comment]
ah sorry i missed that PR. Thanks!
