### ISSUE TITLE
Make sure in-page search works, despite any markup

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#125]
Ideally, we could even somehow test for this automatically. Ideas welcome.

Noted by @rleonid in https://discuss.ocaml.org/t/1841/10.

**Comment by rizo** [comment]
Is this just about the `->` markup using a regular dash sign? If so, I believe it's already fixed in master. If not, could you please give other examples?

**Comment by dbuenzli** [comment]
It may be larger than that see https://github.com/ocaml/odoc/issues/19#issuecomment-307637452

**Comment by aantron** [comment]
That was the only specific example, to my knowledge.

**Comment by yawaramin** [comment]
In page search is not working. E.g. go to https://b0-system.github.io/odig/doc/dolog/Log/index.html#val-info . Then search in page for `val info`. No results.

**Comment by hcarty** [comment]
@yawaramin I get `val info` highlighted + found when searching that page in Firefox.  Do you potentially have a browser plugin altering the page?

**Comment by yawaramin** [comment]
@hcarty you're right, it's working in FF. I also checked and confirmed it's working in Safari. However it is not working in Chrome incognito with no extensions. Strange. Could be a Chrome bug...

**Comment by hcarty** [comment]
Ah - yep, confirmed that it's not working on Chrome here either.

**Comment by dbuenzli** [comment]
I recently noticed this aswell it seems if you set `display: inline-block` on `span`'s it inhibits in-page search across these spans. 

If someone knows where this can be filed against `chrome` here's a repro case (I submited an issue via chrome's UI but the experience felt like writing to  `/dev/null`) :
```
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8">
      <title>inline-block search bug</title>
      <style type="text/css">
        span { display: inline-block }
      </style>
    </head>
    <body>
      <p>
        <span>Is</span> <span>this</span> <span>searchable?</span>
      </p>
      <p>
        Is this searchable?
      </p>
    </body>
</html>
```

**Comment by yawaramin** [comment]
@dbuenzli Chrome bugs are filed against the Chromium project, so https://bugs.chromium.org/p/chromium/issues/list . I tried a couple of different searches there but not finding anything more relevant than https://bugs.chromium.org/p/chromium/issues/detail?id=809886 , which talks about text-selection weirdness for inline-block spans, which also seems to present on odoc pages. May be related.

**Comment by dbuenzli** [comment]
I personally don't have gaccount (and I'm not willing to get one) but in any case that should not be a problem with `odoc`'s stylesheet, as far as I can see it doesn't use `inline-block` on code spans.

`odig`'s stylesheet does however [do this](https://github.com/b0-system/odig/blob/b9add704519889079dfb633d6ac1f5d1c9840683/themes/odoc.css#L198-L199), maybe should disable it -- but then we loose the nice line signature line breaking that was implemented by @trefis. Not sure if there's another way to achieve the same effect (well there must be, that's CSS after all...).

**Comment by dbuenzli** [comment]
So I found a workaround. Rather than making spans `display: inline-block`  make them `white-space: nowrap`. Cf fiddle here https://jsfiddle.net/s59g24vd/

**Comment by dbuenzli** [comment]
> So I found a workaround. Rather than making spans `display: inline-block` make them `white-space: nowrap`

Except CSS being CSS this has other unwanted effects on narrow viewports.  If the span width exceeds the container width this overflows and it's not possible to switch back to wrapping (which entails horizontal scrolling).

This is frustrating `display: inline-block` really does the right thing.
