### ISSUE TITLE
Link from docs to source files

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#128]
It should be as easy as possible to open a PR to fix docs. Relatedly, it should be easy to find the implementation of an API.

**Comment by HuStmpHrrr** [comment]
well, I don't think it should be closed....

**Comment by dbuenzli** [comment]
This was [added](https://github.com/ocaml/odoc/blob/master/CHANGES.md#230) in 2.3 but `odoc` drivers may be lagging.
