### ISSUE TITLE
Reason/OCaml syntax switching

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#129]
This is about outputting docs in Reason syntax.

Nothing needs to be done at the parsing end, because odoc reads docs from parsed ASTs (after the OCaml or Reason parser is done running), so the source syntax doesn't affect odoc.

https://discuss.ocaml.org/t/1841/13, https://discuss.ocaml.org/t/1841/47. The Ocsigen website has an example of switching (http://ocsigen.org/lwt/3.2.1/api/Lwt). cc @Drup

**Comment by ryyppy** [comment]
Hey 👋 
I am currently investing some time into this and try to submit a PR soon!

Hope this is okay?

**Comment by rizo** [comment]
The way I see this feature implemented and run is:

- Add the `--syntax=ml|re` option to `odoc html`.
- Implement an alternative HTML tree encoder for Reason.
- Generate both HTML trees.
- Have a button that changes the directory between `ml` and `re` trees.

@aantron What do you think about this approach?

**Comment by Drup** [comment]
Yeah, or you could just compile refmt to js and do the conversion of the fly.

**Comment by rizo** [comment]
@Drup I think it would be harder to achieve that for the markup. For examples, yes. But the markup is not purely textual, it has links and styling.

**Comment by aantron** [comment]
> Hope this is okay?

It is, and quite welcome :)

@rizo, I think that works. My original thought was to generate both OCaml and Reason output side-by-side in each HTML file, and use CSS to hide/show the right one. But this is probably bad for accessibility, navigation, etc., so separate output trees are likely to be better.

**Comment by aantron** [comment]
@ryyppy added Reason syntax output in #156. Right now, odoc generates one of either ML or Reason syntax each time it is run. What's left on this topic is to decide whether we want to always generate both.

**Comment by ryyppy** [comment]
@aantron @ostera So my idea to complete all of this was to basically generate both versions, but always hide one unselected version via CSS. By providing the `--syntax` flag, you will be able to decide on a default language to display whenever you load the docs for the first time.

As soon as this is done, we can add a JS-driven toggle for both syntaxes in the doc header.

**Comment by lpw25** [comment]
Not hard to too but can we make sure to have an option that only generates one or the other rather than both. Personally, I think that setting should be the default, but that's less important than having the option.

**Comment by rizo** [comment]
Totally agreed with @lpw25. Maybe the `--syntax` option could be changed to accept an ordered non-empty set of `ml|re` with `ml` as the default. The first syntax would be the one shown by default.

Additionally it would stop producing two file-system sub-trees for each syntax prefixed with `.../re/` and `.../ml` – reverting back to what current stable odoc does. This would mean that exclusively one of the syntaxes would be visible for the users (re xor ml), but depending on the `--syntax` option, both would be potentially generated. The syntax toggle button could later be added to allow the switch.

I think this should be relatively simple to achieve with the current HTML generation code. @ryyppy is this something you want to work on next? I think we should do this before releasing odoc.

**Comment by ryyppy** [comment]
@rizo Yeah, after doing some integration work in Dune, I think this is the right way to do it.
Another thing I wanted to have is the ability to use an ENV variable to set the `--syntax` parameter, mostly for the dune integration.

I think I can get this done this week.

**Comment by rizo** [comment]
Great, let me know if you need help with this!

>  I wanted to have is the ability to use an ENV variable to set the --syntax parameter

I believe you should be able to use [Cmdliner.Arg.env_var](http://erratique.ch/software/cmdliner/doc/Cmdliner.Arg.html#VALenv_var) for that.

**Comment by jordwalke** [comment]
Is there anything left to do on this one? I'm eager to get started trying out odoc. I like the discussion here about always generating both, but allowing doc authors to have total control over it if they want.

**Comment by ryyppy** [comment]
@jordwalke i am currently working on the syntax toggle feature... as soon as we get this in, we can switch the behavior of odoc to render both syntaxes by default and use the `--syntax` switch to opt into one specific syntax instead.

Will let you know as soon as this is done, then we should try to rebuild some essential doc pages of e.g. BuckleScript with the new odoc changes.

**Comment by yunti** [comment]
@ryyppy How is it going with this PR? Need any help?
