### ISSUE TITLE
Support multiple project versions and version switching

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#131]
This is a pretty standard and useful feature of most doc websites and generators, and we should probably make sure to support it.

https://discuss.ocaml.org/t/1841/56

**Comment by lpw25** [comment]
I would just note that this is more complicated than it appears, at least for the use case of a big docs repo like the proposed docs.ocaml.org. You may well need a nix-style hash of all the dependency versions if you want to ensure that there are no dead links. For example, if package `foo` has a module whose module type comes from package `bar` at package `baz` has a path that refers to something in that module, then `baz` needs to link into the documentation for `foo` compiled with the same version of `bar`.

Of course it could well be worth providing less complete version handling than that in the short-term for the use case of people generating their own documentation.
