### ISSUE TITLE
thousands of bisect files generated by odig odoc

### ISSUE THREAD

**Issue by avsm** [ocaml/odoc#138]
Running the latest development version of odoc generates a lot of bisect coverage files in the current directory, due to cd570b2157ff5f1ad27c09fc1e7eb5adb90da972 turning it on by default.

This does cause builds to take hours _vs_ minutes for large package sets. Is there any way to turn off coverage testing and still use a `opam pin odoc --dev` version in the doc generation scripts?

**Comment by aantron** [comment]
Yes, I made Bisect on by default to help new contributors a couple weeks ago, but I don't think anyone is checking coverage. I'll turn it off.

The ultimate solution to this is being worked for in https://github.com/ocaml/dune/pull/616, but we don't have to wait for that to fix the script.

**Comment by avsm** [comment]
Thanks; I'd be happy to save up and publish the bisect coverage from a bulk build if that'll help...

**Comment by aantron** [comment]
It should work now.

The bulk coverage files could be useful to see what features are actually being used in opam. However, I think we aren't ready to make use of the information soon.

**Comment by avsm** [comment]
Thanks! This is helpful to my prototyping a Dune+odoc build of the Real World OCaml docs on docs.realworldocaml.org (the URL isnt publicised yet so this is a good chance to experiment)
