### ISSUE TITLE
Add support for argot features

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#140]
Argot expands the ocamldoc format to include some more useful features such as tables. See the [manual](https://forge.ocamlcore.org/frs/download.php/956/argot.pdf).

Additionally, it supports searching, which has been further enhanced by @ivg to support type aliasing. See [here](https://github.com/ivg/argot).

We should incorporate these extensions into odoc, including the search capability.

**Comment by pmetzger** [comment]
Dunno if the licensing would be an issue, it's GPL and not ISC licensed, but perhaps the author could be induced to change that, or perhaps the table and similar features could be re-implemented.

**Comment by ivg** [comment]
It would be, but honestly, it wouldn't be possible to take any code from argot and make it work for odoc, so we can only borrow an idea, which is using the union-find data structure to represent types, and embedding javascript with data into the generated html. This is not licensed and not patented, so we can easily think about providing something like this for odoc.

**Comment by Julow** [comment]
This issue have been closed automatically but I think it should stay closed because it is not actionable.

I'd appreciate if you could open motivated issues for each features that you would like. Note that search is planned and is being worked on.
