### ISSUE TITLE
Add test packages, perhaps as submodules

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#142]
It'd be really great if we could have a selection of packages for testing odoc in real world scenarios. Currently, if we break certain packages, we can't really know about it until someone hits that wall.

In terms of automation, while we can't check for proper html output, we can at least check that content is being generated, which currently isn't the case for several examples.

**Comment by pmetzger** [comment]
We can check the html output a bit, by putting it through an HTML validity tester. We can't make sure it renders quite right of course, but the validity thing might be a bit of an improvement.

**Comment by pmetzger** [comment]
That too.
