### ISSUE TITLE
Is there a way to decorate the package page?

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#144]
@pmetzger pointed out to me that the package page - the first page you see when you land - is extremely barren and off-putting. Is there a way to improve that? Can we write a document that fills that empty page with explanations, examples and such?

**Comment by bluddy** [comment]
See this example from haskell (pointed out by @rizo): https://hackage.haskell.org/package/folds

**Comment by trefis** [comment]
I think you basically just want to write an `index.mld` file (this is well supported by `dune`, I don't know if `odig` is looking at them already) and that ought to be enough.
See for example : https://ocaml.janestreet.com/ocaml-core/latest/doc/base/index.html

**Comment by rizo** [comment]
I think maybe at some point it will make sense to integrate `odoc` package pages with respective `opam` package pages somehow. We do have rich metadata for packages, version information, dependency list, etc – it's just not shown by odoc.

**Comment by trefis** [comment]
N.B. this page is generated by an old version of dune; though I expect you'd get basically the same output with the current version.
I think `odig` could add some information on that page, i.e. the ones it's already generating (package version, licensing, etc.)

**Comment by trefis** [comment]
@rizo: that's not really odoc's job, that's odig. And it already does that.

**Comment by dbuenzli** [comment]
> (this is well supported by dune, I don't know if odig is looking at them already)

Not yet but you can hold your breath, back in this vicinity these days.

**Comment by bluddy** [comment]
OK thanks guys. Was hoping this was the answer. I added an issue about documenting mld pages -- something that's currently missing.

**Comment by rizo** [comment]
I think this can be considered done on the odoc's side. We implemented most features needed for odig to produce custom package pages that include the content of `index.mld`.

I still have some ideas about how the package page can be improved but I'll address them in separate more focused issues.
