### ISSUE TITLE
Add Containers as a dependency

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#145]
When working on my little PR, I found I needed a utility function, and had to move it out to another module. I feel like we're reinventing the wheel to some degree. It makes more sense to me to depend on a more fully-featured, light standard library like Containers, and not have to rebuild some low-level functions.

**Comment by dbuenzli** [comment]
Please don't. It's not a good idea for foundational tool to require much beyond the stdlib or other foundational tools. You quickly run into bootstraping issues. Improve the stdlib instead.

**Comment by bluddy** [comment]
We're already depending on Bos, so I don't see adding Containers as an issue. I view Containers + Bos as the modern OCaml development suite of choice.

Regarding the stdlib, we can't possibly rely on improving it in any reasonable timeframe for this package or any other. Aside from the endless bikeshedding for even a minor change, we wouldn't be able to use any new functions until several years down the road when the OCaml version is old enough for us to drop support for older versions.

**Comment by trefis** [comment]
> I view Containers + Bos as the modern OCaml development suite of choice.

And, exactly as you put it, that is a very personal view. That is not shared by the rest of the people working on the project.

**Comment by dbuenzli** [comment]
> We're already depending on Bos

Well that is news to me. But FWIW I don't think `odoc` should depend on `bos` either.

**Comment by aantron** [comment]
Bootstrapping seems like a future, not a current, problem for odoc. I'd say we can pick up Containers, or any other fairly reasonable dep, temporarily, if it speeds up development. And we can drop it later if it becomes an obstacle. Containers seems like a particularly easy library to import chunks of code from, if we will need to do that.

**Comment by pmetzger** [comment]
I'm going to have to agree with the "conservative" position here. `odoc` will be used at some point to build the main manual, so I think it's best if it has minimal dependencies. _BUT!!!_, my feeling on this is not very strong and if it's a big pain to operate without dependencies then ignore it!

**Comment by lpw25** [comment]
Not sure this makes much sense, but could we try to keep dependencies out of the "core" parts like the `Model`. I think they're quite likely to get pulled out as a standalone fundamental library at some point, for which no dependencies would be a plus. Of course it's not that hard to pull out a dependency from that kind of code later, so maybe just ignore me.

Re. containers specifically I don't really see why you'd need it for odoc.

**Comment by bluddy** [comment]
As far as bootstrapping, I think our concerns should be about the stdlib, dune and opam. I don't see why odoc, or any other library, should be limited in the same way.

@pmetzger for replacement of ocamldoc, we can just vendor odoc's bytecode into the compiler, together with any dependencies.

The reason I think it makes sense to have an expanded library is that we're currently writing utility functions strewn around the code, and I'm sure we also avoid some things that would be much cleaner with a more fleshed out standard library.

**Comment by lpw25** [comment]
> The reason I think it makes sense to have an expanded library is that we're currently writing utility functions strewn around the code

Citation needed.

Containers is a large dependency to take on for some hypothetical utility functions. If we were going to make extensive use of its various additional data structures it would make sense, but I don't think a few small functions is worth it. I don't think it really matters, there's not much harm and it can be easily undone later if needed, but I don't find your argument very convincing.

**Comment by dbuenzli** [comment]
> As far as bootstrapping, I think our concerns should be about the stdlib, dune and opam. I don't see why odoc, or any other library, should be limited in the same way.

No. It means I can't use `odoc` in `bos`'s build system.
