### ISSUE TITLE
Document .mld files

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#146]
We have instructions about ocamldoc syntax (from ocamldoc itself), but nothing about how .mld files work. Even a few sentences would help. Mention `index.mld` and any other relevant info.

**Comment by trefis** [comment]
There is an embryo of documentation already, it's just not easily accessible (or pretty): https://ocaml.github.io/odoc/manual_usage.html

**Comment by pmetzger** [comment]
Where would that most logically be moved?

**Comment by aantron** [comment]
@rizo, almost all of https://ocaml.github.io/odoc/ is either outdated, or not relevant to the vast majority of users. So, I would prefer not to link it, as it can only confuse people. Relevant and updated bits of it are already in the README. I suggest we add a note about `.mld`s to the README for now.

**Comment by rizo** [comment]
This is fixed in my recent PR: [#217/files#diff-bfc958f](https://github.com/ocaml/odoc/pull/217/files#diff-bfc958f9c8392123fb31875cd27acb5fR30). 

Improvements and corrections are welcome!
