### ISSUE TITLE
Please stop displaying the `odoc should not generate html ...` warning

### ISSUE THREAD

**Issue by diml** [ocaml/odoc#158]
I'm seeing this warning often when building documentation with odoc. Given that this is not a warning users can remove by modyifing their own code, I suggest to stop displaying it.

**Comment by rizo** [comment]
This seems to be a duplicate of https://github.com/ocaml/odoc/issues/169 resolved in https://github.com/ocaml/odoc/commit/00b60464a2d9e3409b17e60cc91aa221612431c4.
