### ISSUE TITLE
Support namespacing of tags.

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#159]
Just like the compiler recognizes `[@foo]` and `[@ocaml.foo]`, it would be nice if tags present in docstrings could be prefixed as well, for example `@open` and `@odoc.open`.

**Comment by aalekseyev** [comment]
One reason for this is that unqualified [@open] suggests that some scope manipulation might be happening in OCaml land, whereas actually nothing is happening. I think that makes this notation very confusing (much more so than the `@ocaml.` abbreviations).

**Comment by aalekseyev** [comment]
@trefis Explained that since the string occurs in the comment I should know this shouldn't possibly affect semantics. That's a good point. (but it's not entirely impossible and I was still confused when I first saw it, possibly because I didn't notice that it was a comment)
