### ISSUE TITLE
`odoc compile-deps` does not work on `.cmt` files

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#162]
```
> odoc --version
v1.1.1-710-gdd47a98
> odoc compile-deps int64.cmt
odoc: internal error, uncaught exception:
      Cmi_format.Error(_)
      Raised at file "typing/cmi_format.ml", line 74, characters 6-21
      Called from file "src/odoc/depends.ml", line 31, characters 18-43
      Called from file "src/odoc/bin/main.ml", line 218, characters 17-72
      Called from file "src/cmdliner_term.ml", line 27, characters 19-24
      Called from file "src/cmdliner.ml", line 106, characters 32-39
```

**Comment by dbuenzli** [comment]
Basically [this bit](https://github.com/ocaml/odoc/blob/master/src/odoc/depends.ml#L29-L35) needs to be conditionalized for `.cmt` files. See e.g. [here](https://github.com/dbuenzli/omod/blob/master/src/omod_ocamlc.ml#L162-L177) on how to read that info.

**Comment by dbuenzli** [comment]
Also it might be nice to do a little bit of data cleaning: 

1. Do not report self-references. 
2. Do not report duplicates self-reference duplicates (which may exist on ocaml versions before [this patch](https://github.com/camlspotter/ocaml/commit/e5cf18cfa0ff033e55a4f33c3d901b930609affc) was merged):

[This function](https://github.com/dbuenzli/omod/blob/master/src/omod_ocamlc.ml#L44-L70) in `omod` does that. 

Here's an example of unclean data on `4.03`:

```
> odoc compile-deps odig_odoc.cmti
Buffer 3bd1af04573ce2da7fc3dc04403e852e
CamlinternalFormatBasics 9642e3ed163e46770985ca668738ed5f
Digest 23fdbfc720a71002434f407c37d040a3
Format 60c2e7663dd57d13b5920931742e1c10
Lazy b2e565a5cdbd351dc15bc9061d30c458
Map f23f0e2510f18d4b11ad6f7771618294
Odig fd0e5fd19fad6558e8c10b09070120b6
Odig_odoc 059818369bd7b50c5a94fb604d892d22
Odig_support 2c79861dbb19e31112fc6447b622ca6a
Pervasives 999b28e3b7638771c87eebf5a8325e42
Set a16cc25d9afe91eb22559bef41e9ee28
String c28a3ca42a30c6ffa0bbab4a05329226
Odig_odoc 059818369bd7b50c5a94fb604d892d22
```

**Comment by dbuenzli** [comment]
And a question, is it ok to [simply drop](https://github.com/ocaml/ocaml/pull/781) module aliases at that point ?

**Comment by trefis** [comment]
> And a question, is it ok to simply drop module aliases at that point ?

Yes, and it's actually necessary if you don't want to report cyclic dependencies which aren't there.

**Comment by sharno** [comment]
I tried to pick this up and wrote a fix but I couldn't reproduce the issue, made a simple project and compiled it with dune to get a `.cmt` file but it produces regular output and doesn't give an error even after checking out to the commit you have in your example.
I'm a bit new to the OCaml ecosystem so am I missing something?

**Comment by dbuenzli** [comment]
My guess is that your `test.ml` file might be empty (and self dependencies are still reported). Just test the tool on one of the `cmt` file you can find in `$(opam var ocaml:lib)`. The current code is obviously wrong since it's not special cased for `.cmt` files, see the various links I posted above.

**Comment by dbuenzli** [comment]
> 1. Do not report self-references.

In the end this is still useful, see discussion in #271; so it kept but documented as such.
