### ISSUE TITLE
should not generate html but will for the time being

### ISSUE THREAD

**Issue by fritzsche** [ocaml/odoc#169]
after converting my project from make/ocamlbuild to dune (former jbuild) I get lot of warnings when generating documentation "should not generate html but will for the time being"
Same was reported in closed issue:
* https://github.com/ocaml/odoc/issues/99

What I do not understand from the previous issue is on how to silence this warnings in a dune setup.

I have notice other project have the same issue:
https://github.com/alainfrisch/sedlex
(if you run "make doc")

**Comment by trefis** [comment]
Yes, the warning should appear very frequently with dune.
We should just silence it on our side until the situation improves.

**Comment by aantron** [comment]
I converted it to a comment in the file.
