### ISSUE TITLE
uncaught exception: Parser__Helpers.InvalidReference

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#178]
Because of the reference on that line: https://github.com/ocamllabs/ocaml-ctypes/blob/master/src/ctypes/ctypes_types.mli#L367

```
odoc: internal error, uncaught exception:
      Parser___Helpers.InvalidReference("unknown qualifier `(@'")
      Raised at file "src/parser/helpers.ml", line 28, characters 14-72
      Called from file "src/parser/helpers.ml", line 258, characters 28-47
      Called from file "src/parser/helpers.ml", line 338, characters 10-38
```

**Comment by aantron** [comment]
This is a duplicate of https://github.com/ocaml/odoc/issues/90#issuecomment-355248618.

**Comment by aantron** [comment]
Actually, reopening this, because we want to keep the other issue for actually fixing the reference parser *syntax*.

The attached commit fixes the immediate issue of the current (and original) reference parser not being able to handle operators with dashes for the short term.
