### ISSUE TITLE
Internal error due to truncated mld names

### ISSUE THREAD

**Issue by Octachron** [ocaml/odoc#181]
Trying to compile a mld file named `a.mld` generates an uncaught error

```
odoc compile a.mld --package Test
```
>odoc: internal error, uncaught exception:
      Invalid_argument("String.sub / Bytes.sub")

This stems from `compile.ml`  assuming that all output name for `mld` file are prefixed by `page-`, which is not the case if the option `-o` is not specified.

**Comment by rizo** [comment]
Maybe we should just make the output required in this case?

I also I don't really understand why the `page-` prefix is a requirement and not a convention in odoc.

**Comment by trefis** [comment]
> This stems from compile.ml assuming that all output name for mld file are prefixed by page-, which is not the case if the option `-o` is not specified.

Something may have changed, but at some point it should have been the case even if `-o` wasn't specified, at least according to https://ocaml.github.io/odoc/manual_usage.html

> I also I don't really understand why the page- prefix is a requirement and not a convention in odoc.

Namespacing. So you can have `foo.mld` and `foo.ml` and everything is going to be fine.

**Comment by rizo** [comment]
FYI, I’m preparing a PR to fix this.

@trefis thanks for the clarification.
