### ISSUE TITLE
Revisit allowing nested emphasis/tags

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#188]
From #185 we learned that the nested emphasis supported by `ocamldoc` is allowed but warned upon by `tidy-html5`.

Opening this issue to record that we may want to revisit this, and not ignore that particular warning in the future.

**Comment by aantron** [comment]
Nested emphasis is allowed by ocamldoc, HTML, and LaTeX. I wonder why tidy complains about it.

It seems to work even in Markup:

```
*foo *bar* baz*
*foo* bar *baz*
```

> Inspect these elements:
> *foo *bar* baz*
> *foo* bar *baz*

Though I wonder if this depends on the parser, and is one of those corner cases for which CommonMark was created.

I think we should allow nested emphasis. It's well-supported, and the decision is backwards-compatible. If we ever need to support an output format that doesn't allow nested emphasis, we can emit a warning during output, and then do nothing for it, emitting just the content.

**Comment by aantron** [comment]
I'm going to close this as "we should keep supporting," feel free to comment further if there are other ideas.
