### ISSUE TITLE
Leaked state between tests

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#192]
While working on #185 I encountered an issue related to running tests — apparently, the `theme_uri` tests seem to override the `Section/index.html` (and perhaps other files too), making the diffing work on the wrong outputs.

I had to disable those tests while working on the PR, but after all my changes were there, reenabling them seemed to work just fine.

Original comment:  https://github.com/ocaml/odoc/pull/185#discussion_r217885289

cc @aantron @rizo

**Comment by rizo** [comment]
It seems that there's a namespacing issue with output generation. The diffing/promotion is ignoring the additional options like `theme_uri` and one of the tests overwrites the content of another.

I'm currently refactoring `test.ml` in a way that should avoid this problem.
