### ISSUE TITLE
Publish as an `npm` installable package

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#195]
Now that `odoc` has 4.02 support and works with BuckleScript, I was thinking it'd be more reachable for people working from the js-side of the ecosystem if it was an `npm install odoc` away.

If this worked, then perhaps it could be included with the set of binaries in `bs-platform`.

Opening the issue to gather comments and feedback 🗒

**Update / To do**.
- [x] Equip repo to build `npm` package — #214 
- [ ] Figure out multi-platform packaging
- [ ] Publish `npm` package

**Comment by rizo** [comment]
I think it sounds reasonable if that's the preferred installation for BuckleScript projects.

Here are some questions I have?

* Does this need to be done (and managed in the future) officially by the odoc project?
* Does this require any changes to the project structure, etc?
* How would the installation work (i.e. do we need to precompile binaries)?
* Are there any existing tools (esy?) that can help us with this?

**Comment by aantron** [comment]
If we use esy, we don't need to precompile binaries. However, the installation could take a pretty long time, depending on whether the user has already installed a compatible compiler with esy.

We shouldn't have to change the project, except to add the NPM and esy boilerplate. And yes, we will have to maintain this.

**Comment by aantron** [comment]
@rizo for a really simple example, see [Repromise_lwt](https://github.com/aantron/repromise_lwt). In the repo, you'll find a really simple, ordinary opam+Dune project, packaged for both regular opam and esy.

**Comment by ostera** [comment]
@aantron without introducing another tool into the mix — what would be a _from first principles_ approach to publishing precompiled binaries as an `npm` package?

Given that the audience installing with `npm` _will be using 4.02.x+buckle-master_, perhaps we could only publish a precompiled bytecode with embedded runtime?

Looking for the least _magic_ 🔮approach.

**Comment by aantron** [comment]
@ostera I think with an esy setup, the user won't see that esy is running during the build. Not 100% sure at this point. This will probably be the least magic approach for us. It does have the downsides of a long install time and potential build failures, though. We can minimize the risk of failures with `esy.lock`.

We should be able to publish odoc as a binary compiled to bytecode, and to make it portable, we can run it with `ocamlrun` from the BuckleScript install.

This is one of the reasons I wanted odoc to be one self-contained binary (we had a discussion about this here https://github.com/ocaml/odoc/pull/154#issuecomment-403892559).

odoc doesn't inherently have any runtime dependencies except either ocamlrun (if bytecode) or a specific operating system (if native), so I'd like to avoid introducing any artificially.

**Comment by ostera** [comment]
> We should be able to publish odoc as a binary compiled to bytecode, and to make it portable, we can run it with ocamlrun from the BuckleScript install.

I'd prefer this than introducing esy, but I don't have a lot of experience running/distributing bytecode binaries so there's possibly tradeoffs I'm not aware of.

Might be my naïveté kicking in but it seems like the simplest possible solution would look like:

1. Add `package.json` with `bs-platform` as a peer dependency (so we enforce the version used on the project)
2. Make a publish script that will compile the bytecode, and wrap it in a dispatcher that can find the appropriate `ocamlrun` through the currently installed `bs-platform` binaries.

> odoc to be one self-contained binary

This isn't necessarily needed when publishing as an npm package, since the package itself will live in `$NPM_ROOT/odoc` it'll have access to several other files that can be accessed directly (such as the support files).

But naturally, it'll be easier to move around if the support files were bundled with the bytecode too.

**Comment by aantron** [comment]
@ostera If it's not self-contained, we will need to build in various paths depending on whether we are releasing to opam or NPM. It is indeed easier for odoc to be self-contained whenever external files are not strictly necessary.

**Comment by aantron** [comment]
...and I think your summary of how to publish the bytecode is pretty much right :)

**Comment by ostera** [comment]
Cool, I'll open an exploratory PR sometime this weekend.

**Comment by avsm** [comment]
I've started compiling binaries for several platforms (and a bytecode one) in the https://github.com/avsm/platform repository (which will be moved to the `ocaml/` namespace when it's stable).  I could arrange for a subset of this to be hooked up to the odoc CI if useful for this. 

From past experience, it's hard to make ocaml bytecode portable across operating systems due to runtime linking dependencies, but the CI covers a number of platforms for generating binaries.  The build is also self-contained and only requires a C compiler (but an existing ocaml can be used if available)

**Comment by ostera** [comment]
After looking into it, there is no `ocamlrun` being distributed with the `bs-platform` npm package. 😞

This means that we'll have to explore other distribution mechanisms, including `esy`.

@avsm, what would you recommend for this?

**Comment by avsm** [comment]
I'd recommend a vendored odoc distribution; I'll be pulling avsm/platform into a proper beta release this week sometime. @dra27 and I are just finishing up Windows support so that we can emit executables, and then it'll be a standalone repo that will build binaries for all supported OCaml platforms for odoc, opam, dune, etc.

**Comment by avsm** [comment]
Note: you can experiment with this yourself by trying out the https://github.com/avsm/duniverse tool, if you don't mind some rough edges. Feedback welcome there.

**Comment by ostera** [comment]
@avsm I take it by `vendored odoc distribution` you mean building and distributing `odoc` with the bucklescript platform?

**Comment by andreypopp** [comment]
If odoc doesn't have any runtime dependencies then the easiest probably is to publish a set of binaries (one for each platform). We (at fastpack and esy) use CI to build such binaries. Right now we are making use of Azure DevOps Pipelines (fastpack already transitioned and esy is in process) which produce an npm package with all binaries for three main platforms (Windows, macOS and Linux (glibc)) on each commit.

**Comment by ostera** [comment]
I'll be meeting with @ulrikstrid for the ReasonSTHLM meetup this Thursday — he's been pointing me to the right places to get this working like @andreypopp suggests. Might be able to get something up this weekend :)

**Comment by ryyppy** [comment]
@ostera for building standalone executables (macos, linux & windows), we use a CircleCI & Appveyor pipeline for [genType](https://github.com/cristianoc/genType) and it works pretty well

**Comment by grabbou** [comment]
Not sure if this is the best place to comment, but just wanted to let you know that installation instructions in the main readme don't work. 

You need to run `opam pin` and let it install the Github version. Otherwise it tries to install the latest one and fails to match the dependency on OCaml.

**Comment by rizo** [comment]
The README includes installation instructions for the stable odoc release. The Bucklescript support is currently still in master. I think we should mention the need to pin the package in the Bucklescript section.

**Comment by czystyl** [comment]
I created a small PR where I added exact command what needs to be run in the ReasonMl projects.

**Comment by aantron** [comment]
Ok, #214 equipped this repo with NPM packaging. I think we need to update the README now with instructions for how to install with NPM from git. Later, for some release, we should decide that we want to publishing proper releases in NPM.

**Comment by ostera** [comment]
Updating with some **To-dos** to debate:
- [x] Equip repo to build `npm` package — #214 
- [ ] Figure out multi-platform packaging (binaries for win/linux/macos)
- [ ] Publish `npm` package

Worth noticing that Travis now supports Linux/macOS stably, and [the Windows beta just got out](https://blog.travis-ci.com/2018-10-11-windows-early-release?utm_source=twitter&utm_medium=web&utm_campaign=windows_early_release)!

**Comment by ostera** [comment]
Just an update, I'm looking to vendor `odoc` into the BuckleScript platform so that we don't need to publish a binary to `npm` from this repository.

Instead, anyone installing `bs-platform` would get an `odoc` binary that works with their version of it.
