### ISSUE TITLE
Stable structured output (a.k.a `odoc json ...`)

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#196]
Something I've been considering recently has been extending `odoc` with a `json` module that would export the complete cross-referenced environment as a single json blob that can be used for:

* Generating search indexes — throwing these at elasticsearch would already do miracles for a _hoogle_ style website, and could allow for quick experimentation on the concept
* Building a single-page application powered by this data — no need to modify the existing html generation 👌 
* Opening up the experimentation to a bigger audience!

I'd consider other formats but json seems to be ubiquitous and fast-enough for the use-case of documentation generation.

Opening this issue to gather comments and feedback 🗒

**Comment by lpw25** [comment]
> Generating search indexes — throwing these at elasticsearch would already do miracles for a hoogle style website, and could allow for quick experimentation on the concept

I should probably mention that we have a branch here:

https://github.com/lpw25/odoc/tree/elasticsearch

which generates JSON that use with elasticsearch for a search index within Jane Street.

It needs tidying up and the interface should be changed, which I haven't had time to do, but it should probably be added upstream at some point.

I think it is better to have odoc produce some JSON specifically for search indices than just dump everything as JSON and work from that. For a start you shouldn't under-estimate the size of the data. The documentation of our tree is quite a few Gb and we would rather not have another even larger JSON copy just so we can extract the much smaller search data.

That's not to say you might not want to have a JSON dump for some other purpose -- I'd just rather support the search stuff without needing it.

**Comment by ostera** [comment]
@lpw25 I understand the pragmatism behind the search-index only approach, it is however a tad limiting for exploration and could lead to multiple json-exports that are perhaps too specific to be a part of `odoc`. Although a far-fetched example, I can't imagine `odoc slackbot` being a thing.

I'm envisioning the following usage:

```sh
# Build a search index, internally may or may not use the complete json export
odoc search-index > elastic-search-dump.json

# Export the complete documentation tree as JSON
odoc json ... > ./data/docs.json

# Run a GraphQL server from it
json-graphql-server data/docs.json

# Explore it with `jq`: i.e, get all the nested modules types
echo ./data/docs.json | jq '.modules[.modules[types]]`
```

And naturally, you can use this data to power any sort of application.

The point is that `odoc` doesn't *necessarily* decide anymore.

**Comment by rizo** [comment]
I must suggest that an alternative approach could be converting the `.odoc` files into JSON separately. This functionality doesn’t have to be embedded into odoc itself.

In fact, that’s what I did to implement a [prototype of the search feature](http://odis.io/doc/order-search/) for a package.

**Comment by ostera** [comment]
@rizo if the `.odoc` format is stable, then this should be a perfectly viable solution.

**Comment by lpw25** [comment]
> I'm envisioning the following usage:
>
> # Build a search index, internally may or may not use the complete json export
> odoc search-index ... > elastic-search-dump.json
>
> # Export the complete documentation tree as JSON
> odoc json ... > ./data/docs.json

That's what I was attempting to suggest. I think having `odoc json` is fine, I just think that the search use case should be specifically catered for with its own commands.

**Comment by rizo** [comment]
Another important note, related to https://github.com/ocaml/odoc/issues/137, is that odoc is limited to producing a JSON representation (or any other format really) for a single compilation unit and not the whole package. I see this as a significant limitation for the search feature that would typically be implemented for the whole package. See my [suggestion](https://github.com/ocaml/odoc/issues/137#issuecomment-423153933) in the mentioned issue for a potential solution...

**Comment by MoOx** [comment]
I think a "simple / standard" json output could be very nice. This might help to have better interop with any kind of solutions without having to generate a custom things (ref #121)

**Comment by rizo** [comment]
There is an ongoing effort to implement JSON output generation as part of the work to improve reasonml.org documentation. See: https://www.reason-association.org/projects/doc-tools

The resulting work will, at some point at least, be upstreamed to odoc.
