### ISSUE TITLE
Bring Reason Syntax up to par with Refmt v3

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#199]
I've been meaning to bring up the reason syntax printing on part with `refmt`, so I'm opening this issue to track the work that needs to be done, and we can reference it from smaller PRs until this is more or less completed.

- [ ] Compact arguments:
    `'a => 'b => 'c` should be `('a, 'b) => 'c`

- [ ] Optional arguments:
    `?l: 'a => 'b` should be `(~l: 'a=?) => 'b`

- [ ] Long signatures should break arguments into individual lines (cc @grabbou):
    `('a, 'b, 'c, 'd, ... /* ad nauseum */) => 'z` should be 
```
(
  'a,
  'b,
  'c,
  'd,
  ...
) => 'z
```

- [x] Space _around colons_ is normally a single space _after_ the colon:
  - [x] Record attribute name `{ a : 1 }` should be `{ a: 1 }`
  - [x] Object attribute name `{ a : 1 }` should be `{ a: 1 }`
  - [x] Function signature `let f : 'a => 'b` should be `let f: 'a => 'b`
  - [x] Tweened Type annotations `(a : unit)` should be `(a: unit)`

-----

If you have some more please comment below and I'll add them to the top-level list so we get some coverage 🙌 

cc/ @ryyppy @aantron

**Comment by Drup** [comment]
@ostera If you want to move this forward, the new implementation should be more accessible, and thus easier to tweak for this.
