### ISSUE TITLE
Cross-module references dont work

### ISSUE THREAD

**Issue by grabbou** [ocaml/odoc#200]
During my work for documentation of [`bs-react-native`](https://reasonml-community.github.io/bs-react-native/BsReactNative/status.html), none of the references to other modules work.

After digging around the documentation, it looks like the references are resolved properly - none of the links are underlined with red color and message about missing module. 

References to local modules (included within the current one) work w/o issues. I am using `{!XYZ}` syntax for this.

Please check https://reasonml-community.github.io/bs-react-native/BsReactNative/status.html, https://github.com/reasonml-community/bs-react-native/blob/master/docs/pages/page-status.mld.

CC: @ostera

**Comment by ostera** [comment]
This doesn't seem to be a problem anymore since #204 — can you confirm @grabbou?

**Comment by ostera** [comment]
I think we should close this.

BuckleScript moving on to doing automatic means we won't be able to reference things by their expected name, but we can push this responsibility to the orchestration tool.

Alternatively, we could add a `--namespaced <pkg-name>` flag, but I feel strongly **against** it. It's behavior will have to be kept in sync with BuckleScripts behavior, it adds unnecessary complexity to `odoc`, but it'd let orchestrating tools just read the `bsconfig.json` and know to pass (or not to pass) this flag.

I'd really like to know what's the reason behind automatic namespacing.

**Comment by aantron** [comment]
Thanks, let me know if we should reopen.
