### ISSUE TITLE
References in lists are broken

### ISSUE THREAD

**Issue by leostera** [ocaml/odoc#202]
**Input**
```ocaml
+ {!Module.name}
```

**Expected Output**
A link to `Module.name` in a numbered list.

**Actual Output**
A numbered list with an unresolved reference to `Module.name`

**Workaround**
If I remove the list, so the input becomes simply `{!Module.name}` the reference works just fine.

Possibly related to #200

**Comment by ostera** [comment]
scrap that, they don't work in lists at all.

**Comment by ostera** [comment]
**Input**
```ocaml
{ul {li {!Module.name}}}
```

Same output.

**Comment by grabbou** [comment]
Faced that one too actually!

**Comment by aantron** [comment]
> Do you think this is something an external contributor could take?

Probably :)

The most likely problem is that the code that finds or resolves references isn't descending recursively into lists.

The comment syntax AST is defined here: https://github.com/ocaml/odoc/blob/master/src/model/comment.ml

The easiest way to find existing code that traverses this is to grep for `` `Paragraph ``, which is one of the relevant constructors in the AST. I think this method...

https://github.com/ocaml/odoc/blob/3f35c0a3b2d56a773b4beddf954b00f40ca6394c/src/model/maps.ml#L889-L896

needs to be changed to call itself recursively on `` `List ``.

The class this method is in implements a recursive traversal of docs. Elsewhere, in directory `xref`, some other class inherits from this class, and overrides the traversal method that handles `` `Reference `` to process references, including resolving them.


As you can see in the code above, when the traversal encounters any `nestable_block_element` constructor besides `` `Paragraph `` and `` `Modules ``, it doesn't descend into it. It just returns the subtree unchanged.

**Comment by aantron** [comment]
...and as further confirmation that this code probably never descends into `` `List ``, searching that file (`maps.ml`) for `` `List `` gives no results :)
