### ISSUE TITLE
Present release impact publicly

### ISSUE THREAD

**Issue by ostera** [ocaml/odoc#221]
From issue #217's @dbuenzli and @aantron talked about the hidden impact of a release, and mentioned a `corpus` script that helps you run `odoc` on bigger chunks of the ecosystem.

I'd like to explore running this corpus script or `odig`, in a controlled but public environment, on big chunks of the ecosystem (possibly randomly sampled) to be more explicit about the impact that a release will have.

An ideal flow, to me, looks like:

1. Tag a release candidate -- 1.3.1-RC
2. Have a CI pipeline with persistent storage run that particular tag on the packages
3. Export results in a machine-readable format

#### Why step 3 instead of just failing if there's something broken?
Because I believe that _some_ regressions *will be intentional*, and this should just be an indicator. We can then use these data to build user-friendly tools, such as a gh-pages published website, that will show a list of packages that can seamlessly upgrade with this release, a-la [Reasonably Typed's "Is It Ready" table](https://rrdelaney.github.io/ReasonablyTyped/#is-it-ready-table).

![screen shot 2018-10-18 at 09 33 00](https://user-images.githubusercontent.com/854222/47138142-dbe78a00-d2b8-11e8-8514-8f9c3bcbb062.png)

(minus the big NO)

-----

I believe this would make it easier for people to see the impact of a release, which will help grow confidence that the release is safe to upgrade to.

Should address some of @dbuenzli's concerns and certainly make @aantron's release-job smoother 🙌 I know that by the time the Reason package index uses `odoc` automatically, I'd want to know how many of those docs will be busted.

Also I want to be clear that I am *not proposing we implement this before the next release*. Just opening this for discussion.

Thoughts?

**Comment by dbuenzli** [comment]
> Thoughts?

I don't think that's very useful. If the job is done correctly most problems will not be related to actually compiling. It will rather be in rendering/linking bugs which you can't assess this way. It could maybe be if you want to evolve the ocamldoc language but OTOH that should be pretty stable by now. I'd suggest not to waste time on this.

**Comment by ostera** [comment]
Perhaps I didn't make my point clear. I might sin of verbiage 😅

It doesn't have to be _the current corpus script as is_, so long that is _a corpus script_. So IMO, running `odig` to generate cross-package links is absolutely not out of the question.

**Comment by dbuenzli** [comment]
> Perhaps I didn't make my point clear.

Well apparently so do I... `odig` or another script was not my point, my point was that it will be difficult to assess breakage based on simply running the tools.

**Comment by lpw25** [comment]
I think that you can catch the worst breakages by running the tools and analysing the output. The biggest problems I have with 1.3.0 could have been caught with something like this -- as long as it detects the tool crashing, and the number of files for which nothing is generated. You could also check the output to make sure that links have a valid destination -- which is not always true now but you could look at is the change between versions.
