### ISSUE TITLE
Limit reference kind syntax to only what is supported by ocamldoc, where we have redundancy (suggestion)

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#243]
ocamldoc supports these qualifiers for reference path components: http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sec359, at a glance in odoc:

https://github.com/ocaml/odoc/blob/e8f7dcf218ceaa0da89e16ec2936c8a0cc3efe41/src/parser/reference.ml#L5-L20

odoc supports additional qualifiers:

https://github.com/ocaml/odoc/blob/e8f7dcf218ceaa0da89e16ec2936c8a0cc3efe41/src/parser/reference.ml#L22-L34

As can be seen, there is some overlap, where odoc supports alternative syntax for qualifiers already supported by ocamldoc. The suggestion is to remove support for the redundant qualifiers added by odoc. We will still need some qualifiers over ocamldoc, such as `page` and `extension`.

cc @trefis

**Comment by trefis** [comment]
I'm not sure what you're suggesting. Is it that you want to drop support for (say) `{!Foo.type-t}` and require people to write `{!type:Foo.t}` in that case?

If that's the case then I don't think it's a good idea. `ocamldoc` syntax is clearly more limited than the new one, so we'd need to keep the new form for things like `{!module-type-Foo.type-t}`, and requiring people to use the `qualifier-` syntax for everything but the last element, where the must then switch to having the qualifier as a prefix seems like a bad design.
In a perfect world people would gradually switch to the new syntax, we'll deprecate ocamldoc's syntax at some point, and perhaps even remove support for it later on.

**Comment by aantron** [comment]
We currently support `{!class-type-foo}` and `{!classtype-foo}`. I'm suggesting to support only `{!classtype-foo}`. I'm not suggesting to remove the new qualifier syntax, just to remove redundant qualifier strings, always in favor of qualifier strings already supported by ocamldoc, when there is one (`extension` has no counterpart in ocamldoc, for example).

**Comment by trefis** [comment]
Ah! Thanks for the clarification. I agree then.

Btw, we should probably try to have the reference qualifiers match the strings we use for anchors in the produced html. Does that make sense to you?

**Comment by aantron** [comment]
Yes, I agree with that too :)

For the next release, I'll change odoc to warn when it encounters the redundant qualifier strings, and accept them. After some time, we can remove support for them. Then, any docs that still use them will suffer the ordinary recovery from an invalid reference, which is that the reference will not be resolved (details in #242).

**Comment by lpw25** [comment]
I agree we should only have one name, but I'm not sure we should necessarily choose the ocamldoc one. Some of them are not very clear, like `const`, and some are hard to guess/remember, like `recfield` and `modtype`. I don't think the weirder ones are used very widely in the wild, so we could probably get away with deprecating them.

**Comment by aantron** [comment]
I agree that some of the new names are clearer, so I suggest we use the new names...

- `module-type` instead of `modtype`
- `class-type` instead of `classtype`
- `constructor` instead of `const`
- `field` instead of `recfield`

Using the old names in either `{!NAME:foo}` or `{!NAME-foo}` position will emit a warning that suggests the corresponding new name be used instead.

We will drop the new name `exn`, because I think ocamldoc's `exception` is more predictable, and matches the language keyword, whereas `exn` is just a metavariable. By that same kind of argument, though, I'm not sure if we should prefer `val` (from ocamldoc) or `value` (added by odoc). `val` is the keyword, while `value` is of course the right term in human speech :) There is also the historical precedent of anchors having syntax `VALfoo`.

I'd also like to change `label` (a new name) to something else, because I think it's not clear. The referent of `label` is not a label, it's a section of some kind. The *label* in the section heading is just used to identify the *section* so that it can be referred to. Also, besides section labels, the whole odoc+OCaml language has argument labels, field labels, etc. *Label* is basically a generic word for a name to identity a referent by, so the `label` qualifier is not informative. Perhaps `section` is the right replacement?

**Comment by aantron** [comment]
Thinking about it more, I think I prefer `val` for OCaml. It matches what's written in signatures, and is familiar. I imagine people with very little PL background are not immediately thinking of each value as a *value*, but rather as a function, `int`, `string`, etc., according to its type signature.

There is, however, the issue that `val` is not used in ReasonML, instead values are declared with `let` in signatures. I think this would be the main argument in favor of `value` (or maybe even some other option).

**Comment by dbuenzli** [comment]
Whenever the keywords exist in the module specification language I think it is valuable to exactly match them (modulo space to dash translation). I don't see any good justification in being creative here, it would only increase the cognitive burden of dealing with the language and its eco-system.

**Comment by aantron** [comment]
That's right, I forgot we already support `section` because it's in ocamldoc. So I suggest we just drop `label`.

**Comment by lpw25** [comment]
Yeah, I called them labels within odoc originally because I had some vague ideas about allowing them in places other than section headings, but it never went anywhere so going back to section is fine.
