### ISSUE TITLE
Missing space after exception declaration with 1.3.0 CSS

### ISSUE THREAD

**Issue by jorisgio** [ocaml/odoc#245]
On firefox on linux (Xorg, intel GPU), no space is displayed between the `exception` keywords and the excpetion name : 
![screenshot-2018-11-14 url ahrefskit url](https://user-images.githubusercontent.com/1108145/48485770-b23c6700-e854-11e8-8506-dd8cad1c96c8.png)

Reproduced withFirefox 60 and nightly.

**Comment by aantron** [comment]
Thanks. It's also broken in Chrome:

![exception](https://user-images.githubusercontent.com/12073668/48488099-9c438d80-e7e5-11e8-81c5-b04151706303.PNG)

It looks like a CSS issue at first glance.
