### ISSUE TITLE
Disable programming ligatures in code blocks

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#248]
I noticed that ligatures (e.g. `|>` rendered as a triangle arrow, `=>` rendered as a fancy arrow) make code blocks more difficult to read. I imagine someone unfamiliar with Fira Code ligatures (or programming ligatures in general) would be confused by what they are seeing. *I* find them less legible in docs, even though I use Fira Code for all my programming.

I suggest to leave ligatures enabled only in rendered declarations:

- I've only encountered the arrow ligature there so far, and it is easy to understand. By contrast, free-form code blocks use a much more diverse set of symbols, which could have surprising or confusing ligatures.
- Readers are not as likely to type in declarations, as they are to try to write code based on code blocks. So, clarity in code blocks is much more important.
- The author of the code block might not be using programming ligatures, and might not even be aware that they exist. We surprise the author by rendering code blocks in a noticeably different way from what may have been intended.

We'll have to look into whether the right ligatures can be enabled/disabled using CSS, or we have to use a separate font face (likely from the same family).

Alternatively, we could abandon ligatures everywhere.

**Comment by hcarty** [comment]
As nifty as they look, I'd prefer abandoning them everywhere.  They obscure the actual syntax being presented.

**Comment by nilsbecker** [comment]
good! i just commented about the same thing as i had trouble reading the `containers` docs with the ligatures.
