### ISSUE TITLE
Fix the esy build in Travis

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#257]
I moved it to `allowed_failures` for now due to lack of time for debugging it.

**Comment by ostera** [comment]
It looks like the Travis builds on macOS and Linux are working alright now. We're still missing a Windows build.

**Comment by aantron** [comment]
Thanks for the ping, closing this.

**Comment by aantron** [comment]
(I had moved the builds back out of `allow_failures` in 92bcb66b946211a7f25d3f49566003684bfca16c).
