### ISSUE TITLE
Variand and record field docs are styled differently

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#260]
Variands:

![variant](https://user-images.githubusercontent.com/12073668/49143688-306f2380-f2c1-11e8-8a6b-dc9f2ad393d7.PNG)

Record fields:

![record](https://user-images.githubusercontent.com/12073668/49143696-32d17d80-f2c1-11e8-9b25-8873da25ad6f.PNG)

**Comment by trefis** [comment]
Also mildly related: #82 .
I think it'd be a huge improvement in terms of readability if #82 was implemented.
