### ISSUE TITLE
`with` fragments use the wrong module as their base

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#28]
The link for `t` in `module M : S with type t = ...` links to `M.t` when it should probably link to `S.t` instead.

For example, in http://docs.mirage.io/asetmap/Asetmap/Set/index.html the `elt` link tries to go to `Make.elt` (which doesn't exist due to #13) whereas it should link to `S.elt`.

**Comment by trefis** [comment]
I think I disagree.

If you have, e.g.
```ocaml
module M : sig
  type t
  val compare : t -> t -> int
end with type t = ...
```
Then `t` only exists in `M`, not anywhere else.

Notice that we have exactly the same use `with type ...` [here](http://docs.mirage.io/odoc/ocaml/Set/index.html) as in #13 and it works fine.
The problem in #13 does imply some broken links, but I do think the links are correct, it's just that we're failing to generate some pages.

**Comment by dbuenzli** [comment]
The particular example you mention seems to be fixed. Can we find another case where this is still problematic ? If not we should close this.

**Comment by jonludlam** [comment]
Looks to be fixed, reopen if that's incorrect.
