### ISSUE TITLE
Cross-references do not follow the disambiguation method of ocamldoc

### ISSUE THREAD

**Issue by Mishio595** [ocaml/odoc#283]
Cross-reference syntax in question: http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sss%3Acrossref

The issue is that I have a `type foo` and a `val foo` in the same module `Bar`, which causes the standard syntax for cross-references `{!Bar.foo}` to be ambiguous. Following the ocamldoc rules, I then did `{!val:Bar.foo}` and it continued to generate a link to the type.

**Comment by aantron** [comment]
This may have been fixed in `master`. If you are using 1.3.0 or another release, could you try again after doing `opam pin add odoc --dev-repo`?

**Comment by Mishio595** [comment]
It does appear to be fixed on `master`. Thanks!
