### ISSUE TITLE
Add option to fail on warnings

### ISSUE THREAD

**Issue by Gbury** [ocaml/odoc#284]
Is there a way to make odoc fail on warnings ? Ideally, that would be useful in CI scripts to make sure doc builds without errors or warnings.

**Comment by aantron** [comment]
Not at the moment. We should add this.

**Comment by aantron** [comment]
Even odoc's own development would benefit. We currently have CI emitting warnings on odoc's own comments, which have gone unnoticed for a while: https://travis-ci.org/ocaml/odoc/jobs/503418122#L1798.

(Aside: those docs are being built unintentionally, but we should probably build them in a separate test).

**Comment by aantron** [comment]
We should also expose this through Dune somehow (cc @emillon).

**Comment by emillon** [comment]
Yes, that'll need to be opt in for now, either through a `(documentation)` parameter or a flag in `dune-project`, but if it works well that could become default around dune 3 ;)
