### ISSUE TITLE
odoc pages have no TOC

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#294]
It would be nice to have some following the same rules as the `.mli` file. 

Btw. I'm not very fond of calling the preamble to the table of contents `Topics` in the rendering, that's not a topic index, it's really a table of contents. I think `Contents` would be a better name (that's what wikipedia uses and what documentation preparation systems like `LaTeX` generate for you).

**Comment by rizo** [comment]
@dbuenzli I'm currently working on this. I was waiting for https://github.com/ocaml/odoc/pull/261 to be merged (looks like you already did merge it, thanks) before submitting a PR.

Regarding "Topics": I thought about it and the reasoning is that I wanted to omit paragraph and subparagraph headings (like "Examples" or "Notes") in the listing, in which case it wouldn't be a _complete_ "table of contents". Normally the different section headings represent library topics, in my opinion. On the other hand, "Contents" is a more general term that would imply that the module symbols would also be included, and that's not the case.

I don't feel strongly about this and would be happy to rename "Topics" to "Contents".

**Comment by dbuenzli** [comment]
> in which case it wouldn't be a _complete_ "table of contents".

I don't see the problem with this, when you make table of contents in documents and books you don't necessarily include all sub-headings levels . 

> Normally the different section headings represent library topics, in my opinion.

Frankly it feels a bit a weird I dont' really understand what a "library topic" is. It's even weirder in pages where you could have an `Introduction` and a `Conclusion`.

> On the other hand, "Contents" is a more general term that would imply that the module symbols would also be included, and that's not the case.

Not really, I would expect this to be found under *indexes*. I think `Contents` is a better term here that follows established document production.

**Comment by rizo** [comment]
"Contents" it is then :)

> Not really, I would expect this to be found under _indexes_.

Just to clarify: do you mean the global index as the one generated by ocamldoc ([example](https://caml.inria.fr/pub/docs/manual-ocaml/libref/index.html))?

**Comment by dbuenzli** [comment]
> Just to clarify: do you mean the global index as the one generated by ocamldoc ([example](https://caml.inria.fr/pub/docs/manual-ocaml/libref/index.html))?

Yes these indexes. Issue https://github.com/ocaml/odoc/issues/52 tracks this.

**Comment by trefis** [comment]
@rizo any news? Do you still have your code lying around somewhere? How close is it from being finished? :)

**Comment by rizo** [comment]
@trefis See linked PR :)

(Apologies for the delay. Unfortunately I have been struggling to find time to work on odoc lately.)

**Comment by dbuenzli** [comment]
Tried it on a larger manual of mine, works great. Thanks @rizo.

**Comment by dbuenzli** [comment]
However did you maybe introduce https://github.com/ocaml/odoc/issues/365 when you did so ? I suspect you didn't see this since the example `.mld` file in the PR has a single para per section.
