### ISSUE TITLE
Record field and variant case rendering breaks cut and paste

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#296]
Please don't do this. Either do it like `ocamldoc` did by putting the field doc string in a regular ocaml comment or find a markup strategy that allows to select only the type definition. 

For reference: 

* The [ocamldoc way](https://erratique.ch/software/vg/doc/Vg.P.html#TYPEoutline)
*  The current odoc way [odoc way](https://b0-system.github.io/odig/doc/vg/Vg/P/index.html#type-outline). 
* An [odoc variant](https://b0-system.github.io/odig/doc/uuidm/Uuidm/index.html#type-version) doc that suffers from the same problem.

**Comment by rizo** [comment]
> Either do it like `ocamldoc` did by putting the field doc string in a regular ocaml comment or find a markup strategy that allows to select only the type definition.

Maybe both?

**Comment by dbuenzli** [comment]
> Maybe both?

I mean if you manage to select only the type definition you could decently argue that the comment delimiters are going to look like noise since you can distinguish them via typography.

**Comment by rizo** [comment]
Looking into it. Seems like disabling selection on comments is quite easy and would work (I don't that's a good idea though), but changing the direction to select vertically in a table is not.

Might be better to just add delimiters.

**Comment by dbuenzli** [comment]
> Looking into it. Seems like disabling selection on comments is quite easy and would work (I don't that's a good idea though), but changing the direction to select vertically in a table is not.

To be honest I don't have a strong opinion on that. But OTOH when you cut and paste say a `value` signature you don't get the doc string with it.

**Comment by trefis** [comment]
> but changing the direction to select vertically in a table is not.

IIRC the plan is to stop using a table for these anyway.

**Comment by dbuenzli** [comment]
Reopening. #615 didn't fix that in the end.

**Comment by dbuenzli** [comment]
But #626 did. Thanks @Drup. 

Currently the c&p when comments are oneliners is not that great because of the `p`, but that should improve if the scheme in https://github.com/ocaml/odoc/issues/614 is implemented.
