### ISSUE TITLE
The `{!modules}` directive should splice in the module synopsis

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#297]
These [kind](https://b0-system.github.io/odig/doc/containers/index.html) of lists are a bit bland and not very user friendly. Having the module synopsis next to the name would be nice.

Also it would be nice to classify the generated `ul` a bit along the way so that it can be easily styled.

**Comment by rizo** [comment]
> it would be nice to classify the generated `ul`

What would be an appropriate class for the `ul`? Would `class="modules"` be ok?

**Comment by dbuenzli** [comment]
That's what they used to be yes.

**Comment by rizo** [comment]
> Having the module synopsis next to the name would be nice.

Do you have a preference on the markup for this? I looked at the output from ocamldoc and it seems to generate a table.

**Comment by dbuenzli** [comment]
Tables are nice to align things if you know how long these things will be. Since in general we don't know how long module identifiers are going to be I'd rather not do this other wise you may get
```
M                      M's synopsis
M_with_a_very_long_id  That synopsis
```
which is difficult to scan. 

A good workaround which I once found in a typographic book is to align as follows:
```
                    M  M's synopsis
M_with_a_very_long_id That synopsis
```
but it doesn't look good or natural in all context. Personally I'm fine with:
```
M M's synopsis
M_with_a_very_long_id  That synopsis
```
so there's no need for tables. However it's always good to properly classify with `span`s. `span`ing the synopsis with a `synopsis` class won't hurt.

**Comment by dbuenzli** [comment]
Also adding an anchor would be nice.

**Comment by greedy** [comment]
Wouldn't definition lists like
```
<dl>
  <dt>M</dt>
  <dd>M's synopsis</dd>
  ...
</dl>
```
be appropriate for this?

**Comment by gasche** [comment]
ocamldoc generates a list of each module with its synopsis (formatted as a table). As mentioned in the Discuss thread [How to get pleasant documentation for a library using Dune](https://discuss.ocaml.org/t/how-to-get-pleasant-documentation-for-a-library-using-dune/7121), this feature `{modules: ...}` is very useful for front pages... with the ocamldoc rendering. Could we get the module synopsis(es?) with odoc as well?

**Comment by Julow** [comment]
I've implemented this using description lists: https://github.com/ocaml/odoc/pull/597
