### ISSUE TITLE
Odoc fails to compile with OCaml 4.08

### ISSUE THREAD

**Issue by jonludlam** [ocaml/odoc#304]
The constructors of `Types.signature_item` have been extended with a `visibility` flag introduced in ocaml/ocaml#2147. On first glance it looks like we should just filter out items that are `Hidden`, but I'd like to double check that.

**Comment by trefis** [comment]
> On first glance it looks like we should just filter out items that are `Hidden`

That sounds right to me.

**Comment by jonludlam** [comment]
Additionally another new field has been added to `Sig_module` in ocaml/ocaml#1610 - again, first glance, looks like we can just ignore the `module_presence` field.

**Comment by jonludlam** [comment]
And in the same PR, `Path.Pdot(x,y,z)` became `Path.Pdot(x,y)`.

**Comment by jonludlam** [comment]
And ocaml/ocaml#2122 introduced `Tsig_typesubst` and `Tsig_modsubst` to `Typedtree.signature_item_desc`. This looks a little more interesting - @trefis do you think this will require more substantial changes to odoc?

**Comment by trefis** [comment]
> again, first glance, looks like we can just ignore the `module_presence` field.

That seems correct.

> And in the same PR, `Path.Pdot(x,y,z)` became `Path.Pdot(x,y)`.

The part that disappeared is an `int`, indicating a position in the module block, which odoc doesn't care about. The two remaining fields are the only ones we were looking at anyway.

> And [ocaml/ocaml#2122](https://github.com/ocaml/ocaml/pull/2122) introduced `Tsig_typesubst` and `Tsig_modsubst` to `Typedtree.signature_item_desc`.

These ones are more interesting indeed and we'll want to support them.
There's some choice to be made regarding what to do with them
1. apply the substitution and make them disappear from the generated doc
2. do not apply the substitution, just print them as is in the generated doc
3. same as (2) and additionnaly update the code for `<module type> with type/module ... := ...` to replace the type/module declaration by the `:=` one in the signature.

(2) seems like the easiest to do right now, and a decent choice overall.
As for how to handle them: I think you should be able to treat them as normal types / modules (w.r.t resolving and expansion) and just print them a bit differently (that is: with the `:=`).

**Comment by jonludlam** [comment]
The `visibility` changes is a bit painful, because it changes the number of params in every constructor in `signature_item`, so doing the `#if` preprocessor directives inline in the match cases is becoming unreadable. It might be time to do a migrate-parsetree style redeclaration of some small parts of the typedtree/types definitions, and have per-compiler-version translation to these in one place only.
