### ISSUE TITLE
Running odoc against OCaml 4.08 beta1 raises assertion failure when processing asmcomp/CSE.ml

### ISSUE THREAD

**Issue by jonludlam** [ocaml/odoc#311]
See https://github.com/ocaml/odoc/issues/288#issuecomment-465302208 for backtrace.

The problem appears to be that we're calling `Ctype.object_fields` with something with this type:

```
{id=1391;level=100000000;desc=
 Tsubst
  {id=-57;level=100000000;desc=
   Tobject(
    {id=-58;level=100000000;desc=
     Tfield(class_of_operation,Fpresent,
      {id=-70;level=100000000;desc=
       Tpoly(
        {id=-71;level=100000000;desc=
         Tarrow("",
          {id=-73;level=100000000;desc=Tconstr(Mach.operation,[],[])},
          {id=-72;level=100000000;desc=Tconstr(CSEgen.op_class,[],[])},Cok)},
        [])},
     {id=-59;level=100000000;desc=
      Tfield(is_cheap_operation,Fpresent,
       {id=-66;level=100000000;desc=
        Tpoly(
         {id=-67;level=100000000;desc=
          Tarrow("",
           {id=-69;level=100000000;desc=Tconstr(Mach.operation,[],[])},
           {id=-68;level=100000000;desc=Tconstr(bool,[],[])},Cok)},[])},
      {id=-60;level=100000000;desc=
       Tfield(fundecl,Fpresent,
        {id=-62;level=100000000;desc=
         Tpoly(
          {id=-63;level=100000000;desc=
           Tarrow("",
            {id=-65;level=100000000;desc=Tconstr(Mach.fundecl,[],[])},
            {id=-64;level=100000000;desc=Tconstr(Mach.fundecl,[],[])},Cok)},
          [])},{id=-61;level=100000000;desc=Tvar None})})})},ref None)}}
```

It seems `Ctypes.object_fields` only handles `Tobject`:

```
let object_fields ty =
  match (repr ty).desc with
    Tobject (fields, _) -> fields
  | _                   -> assert false
```

I don't know whether this is a problem in odoc or in ocaml.

**Comment by lpw25** [comment]
At first glance this looks more likely to be an OCaml bug than an odoc one. There really shouldn't be any `Tsubst` nodes left lying around and I don't think odoc calls any of the functions that (temporarily) create them.

**Comment by trefis** [comment]
It's worth noting that this happens only when processing the `.cmt`, not on the `.cmi` (which I find reassuring).

**Comment by trefis** [comment]
Alright, I think I've found what's causing this.
I'll submit a PR against the compiler.

**Comment by jonludlam** [comment]
I'll close this issue then. Thanks!

**Comment by trefis** [comment]
https://github.com/ocaml/ocaml/pull/2261

**Comment by dbuenzli** [comment]
Happy to report that `odoc` no longer explodes in 4.08.0+beta1. A small (because a lot of dune packages explode due to the Pervasives deprecation) 4.08 docset can be spotted here: 

https://b0-system.github.io/odig/dev/

**Comment by trefis** [comment]
I assume you meant beta2?

**Comment by dbuenzli** [comment]
Yes sorry !

**Comment by aantron** [comment]
Thanks @dbuenzli, @trefis, and @jonludlam.

I'd like to release odoc in its current state. Please let me know if there are any objections.

**Comment by dbuenzli** [comment]
If @rizo has a timely fix for https://github.com/ocaml/odoc/issues/294 that's the last one I would have had liked in the release. For the rest it's good enough for me to be able to push the next release of `odig`. 

However I think @trefis fell on something related to https://github.com/ocaml/odoc/issues/276 on Js' packages that it may be good to fix before.

**Comment by trefis** [comment]
Indeed, I will try to provide a minimal example ASAP.

**Comment by trefis** [comment]
I think the issue I encountered has been here for a long long time, and I'm having a hard time understanding all of the details, so the example might take a while.

If I'm the only blocker, I think you should release without waiting for me on that one.

**Comment by jonludlam** [comment]
I have no objections to releasing now.
