### ISSUE TITLE
Discover Bisect_ppx during build and remove it from dev dependencies

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#316]
Development odoc depends on Bisect_ppx, which depends on ocaml-migrate-parsetree, which doesn't always keep up early with compiler development (we are currently having trouble with it and 4.08.0+beta1).

This complicates pinning odoc `master` for testing against upcoming compiler versions.

We need to loosen the dependency on Bisect_ppx so that it is used if available, but never required, even in `master`.

See https://github.com/ocaml/odoc/pull/314#issuecomment-465949337, https://github.com/ocaml/odoc/pull/312#issuecomment-465333593. cc @ostera, @dbuenzli.

**Comment by dbuenzli** [comment]
[Here](https://github.com/avsm/arp/commit/63826d0d95e9403f6c380b6427110a6a08c876f8) could be one way.

**Comment by aantron** [comment]
The linked commit should fix this, and I'll merge it into `master` once it passes CI. This also unblocks testing on 4.08 in Travis, which I'll add next.

**Comment by aantron** [comment]
@ostera, this should also fix the error you reported in #314, provided you have esy pull from commit 985ecfd1107935276f08d2d66e61a06bee03b290 or later.
