### ISSUE TITLE
Suppress "sig ... end" output for modules

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#323]
For modules that have a literal signature, or whose signature is inferred, odoc currently generates

```ocaml
module A : sig ... end
module B : sig ... end
module C : sig ... end
(* etc. *)
```

The `sig ... end` adds visual noise and no information, compared to not having it at all. I suggest to not generate it.

We can also suppress `object ... end` for classes.

The corresponding output in Reason syntax is `{ ... }`, and I suggest to suppress that, too.

**Comment by trefis** [comment]
I assume that you'd want to do that for module types as well.
At which point there is no visual difference between an abstract module type, and a module type which defines a signature.

The same remark applies to class types.

Would you suggest doing the same for includes as well?

**Comment by lpw25** [comment]
> The `sig ... end` adds visual noise and no information, compared to not having it at all

Doesn't it add the information that the module is a structure rather than a functor?

**Comment by aantron** [comment]
> I assume that you'd want to do that for module types as well.

Just modules.

> Doesn't it add the information that the module is a structure rather than a functor?

We output something like `module F : functor (Arg : ARG) -> S` (or `-> sig ... end`) for functors, and will keep that. So, there is still a distinction between structures and functors. I don't think we need to positively tell the reader that a module is a structure when it is, since that's the common case, and we will still tell the reader when a module is either not a structure, or has an ascription to a module type (i.e. not a literal signature).

**Comment by dbuenzli** [comment]
> Just modules.

I think you'd rather have consistency here. 

In general I prefer to see module pages as a pretty-printed/literate mlis. Following the module link somehow expands the  `...`. Also at a certain point there was the possibility of having annotations to allow to directly splice in a module sig inline rather than jump to a new page, if that becomes a reality the `sig end` would need to re-appear leading again in an inconsistent design.

That said you could devise a markup that allows to decide this through styling, but as far as I'm concerned I don't think I'd like to see the `sig ... end` go.

**Comment by aantron** [comment]
> pretty-printed/literate mlis

If the `.mli` has

```ocaml
module Foo =
sig
  type t = int
end
```

and we drop `type t = int` when "pretty-printing" it, why not drop the `sig` and `end`, too?

Also, how is the result *pretty*?

> Also at a certain point there was the possibility of having annotations to allow to directly splice in a module sig inline rather than jump to a new page, if that becomes a reality the `sig end` would need to re-appear leading again in an inconsistent design.

This is exactly where the `sig` and `end` would be useful, and when I explicitly would want to reintroduce them into the output. Rather than consistency about displaying `:` with a constraint, I'm more concerned about consistency in conveying useful and salient information with the characters that are in the output. 

`sig ... end` doesn't positively convey much, because it says "this module is a structure that is documented elsewhere." Structures is already the common case, and the reader knows it's documented elsewhere because of the link.

It is deviations from this that are interesting, such as functors, where we would want to explicitly print `: functor ...`, and inlined signatures, where we would want to explicitly print `: sig (* actual docs *) end`.

<br/>

The `sig ... end` is especially annoying in Dune index modules:

```ocaml
module A = A
module B = B
(* etc. *)
```

becomes

```ocaml
module A : sig ... end
module B : sig ... end
(* etc. *)
```

which is ugly even with comments in between.

This is also a bit of a counterexample to *pretty-printing* `.mli` files, since this will be a common example where we generate docs from (ultimately) an `.ml` file.

**Comment by dbuenzli** [comment]
> and we drop `type t = int` when "pretty-printing" it, why not drop the `sig` and `end`, too?

We don't drop it, we *elide* it with `...` and puts it's content on another page. 

> Also, how is the result _pretty_?

Let's not get bogged into taste discussions. This can perfectly be solved at the styling level if the markup is improved.

**Comment by lpw25** [comment]
I don't really mind either way, but I just thought I would throw in:

```ocaml
module A : ...
```
to the list of possibilities as somewhere between the two options being discussed.
