### ISSUE TITLE
Abbreviations dictionary

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#325]
This is about detecting all-caps abbreviations that appear in comment text, such as "STDERR" and "I/O," and surrounding them with `<abbr>` during output, so they can be styled to be less of an eyesore. I typically use small caps for them.

**Comment by dbuenzli** [comment]
These kind of automated conversions always end up bitting at some point. I think if you  really want to be able to tag some text as `abbr` simply extend the ocamldoc language to support this markup.

**Comment by dbuenzli** [comment]
I would move on to close this.
