### ISSUE TITLE
Anchoring module structure items

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#326]
Anchors in module structure items allowed, in the old markup to highlight a definition and it's docstring if desired since those were wrapped in a single `div`. 

This is no longer the case. I don't think using definition lists was a very smart move since we can no longer group a structure item in a single block element. 

Besides using definition lists doesn't really bring any semantics markup-wise since you have to break them in case there is literate content in the mli. 

The old way of treating the .mli as a literate document with markup elements (paragraphs, lists, header) interleaved with definitions (packed in their own `div`) was much more convenient.

**Comment by dbuenzli** [comment]
For reference contrast for example: 

https://docs.mirage.io/alcotest/Alcotest/index.html#val-equal
https://b0-system.github.io/odig/doc/alcotest/Alcotest/index.html#val-equal

https://docs.mirage.io/alcotest/Alcotest/index.html#type-speed_level
https://b0-system.github.io/odig/doc/alcotest/Alcotest/index.html#type-speed_level

**Comment by aantron** [comment]
Emitting definition lists is correct for an interpretation where a doc comment explains multiple interrelated items:

```ocaml
type t
type u
(** Two related types that are always used together. *)

type something_else
```

In this case, it would be wrong to highlight the comment as belonging to `u`, but not `t`. It also makes it easier to style the space between `t` and `u` with CSS, though that can also be done by abusing the absence of a docstring, provided it is wrapped correctly in the output.

> Anchors in module structure items allowed, in the old markup to highlight a definition and it's docstring if desired since those were wrapped in a single `div`.

This is nice, but not necessary, nor common, and sometimes undesirable (if using the style above). For example, Sphinx output doesn't do this: http://docs.libuv.org/en/v1.x/async.html#c.uv_async_t.

> Besides using definition lists doesn't really bring any semantics markup-wise since you have to break them in case there is literate content in the mli.

How does breaking up definition lists make them less semantic?

They are serving their direct semantic purpose in the markup right now. It's also suggestive to look at the current odoc output unstyled. Even the default styling of definition lists suggests that they are an appropriate choice.

> The old way of treating the .mli as a literate document with markup elements (paragraphs, lists, header) interleaved with definitions (packed in their own `div`) was much more convenient.

In what way do definition lists in the *output* of odoc amount to not treating an `.mli` as a literate document?

Concerning the output, we still emit paragraphs, lists, headers, and definitions. Standalone paragraphs, lists, headers are wrapped in `<header>`s or `<aside>`s, and definitions are wrapped in `<dl>`s (rather than `<div>`s). How does changing the wrapping structure of definitions, and (presumably) promoting `<aside>` content to the top level (if that is what you are suggesting), related to treating the `.mli` as a literate document or not, or is more semantic?

> was much more convenient.

For which specific purposes? Are there more besides being able to apply an anchor to a declaration and its immediate docstring?

**Comment by trefis** [comment]
> Emitting definition lists is correct for an interpretation where a doc comment explains multiple interrelated items:
> 
> ```ocaml
> type t
> type u
> (** Two related types that are always used together. *)
> 
> type something_else
> ```
> In this case, it would be wrong to highlight the comment as belonging to `u`, but not `t`.

Well actually, it wouldn't.
The compiler will have attached the comment to `u`, which IMO settles that question.

Also, do you differentiate between the example you gave and the following:
```ocaml
type t

type u
(** Two related types that are always used together. *)
 
type something_else
```
?

**Comment by aantron** [comment]
> Well actually, it wouldn't.
> The compiler will have attached the comment to `u`, which IMO settles that question.

This settles the question for the compiler, not odoc. We're all aware of what the compiler does here, and what the parser *has* to do for practical reasons. This isn't about the technical procedures of the compiler, but about how the tools can be used nonetheless. That a docstring has to (practically) be attached to at most one element doesn't mean we have to enforce this restriction rigidly throughout the whole system.

> Also, do you differentiate between the example you gave and the following:

No. In this usage, if the author wants `t` not to become "grouped" with `u`, the author should document `t` independently. So, in practice, this works well with complete documentation only.

**Comment by aantron** [comment]
(An intervening standalone comment also works)

**Comment by dbuenzli** [comment]
> In this case, it would be wrong to highlight the comment as belonging to `u`, but not `t`.

AFAIK that's not the semantics of ocamldoc attachements. In your example the doc string is for `u` not for `t`.

> This is nice, but not necessary, nor common, and sometimes undesirable (if using the style above). For example, Sphinx output doesn't do this: http://docs.libuv.org/en/v1.x/async.html#c.uv_async_t.

I don't see what's undesirable and I don't really care if other system don't have a good UX or don't do this... With the old scheme you could *choose* in the styling whether to highlight only the ocaml code or the ocaml code and the doc string. The reason why I prefer to highlight both is that in most discussions online when I hyperlink in the documentation my aim is to usually link to the definition and it's explanation which is exactly what the old design allowed.

> How does breaking up definition lists make them less semantic?

To be honest, I don't really believe in the whole semantics thing and apply it as much as possible but without being religious about, in practice seperation of content and styling remains a pipe's dream. In any case in my semantic view of things I would expect to have a single definition list for the whole module.

> In what way do definition lists in the _output_ of odoc amount to not treating an `.mli` as a literate document?

That's not exactly what I said. But in any case I dont think it's useful to interleave lists of definitions with the rest of the markup, the definitions can be at the same level (especially since sometimes you get lists with a single element), each in their own as a single block.

> Concerning the output, we still emit paragraphs, lists, headers, and definitions. Standalone paragraphs, lists, headers are wrapped in `<header>`s or `<aside>`s, and definitions are wrapped in `<dl>`s (rather than `<div>`s). How does changing the wrapping structure of definitions, and (presumably) promoting `<aside>` content to the top level (if that is what you are suggesting), related to treating the `.mli` as a literate document or not, or is more semantic?

It's not about semantics, it's about easiness of styling. Your markup design suffers from `div`itis and makes some styling harder or impossible to perform. 

E.g. if you want to do something to spacing only when a code fence is followed by a heading, with the simple markup we had before this is a simple `pre + h1` CSS selector. Here I simply cannot do anything because you wrapped everything in `articles`, `headers` and what not which make little semantics sense anyways, at most the whole `mli` would be an article to me.

Here's an example of a pre followed by a header, contrast the markup: 

https://b0-system.github.io/odig/doc/cmdliner/Cmdliner/index.html#excp
https://docs.mirage.io/cmdliner/Cmdliner/index.html#examples
 
> For which specific purposes? Are there more besides being able to apply an anchor to a declaration and its immediate docstring?

It's not only about the anchors it's about the whole markup.

**Comment by aantron** [comment]
> It's not only about the anchors it's about the whole markup as just explained.

That's why I'm asking, because I already agree with removing the `<section>`s and such, since the time I first wrote that. It was an experiment that was very easy to do (and undo), which I just did as a side effect of generating the TOC. I'm opening a separate issue for that.

**Comment by lpw25** [comment]
> We're all aware of what the compiler does here, and what the parser _has_ to do for practical reasons. This isn't about the technical procedures of the compiler, but about how the tools can be used nonetheless.

To be clear, the parser doesn't attach comments in this way for technical reasons. It attaches comments in this way because it is the intended and documented semantics of ocamldoc comments. If you want to document multiple things with a comment then the comment should not be an attached comment but a free-standing comment.

**Comment by aantron** [comment]
> E.g. if you want to do something to spacing only when a code fence is followed by a heading, with the simple markup we had before this is a simple `pre + h1` CSS selector

The example you linked actually has been a CSS problem for me. In the old markup, a `pre` that was in a standalone comment would be emitted at the top level (unwrapped), whereas a `pre` that was part of a doc comment would be emitted in a `div`. So, I could not style them consistently. So, there was still no consistent way to select headings that follow code blocks.

I also wanted to be able to select groups of related elements, that were part of one comment in the `.mli`, but the old markup does not allow that at all.

**Comment by dbuenzli** [comment]
> So, there was still no consistent way to select headings that follow code blocks.

That's true but the current markup nesting makes that even worse. Please keep the markup as flat as possible.

> I also wanted to be able to select groups of related elements, that were part of one comment in the `.mli`, but the old markup does not allow that at all.

I'm not sure exactly what you mean by that but the notion of "comment" doesn't really make sense in the ocamldoc language see again the discussion [here](https://github.com/ocaml/odoc/issues/235#issuecomment-440100450).

**Comment by aantron** [comment]
> If you want to document multiple things with a comment then the comment should not be an attached comment but a free-standing comment.

In that case, it seems to be another reason not to put the elements of unattached comments ungrouped at the top level, as it makes it difficult to style comments meant for a group of signature items the same way as comments attached to one signature item, due to the different nesting levels and semantic structure.

> I'm not sure exactly what you mean by that but the notion of "comment" doesn't really make sense in the ocamldoc language see again the discussion [here](https://github.com/ocaml/odoc/issues/235#issuecomment-440100450).

Yes. I don't mean one comment, but one run of unattached comment text.

This brings up another issue.

Considering

> If you want to document multiple things with a comment then the comment should not be an attached comment but a free-standing comment.

and 

> I'm not sure exactly what you mean by that but the notion of "comment" doesn't really make sense in the ocamldoc language see again the discussion [here](https://github.com/ocaml/odoc/issues/235#issuecomment-440100450).

it seems that there is no consistent way, with the semantics of the ocamldoc language, to delimit a run of freestanding comment text as specifically documenting a particular group of related signature items.

In

```ocaml
type t
(** foo *)
```

The comment is automatically delimited as applying to `t`.

However, in both

```ocaml
(** Some unrelated text. *)

(** This comment documents t and u. *)

type t
type u
```

and

```ocaml
type t
type u

(** This comment documents t and u. *)

(** {1 A new section} *)
```

it seems that the comment that the author would want to notionally "attach" to `t` and `u` as a group gets melded into the preceding or following comment text.

I guess this forces us to treat the freestanding text as ungrouped, but, as mentioned above, that can lead to its own problems with inconsistent styling, not the least of which is that I can't easily produce the appearance of a group of elements with its own attached comment, consistent with how a single element with an attached comment looks.

**Comment by trefis** [comment]
> it seems that there is no consistent way, with the semantics of the ocamldoc language, to delimit a run of freestanding comment text as specifically documenting a particular group of related signature items.

Indeed.
And that's something we might want to fix, but I don't think the fix should be limited to odoc (or its markup), it would be beneficial to merlin as well for example.

In the meantime, I think the best approximation is to define a (sub)section.

**Comment by dbuenzli** [comment]
> In that case, it seems to be another reason not to put the elements of unattached comments ungrouped at the top level, as it makes it difficult to style comments meant for a group of signature items the same way as comments attached to one signature item, due to the different nesting levels and semantic structure.

I think you are making this more complicated than it is. Just do the obvious if you have: 

```
(** Para
 
    Para
 
    Para  *)

val ... 
(** ... *)

val ...
(** ... *)

(** Para *)

val ... 
(** .. *)

(** Para 
  
     Para 

     Heading *)
```

Simply output 
```
p 
p 
p 
<div class="value'>
<div class="value'>
p
<div class="value'>
p 
p 
h1
```

There's no need to render that more complicated than this. The mapping is obvious to the documenter and to the person who needs to process it. And if you want to style the `p` in the `div` the same way the outer `p` are styled there's aboslutely no problem.

> it seems that there is no consistent way, with the semantics of the ocamldoc language, to delimit a run of freestanding comment text as specifically documenting a particular group of related signature items.

What's wrong with simply documenting them under the same heading ? That's exactly what headings are for, you even get a toc entry for them. Let's not create problems that do not exist here.

**Comment by aantron** [comment]
> Let's not create problems that do not exist here.

I don't want a heading for a couple of small phantom types whose only purpose is to be different from each other, and to be parameters for a type constructor declared immediately afterwards. There are other such examples. I also want to be able to style the text that comes before or after them consistently with how other attached text is styled. It would also be nice if linking to them with an anchor wasn't different from linking to a "normally" documented item with an anchor.

> And that's something we might want to fix, but I don't think the fix should be limited to odoc (or its markup), it would be beneficial to merlin as well for example.

Ok, fair enough. I can work around this for my own purposes in the meantime.

**Comment by dbuenzli** [comment]
> I don't want a heading for a couple of small phantom types whose only purpose is to be different from each other, and to be parameters for a type constructor declared immediately afterwards. There are other such examples. I also want to be able to style the text that comes before or after them consistently with how other attached text is styled. It would also be nice if linking to them with an anchor wasn't different from linking to a "normally" documented item with an anchor.

To be honest I'm not sure the number of cases where you'll find this arising is worth adding more complexity to the ocamldoc language and/or rendering. Be creative within the limits.

**Comment by dbuenzli** [comment]
> Anchors in module structure items allowed, in the old markup to highlight a definition and it's docstring if desired since those were wrapped in a single `div`. This is no longer the case.

This is not fixed. The `id` and anchoring is on the `div.spec` not the wrapping `div.odoc-spec`, I don't mind it that way nowadays.

>  I don't think using definition lists was a very smart move since we can no longer group a structure item in a single block element.

This was fixed by @Drup's new rendering. Last uses of `dl` are going away in #607. Good riddance. 

> The old way of treating the .mli as a literate document with markup elements (paragraphs, lists, header) interleaved with definitions (packed in their own `div`) was much more convenient.

This became again a reality with #600.
