### ISSUE TITLE
Module preamble/header detection.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#328]
Related to https://github.com/ocaml/odoc/issues/235 

The way module preambles are detected is odd. Basically one expects to have anything that happens before the first header or structure item to go in the module preamble/header.

More precisely in the stdlib `Int64` module I would expect all of the contents of the first comment to go in the preamble. Instead, it seems *all* of it put in an `aside` element (!?):

https://github.com/ocaml/ocaml/blob/4.07/stdlib/int64.mli#L16-L28
https://b0-system.github.io/odig/doc/ocaml/Stdlib/Int64/index.html

**Comment by dbuenzli** [comment]
Also I suspect this should explain the annoying lack of module synopses in the 4.08 docset here:

https://b0-system.github.io/odig/dev/ocaml/Stdlib/index.html#modules

**Comment by dbuenzli** [comment]
This is still an issue with the new odoc. Basically the module preamble here:

https://github.com/ocaml/ocaml/blob/4.09/stdlib/int64.mli#L16-L35

Ends up in `div.odoc-content` rather than `header.odoc-preamble` (using classification terminology from #589)

**Comment by dbuenzli** [comment]
I took the liberty to add this to the 2.0.0 milestone because it basically breaks all Stdlib module preambles and as a side effect their synopsis line in the `Stdlib` module.

**Comment by Julow** [comment]
I've made a reproduction test case for this issue: https://github.com/ocaml/odoc/commit/113d00659378e2eb80ef1b39a10ff4fe337f0356
This seems to be due to the `stdlib__` wrapping of the stdlib. Generating the html for `stdlib.odocl` spits out a page for `Int64` that has the module's documentation in the wrong place. The html for `stdlib__int64.odocl` has the documentation in the preamble (but the rest of the page is empty due to it being a "hidden" module).

**Comment by dbuenzli** [comment]
Sorry but this is not fixed, still no preamble on `Stdlib` modules.

**Comment by dbuenzli** [comment]
(and hence no synopses aswell in `Stdlib`)

**Comment by dbuenzli** [comment]
Here's yet another preamble problem that I suspect is different from the `Stdlib` modules. 

The docset [here](https://erratique.ch/software/b0/doc/#io) was generated with master. The `B00_lines` module is missing the synopsis and its doc page has no `odoc-preamble`, everything is folded in `odoc-content`.

That seem to be because [there's an `open`](https://github.com/b0-system/b0/blob/d0c1f5e9b5be2f082406c74bf831f707f9813afd/src/b00/kit/b00_lines.mli#L6) in the source before the module preamble.

**Comment by dbuenzli** [comment]
> That seem to be because [there's an `open`](https://github.com/b0-system/b0/blob/d0c1f5e9b5be2f082406c74bf831f707f9813afd/src/b00/kit/b00_lines.mli#L6) in the source before the module preamble.

That is fixed. 

> Sorry but this is not fixed, still no preamble on `Stdlib` modules.

Still an issue…

**Comment by dbuenzli** [comment]
More precisely. This is fixed:

> This is still an issue with the new odoc. Basically the module preamble here:
> 
> https://github.com/ocaml/ocaml/blob/4.09/stdlib/int64.mli#L16-L35
> 
> Ends up in `div.odoc-content` rather than `header.odoc-preamble` (using classification terminology from #589)

But the modules [here](https://b0-system.github.io/odig/doc/ocaml/Stdlib/index.html#modules) still don't have synopses.

**Comment by Julow** [comment]
Odoc doesn't do this, I tested with master and 1.5.2.
I opened an other issue: https://github.com/ocaml/odoc/issues/632
