### ISSUE TITLE
Command for mapping identifiers to urls anchors

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#334]
For allowing editors to let their user browse the documentation of a given identifier in a generated documentation set it would be nice to have a command like `odoc [-I DIR]...  uri ID [KIND]`

`odoc` would resolve the identifier in the set of `odoc` files found in the `-I DIR`  options and write one or more relative url on stdout and/or exit with a well defined exit code if the identifier cannot be found.

/cc @trefis

**Comment by trefis** [comment]
Note: `ID` would actually be a path (in the sense of odoc and the ocaml typechecker).

**Comment by trefis** [comment]
And, since it's not obvious, the reason why you'd want this command instead of just guessing the url based on the path is that if your path is `Foo.Bar.t` but `Foo.Bar` is an alias for `Baz` then `Foo/Bar/index.html` won't exist, and the page you want to link to will be `Baz/index.html`.

**Comment by jonludlam** [comment]
I think `id` will be a reference rather than a path, but yes, I'm all for this!
