### ISSUE TITLE
Types in include with at toplevel are not resolved properly

### ISSUE THREAD

**Issue by greedy** [ocaml/odoc#343]
While exploring #96 I came across this confounding issue with includes at the toplevel of a module. Given the following mli:

```ocaml
module type S = sig
  type zzz
  val f : zzz -> zzz
end

include S with type zzz = int

module type Z = S with type zzz = int list

module Foo : sig
  include S with type zzz = string
end
```

The mention of `zzz` in `include S with type zzz = int` does not get resolved properly but the include within `Foo` and the reference in defining `module type Z` are resolved properly. This is seen in the HTML where the top-level include is rendered as `include S with type S.zzz = int` (which is invalid code to boot) with `S` being linked to the documentation for the module type and `zzz` not linked.

The trouble seems to begin around `module_type_expr_with_id` calling `resolve_type_fragment` and it ends up that the top-level reference invokes the unresolved case.

I've traced things further different cases and got as far as `resolved_module_type_path` in component_table.ml where the include at the top level is considered local but the rest are considered non-local. The non-local cases seems to trigger loading of the signature items for the module interface but the local one does not. I don't really have any idea what to do with this information or what a proper fix would be though.

**Comment by jonludlam** [comment]
Should be fixed with the new model.
