### ISSUE TITLE
How to document reexports?

### ISSUE THREAD

**Issue by emillon** [ocaml/odoc#347]
Hello!

Suppose I have a wrapped library with some "private" modules and a manual wrapper that reexports some types and values:

```
dune-project
dune
lib.ml
lib.ml
something.mli
something.ml
```

```
; dune
(library
  (name lib)
  (wrapped true))
```

```ocaml
(* lib.ml *)
type something = Something.t

let print_something = Something.print
```

```ocaml
(* lib.mli *)
type something

val print_something : something -> unit
```

```ocaml
(* something.mli *)
type t

val print : t -> unit
val something_else : t -> t -> unit
```

I'm not sure how to document `Something.print`: it's possible to document it in `something.mli` together with the rest of that module's API, but then it's would be missing in `lib.mli`. At the moment, my understanding is that I have no choice but to copy/paste the docstring.

Is there a way to tell odoc to reuse the doc for `Something.print` for `Lib.print_something`? Maybe an attribute like the following:

```ocaml
let[@odoc.alias] print_something = Something.print
```

I'm not familiar with odoc's internals so I don't know if this is feasible.

Let me know what you think. Thanks!

**Comment by aantron** [comment]
I'm not aware of a way to do this neatly right now. We'll have to consider adding it.

**Comment by trefis** [comment]
A few thoughts:
- we're not going to introduce `[@odoc.whatever]` attributes, we should stick to tags in docstrings, e.g. `(** @alias Foo.Bar *)`  or `(** @odoc.alias Foo.Bar *)` (where `Foo.Bar` is understood as a reference path)
- the annotation should be on the interface, not in the implementation
- you could do things differently:
  ```ocaml
  (* lib.mli *)
  include Something.Exported (** @inline *)

  (* something.mli *)
  module Exported : sig
    type t
    val print : t -> unit
  end

  include Exported
  val something_else : t -> t -> unit
  ```
  I believe that would copy the docstrings from inside something.mli to the page for lib.

**Comment by hannesm** [comment]
@trefis I tried your `include Something.Exported (** @inline *)` approach, this didn't work for me (using odoc 1.4.0) -- it changed the output to not contain `include YY` and a triangle to show/hide, but instead showed all included values and types directly.

**Comment by trefis** [comment]
That is the point. But the docstrings should also be there. If they aren't, then something's wrong indeed.

**Comment by avsm** [comment]
Reopening this as it never really got solved. There's a feature request for it over at Tezos as well: https://gitlab.com/tezos/tezos/-/issues/1076

(cc @jonludlam)
