### ISSUE TITLE
Variant extensions not recognized as specs

### ISSUE THREAD

**Issue by vphantom** [ocaml/odoc#348]
I think this one might be for `odoc`, though please keep in mind that I'm using `dune build @doc` as a front-end.  With odoc v1.4.0 and dune v1.8.2, given the following input in an `.mli` file:

```ocaml
(** Extend storage key with a user ID variant. *)
type Storage.key += UserID of Id.t
```

The output doesn't get styled like other definitions:

```html
<dl>
  <dt>
    <code>…</code>
  </dt>
  <dd>
    <p>…</p>
  </dd>
</dl>
```

I would've expected this `<dt>` to have CSS class `spec` (if not also `type`).  Note that extensible variants were introduced in OCaml 4.02; so maybe some parser in the chain doesn't recognize `+=` here?

**Comment by aantron** [comment]
Indeed, this is a bug in the HTML generator. The above commit adds the `spec` and `extension` classes to this `<dt>`. Thanks for reporting!
