### ISSUE TITLE
`-I $DIR` option needs $DIR to exist

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#35]
Currently the `-I $DIR` option requires $DIR to exist. I'm not sure this is a good idea. Any reason why this is the case ?

**Comment by lpw25** [comment]
In general I think it is good for tools to sanity check their input, to detect things like typos early and give good error messages. Is there any particular reason that this shouldn't apply in this case?

**Comment by dbuenzli** [comment]
I don't know, but generally tools with include and other `PATH` do not check this. In this particular case it inhibited me to have a very simple manual sequence of invocations

```
odoc compile -I p -o p/m1.odoc m1.cmti
odoc compile -I p -o p/m2.odoc m2.cmti
```
(`-o` will create `p`)

But feel free to close this if you think that's a good idea.

**Comment by lpw25** [comment]
If other similar tools (i.e. compilers) don't check their `-I` then that would be a fair reason for not sanity checking them. I think I don't mind either way.
