### ISSUE TITLE
support ocaml 4.08 features

### ISSUE THREAD

**Issue by avsm** [ocaml/odoc#350]
Opening this as a followup to #304 and #310 which added basic OCaml 4.08 compat, but didn't support the new features.

From @trefis, `Tsig_typesubst` and `Tsig_modsubst` occurrences will result in unresolved references, so we need testcases that exercise the new features and support for resolving them.

(Note that as of #304, OCaml 4.08 can be used with odoc for resolving existing code that doesn't use the new 4.08 features).

**Comment by trefis** [comment]
It would be nice to get minimal support for these.
Our internal build of the doc at janestreet started failing with `"Assert_failure ident_env.cppo.ml:274:24"` when encountering `module Foo := Bar`.
