### ISSUE TITLE
"not an interface" uncaught exceptions

### ISSUE THREAD

**Issue by dteoh** [ocaml/odoc#356]
I am trying to use odoc (through bsdoc). The version of bsdoc that is installed is "6.0.2-alpha".

I'm getting a lot of internal errors, in many files, when I run "bsdoc build":

```
odoc: internal error, uncaught exception:
      Failure("File \"./lib/bs/src/SK_Logger.cmti\":\nnot an interface")
      Raised at file "pervasives.ml", line 32, characters 17-33
      Called from file "cmdliner_term.ml", line 25, characters 19-24
      Called from file "cmdliner.ml", line 116, characters 32-39
```

For reference, the contents of the associated `.rei` file:

```
type t;

let logger: t;

let nullLogger: t;

let info: (t, string) => unit;

let info2: (t, string, Js.t('a)) => unit;
```

What am I supposed to do to get this working?

**Comment by dbuenzli** [comment]
I suspect a version mismatch between the OCaml compiler that compiled `odoc` and the one that compiled `SK_Logger.cmti`. Both must match.

**Comment by rizo** [comment]
(CC @ostera)

**Comment by dteoh** [comment]
> I suspect a version mismatch between the OCaml compiler that compiled odoc and the one that compiled SK_Logger.cmti. Both must match.

Ok, yeah, I'm guessing this will not support bs-platform 5 or OCaml 4.02 projects.

I tried hacking bsdoc to use OCaml 4.2.3007 (and make other deps resolve), but no luck in the build phase.

**Comment by dbuenzli** [comment]
This looks rather an issue with `bsdoc` so I'm closing this. Feel free to continue the discussion if you think something is wrong with `odoc`.

**Comment by dteoh** [comment]
> Feel free to continue the discussion if you think something is wrong with odoc.

Coming from bs-platform, I'm not well versed in how the OCaml ecosystem works, so maybe this is all very obvious to everyone else, but maybe the README or something similar can explain the requirements to use this tool (library?).

Things that might be useful to answer:

* is odoc a command line tool? a library that requires a front-end wrapper like bsdoc?
* is everyone supposed to compile their own odoc for their ocaml installation?
* is there a prebuilt odoc for each ocaml version?
* supported versions of ocaml?

**Comment by ostera** [comment]
@dteoh, bsdoc owner here.

> is odoc a command line tool? a library that requires a front-end wrapper like bsdoc?

odoc can be driven by a user, but it has a few moving parts and in the past its been driven by other tools such as `odig` or `dune`.

bsdoc is a driver for it.

> is everyone supposed to compile their own odoc for their ocaml installation?

Yes. When you install odoc using opam (or esy), you are effectively compiling it with the version of the ocaml compiler that you're using for your project.

> supported versions of ocaml?

4.02 and forward.

----

I invite you to [create an issue on bsdoc](https://github.com/ostera/bsdoc/issues/new) and we can continue discussing there. I haven't yet put time to publish a version compatible with bs-platform@5.x.x but it should be doable :)
