### ISSUE TITLE
Module-level documentation comment ignored in Reason

### ISSUE THREAD

**Issue by Lupus** [ocaml/odoc#363]
I can't make odoc (via `dune build @doc-private`) generate module-level documentation for .rei file.

There is some issue with comment parsing in reason as reported in [reason/2419](https://github.com/facebook/reason/issues/2419), but even with workaround applied (which should produce seemingly correct documentation attachment point in AST) I can't see my documentation in the generated html.

Reason prints module doc into ocaml as follows:

```ocaml
[@@@ocaml.doc " this is module comment "]

type t[@@ocaml.doc " this is comment, associated with type t "]
```

I've tried generating documentation from this .mli and module level doc gets ignored as well. Probably the module level doc is attached to AST in a wrong way by Reason, or odoc ignores it. 

dune version: 1.10.0
esy version: 0.5.6
refmt version: Reason 3.3.7 @ 43efc14
odoc version: 1.4.0

**Comment by lpw25** [comment]
I think that needs to be `[@@@ocaml.text " ... "]`. Stand-alone comments should be `text` rather than `doc`.

**Comment by Lupus** [comment]
`ocamlc -dparsetree` agrees with that statement :) I believe this odoc issue can be closed, as there's nothing to fix in odoc per se. For others trying to generate module level doc in Reason, I've published some small workaround in [this comment](https://github.com/facebook/reason/issues/2419#issuecomment-500104433) of the corresponding Reason issue on invalid ast printing for stand-alone comments.
