### ISSUE TITLE
Test failures on 4.08.0 (release)

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#367]
Can be seen in the [Travis log](https://travis-ci.org/ocaml/odoc/jobs/546199354#L1774), for example:

```diff
-     <a href="#type-gadt" class="anchor"></a><code><span class="keyword">type</span> _ gadt</code><code> = </code>
+     <a href="#type-gadt" class="anchor"></a><code><span class="keyword">type</span> <span>_ gadt</span></code><code> = 
```

This looks related to the recent spanning PRs, and happens only on 4.08. @trefis, can you take a look?

**Comment by trefis** [comment]
Will do.

**Comment by aantron** [comment]
The new output is likely correct, and was promoted by @dbuenzli in #378.
