### ISSUE TITLE
Display types as abstract

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#371]
I have some docs with

```ocaml
type t = some_ugly_type
```

but I'd like them to show just `type t`.

Perhaps we can add either a doc tag or an annotation for this?

```ocaml
type t = some_ugly_type
  [@@odoc abstract]
```

or

```ocaml
type t = some_ugly_type
(** @abstract *)
```

**Comment by ostera** [comment]
Do we have this information in the parse/typedtree? It'd be cool if the types that _are_ abstract were automatically hidden.

**Comment by dbuenzli** [comment]
@ostera they are. I'm a little bit dubious about this feature request I don't think you should hide the equation of types if they do exist.

**Comment by Octachron** [comment]
I feel that this is an anti-feature, the fact that a type is abstract or not change the nature of the module API.  Contrarily, eliding the type abbreviation sounds fine.

**Comment by dbuenzli** [comment]
> Contrarily, eliding the type abbreviation sounds fine.

And what if I *really* want to know what it's in the abbreviation, I need to go and hunt the `.mli` or my toplevel ? That really feels like an annoying feature.

**Comment by Octachron** [comment]
Sorry, I meant eliding in the main documentation with a link to follow to get the full expanded abbreviation. Keeping some information only available in the mli would indeed be utterly annoying.

**Comment by aantron** [comment]
In my case, the type definition is internal, and I'd prefer not to complicate the implementation to present a concrete type to other modules in my library, and an abstract type to the user.

> Keeping some information only available in the mli would indeed be utterly annoying.

This is at the control of the documentation author, though.  We already have `(**/**)` for hiding parts of the `.mli` from documentation.

**Comment by Octachron** [comment]
Except that the type abbreviation can leak. For instance, someone can apply a function to the not-abstract type that by accident matches the true type. Then the user might get a type error that is unrelated to any type that she can see and she would have to guess that the documentation lied to her to event start to debug the error.

**Comment by dbuenzli** [comment]
I still think the potential of misuse by authors for this makes it not such a great idea, notably for the reasons @Octachron mentions. Also `(**/**)` is really to hide things you don't want to be used so I'd say it's different since your case the type ends up being used in the API.

**Comment by aantron** [comment]
I'm aware that it can leak. Technically, module items in `(**/**)` can leak too, though it's probably not nearly as annoying. The items in `(**/**)` may allow a module to surprisingly match a signature that it should not match.

**Comment by aantron** [comment]
I accept the arguments.

**Comment by trefis** [comment]
https://github.com/ocaml/odoc/wiki/Model-design#abstracting-aliases-containing-hidden-paths
