### ISSUE TITLE
Should nested comment+code_block be accepted ?

### ISSUE THREAD

**Issue by hhugo** [ocaml/odoc#375]
```ocaml
(**
  This is a comment with code inside
  {[
    (** This is a comment with code inside
        {[ let code inside = f inside ]}
    *)
    let code inside = f inside
  ]}
*)
```

**Comment by aantron** [comment]
To clarify, the problem is the nested `]}` that is inside the nested `(** ... *)`.

What is the natural scenario in which this kind of input arises?

**Comment by hhugo** [comment]
This came up while writing tests for ocamlformat.
I don't know if there is a natural scenario for this.
If we don't plan to support it, it would be good to document the restriction.

**Comment by aantron** [comment]
I'm inclined not to support it, unless we find someone is really using this.

**Comment by dbuenzli** [comment]
I think we should try, not doing so would prevent the ability of extracting (see https://github.com/ocaml/odoc/pull/303) any OCaml source file.
