### ISSUE TITLE
Allow to supply .md files in addition to .mld files

### ISSUE THREAD

**Issue by ulrikstrid** [ocaml/odoc#377]
It would be nice to be able to write .md files in addition to .mld files as they can also be looked at in GitHub.
This issue is separate from the issue about making odoc parse markdown everywhere.

**Comment by dbuenzli** [comment]
You can have a look at @mseri's [md2mld](https://github.com/mseri/md2mld) project if you really want this (I would still suggest you don't do this, if you want to write good manuals the markdown language is terrible and largely inferior to the ocamldoc language and its checked cross linking capabilities into your API). 

Supporting this would also likely add more dependencies to the project while it should rather try to cut on these. Besides the project is moving at a glacial pace with many problems unresolved, I think it's better if we polish and focus on the problems of its core feature which to support the `ocamldoc` language.

So I'm closing this. If other members of the project disagree feel free to reopen.

**Comment by ulrikstrid** [comment]
@dbuenzli I just want it for "guides" and things that are not code heavy so I don't think it matter much that it's a "inferior" format. `md2mld` might be fine but I still think this would be a great feature to have.

**Comment by dbuenzli** [comment]
I don't think there's any point in solving this in `odoc` if external tools like `md2mld` can do it -- priorities and lean systems.
