### ISSUE TITLE
Inconsistent markup for module preambles.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#38]
The markup generated for module preambles is different for 1) toplevel modules (compilation units) and 2) submodules: 

1. 
```
<header>
  <h1>module Mod</h1>
</header>
<p>preamble</p>
<p>preamble</p>
...
```
2. 
```
<header>
  <h1>module Mod.Sub</h1>
</header>
<div class="mod">
  <div class="def"><code>module Mod.Sub : sig ... end</code></div> 
  <div class="doc"><p>preamble</p>...</div>
</div>
```

This should be discussed and a unifying scheme should be found which should take into account functors and the rendering of their arguments.

**Comment by trefis** [comment]
I agree with what you set in #22 i.e. that we should probably just drop the `module Mod.Sub : ...` repetition in the submodule.
In ocamldoc it links to a plain signature of the module, I'm not sure how useful that is.

What do you have to say about for functors and functor arguments?

**Comment by dbuenzli** [comment]
> What do you have to say about for functors and functor arguments?

In functors the "repetition" has clickable elements that regular modules do not have.

Also I'm not sure about these "parameters" and "signature" section for functors is because there is actually a way to associate doc strings to each argument ? If not I'd simply drop that. 

(see e.g. http://docs.mirage.io/asetmap/Asetmap/Map/Make/index.html)

**Comment by lpw25** [comment]
Note that the "parameters" will shortly be the only place that the parameters appear on the page since the copy of the submodule's definition at the top of the page is being removed. I also hope to add support for giving them documentation (probably using the `@param` tag which is already supported for functions).

**Comment by dbuenzli** [comment]
> the copy of the submodule's definition at the top of the page is being removed.

Note that this still has more information than the "parameters" and "signature" sections namely the type equations.

**Comment by trefis** [comment]
> Note that this still has more information than the "parameters" and "signature" sections namely the type equations.

Fair point, I will try to include that in the parameters section.
As for the signature, there should be no need as the equations/substitutions should be reflected in the displayed signature.
N.B. unless I'm missing something, they aren't at the moment, but will be after the rewrite of the expansion phase that @lpw25 is planning to do in the "near" future.

**Comment by dbuenzli** [comment]
> Fair point, I will try to include that in the parameters section.

I wonder if we should not simply move what was removed minus the `sig : ... end` to the `h1` and remove these `parameters` and `signature` headers. It seems to me that the best way to describe functor parameters is like we do for functions (i.e. without `@param` but by writing an application and describing the result of the application).

**Comment by dbuenzli** [comment]
The original issue is fixed in the new markup. I'll open a new issue about functor rendering which I still find a bit weird.
