### ISSUE TITLE
Cannot reference to infix operator, e.g OUnit2.(>::), in .mld files

### ISSUE THREAD

**Issue by gildor478** [ocaml/odoc#384]
I get an error, if I use the following piece of code in a .mld file:
```
{1 Foobar}
{!Test.(>::)}
```

The error is:
File "index.mld", line 1, characters 2-10:
Unknown reference qualifier 'Test.(>:'.

Not only does it strip half of the identifier, it also doesn't link '>::'. Using the same code in a .ml file, I got no errors. Doing the same thing with ocamldoc works.

Here is an archive where you can see the problem:
[test-odoc.tar.gz](https://github.com/ocaml/odoc/files/3616521/test-odoc.tar.gz)

Just extract the archive and run "make odoc" to see the problem.

**Comment by trefis** [comment]
Yep, that doesn't surprise me.
I believe it's due to [this line](https://github.com/ocaml/odoc/blob/master/src/parser/reference.ml#L324).

We should have a proper parser.
