### ISSUE TITLE
Release 1.4.2 (4.09 support) tomorrow (19 September 2019)

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#386]
Looks like OCaml 4.09 is about to be released (https://github.com/ocaml/opam-repository/pull/14842). odoc 1.4.1 doesn't support it, so we need to release odoc 1.4.2, which has #383.

I'm ready to do the release. If anyone has any objection, please comment.

**Comment by pmetzger** [comment]
I have the inverse of an objection, which is a strong encouragement.

**Comment by aantron** [comment]
https://github.com/ocaml/opam-repository/pull/14848

**Comment by avsm** [comment]
Thanks!
