### ISSUE TITLE
0-level comments inside mli files cut off generated html

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#387]
I'm not sure how prevalent this is, but at least in ldap, the mli file has a 0-level comment mid-way. When generating the odoc for this package, everything after and including that comment is cut off from the final products, including sub-modules that aren't generated. odig waits for these artifacts to be produced and fails. No warning is generated by odoc, either.

Steps to reproduce:

* Install ldap with opam.
* Run `odig odoc`

**Comment by dbuenzli** [comment]
Turning the 0 into a 1 and generate a warning is likely what should be done.

**Comment by Julow** [comment]
This is solved. The heading is converted to a h1 and the warning looks like that:
```
File "test.mli", line 4, characters 4-23:
Warning: '{0': heading level should be lower than top heading level '0'.
```
