### ISSUE TITLE
Get defintion formatting from the MLI

### ISSUE THREAD

**Issue by smondet** [ocaml/odoc#390]
Related to https://github.com/ocaml/odoc/issues/19 .

Right now the formatting of large OCaml definitions is quite unreadable: one line + wrapping without indentation.

It would be nice to have the option to just get the formatting of `val`, `type`, etc. definitions directly from the `.mli` itself (i.e. just add colors, keep it `<pre>..</pre>`).
Smaller-width outputs can be handled with horizontal scroll bars if that's a concern.

**Comment by dbuenzli** [comment]
On the web you have to cope with multiple viewport size in a graceful manner and horizontal scroll bars are terrible from a usability point of view. So this is really not a good solution. 

@trefis recently made things better according to [these lines](https://github.com/ocaml/odoc/issues/19#issuecomment-470128041). Maybe that's not supported by your stylesheet though. Feel free to point to particular examples so that we can have a look. 

But I'd say the specific wish here is not a good solution so I'm closing this.

**Comment by smondet** [comment]
Using odoc 1.4.2, and all the defaults (from `dune`), I get this:

https://tezos.gitlab.io/-/flextesa/-/jobs/316458794/artifacts/testweb/api/flextesa/Flextesa/Interactive_test/Pauser/index.html#val-run_test

unusable with *any* viewport size I've tried.

instead of (`ocamlformat` with `profile=compact`):

```ocaml
  val run_test :
       < application_name: string
       ; console: Console.t
       ; paths: Paths.t
       ; pauser: t
       ; runner: Running_processes.State.t
       ; test_interactivity: Interactivity.t
       ; .. >
    -> (unit -> (unit, ([> System_error.t] as 'errors)) Asynchronous_result.t)
    -> pp_error:(Format.formatter -> 'errors -> unit)
    -> unit
    -> (unit, [> System_error.t | `Die of int]) Asynchronous_result.t
```

The [mli displayed by gitlab](https://gitlab.com/tezos/flextesa/blob/0f9694175849782a55a8d58e3d2c2a6726fa4093/src/lib/interactive_test.mli#L219) still looks much better on my old phone.

**Comment by dbuenzli** [comment]
It seems `odoc`'s default stylesheet is missing something like [this](https://github.com/b0-system/odig/blob/master/themes/odoc.css#L201-L203) which leads to much more natural breakpoints. Maybe try with one of `odig`'s provided stylesheets.

**Comment by dbuenzli** [comment]
@smondet just to make things clear the markup certainly needs more work but I think we have that covered by other issues. It's just that getting the formatting as is from the `.mli` is not a great solution (what if the formatting in the `cmi` is bad ?) and doesn't really fit with the publication medium.

**Comment by smondet** [comment]
Definitely better with an odig CSS, still not as good as Gitlab's horizontal-scrollbar code:

![screenshot-20191010-144527](https://user-images.githubusercontent.com/617111/66597321-b9efb300-eb6c-11e9-9bef-93ce628ac19b.png)
(https://tezos.gitlab.io/-/flextesa/-/jobs/317779694/artifacts/testweb/api/flextesa/Flextesa/Interactive_test/Pauser/index.html#val-run_test)

is that closing parenthesis all the way to right a bug? (if yes, in odig or odoc?)

> It's just that getting the formatting as is from the .mli is not a great solution (what if the formatting in the cmi is bad ?) 

That's why I proposed the idea as an option. If the user uses the option, then formatting the MLI properly becomes their problem :)

**Comment by dbuenzli** [comment]
> That's why I proposed the idea as an option. If the user uses the option, then formatting the MLI properly becomes their problem :)

Except the user of the system is in general not the one who controls the mli. I have no respect for systems that push problems onto users that they can't solve ;-)

There's quite a bit that can be done to improve the markup and rendering of signatures but again, taking the formatting of the mli is not part of the solution.
