### ISSUE TITLE
compilation error when installing odoc

### ISSUE THREAD

**Issue by thedufer** [ocaml/odoc#392]
I get a compilation error when trying to install odoc via opam:

```
#=== ERROR while compiling odoc.1.4.2 =========================================#
# context     2.0.5 | linux/x86_64 | base-bigarray.base base-threads.base base-unix.base ocaml-base-compiler.4.07.0 | https://opam.ocaml.org/#7f655b2f
# path        ~/.opam/4.07.0/.opam-switch/build/odoc.1.4.2
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build -p odoc -j 4
# exit-code   1
# env-file    ~/.opam/log/odoc-10046-d2c37b.env
# output-file ~/.opam/log/odoc-10046-d2c37b.out
### output ###
#       ocamlc src/html/.odoc_html.objs/byte/odoc_html__Tree.{cmi,cmti} (exit 2)
# (cd _build/default && /home/thedufer/.opam/4.07.0/bin/ocamlc.opt -w -40 -w -18 -g -bin-annot -I src/html/.odoc_html.objs/byte -I /home/thedufer/.opam/4.07.0/lib/bytes -I /home/thedufer/.opam/4.07.0/lib/ocaml/compiler-libs -I /home/thedufer/.opam/4.07.0/lib/re -I /home/thedufer/.opam/4.07.0/lib/result -I /home/thedufer/.opam/4.07.0/lib/seq -I /home/thedufer/.opam/4.07.0/lib/tyxml -I /home/thed[...]
# File "src/html/tree.mli", line 1:
# Error: The files /home/thedufer/.opam/4.07.0/lib/tyxml/tyxml_html.cmi
#        and /home/thedufer/.opam/4.07.0/lib/tyxml/html_types.cmi
#        make inconsistent assumptions over interface Html_types
```

The error only references tyxml, but that package installed just fine so it seems like an odoc issue?  I don't really understand what's going on here.

**Comment by dbuenzli** [comment]
The inconsistency seems rather to be in the `tyxml` package itself. Maybe try an `opam reinstall tyxml`, that may help.

**Comment by thedufer** [comment]
No luck with a reinstall.  Should I take this to the tyxml project?  I started here because tyxml seemed to install fine, but maybe this doesn't show up until you try to link it into an executable or something like that?

**Comment by trefis** [comment]
> Should I take this to the tyxml project? I started here because tyxml seemed to install fine, but maybe this doesn't show up until you try to link it into an executable or something like that?

Yes that all sounds right. I think you should open an issue there.

**Comment by thedufer** [comment]
Done.  Thanks!
