### ISSUE TITLE
`odoc compile` exits with 0 on errors

### ISSUE THREAD

**Issue by emillon** [ocaml/odoc#394]
Hi,

When passed an invalid .mld file such as `{2`, `odoc compile` displays errors but does not exit with an error code. This also happens with a comment in a .mli file.

In turns, this causes `dune build @doc` to succeed.

Could odoc fail in such a case?

Thanks!

**Comment by aantron** [comment]
This is probably because all messages are warnings in odoc, and odoc recovers from them. We could consider add a strict mode (#284).

**Comment by emillon** [comment]
That would be perfect for my use case, and it could be exposed in dune as well.

**Comment by aantron** [comment]
Great, I'm closing this in favor of #284.
