### ISSUE TITLE
use monospace font in code snippets in html output

### ISSUE THREAD

**Issue by c-cube** [ocaml/odoc#397]
it's pretty strange not to see code properly aligned in `{[ … ]}` snippets :)

edit: see for example [this doc page](https://c-cube.github.io/printbox/0.3/printbox/PrintBox/index.html)

**Comment by aantron** [comment]
Which font are you seeing being used? I have Fira Mono and the alignment looks fine.

I suspect the mention of `pre` and `code` should be removed from `odoc.css` line 14.

**Comment by c-cube** [comment]
Hum, seems to have disappeared (I think I didn't get fira mono initially? Maybe because it's hosted on google which I typically block.)
