### ISSUE TITLE
Comments inside docstrings

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#399]
It might be useful to provide some syntax to add comments (i.e. things that will be omitted from the generated html) inside docstrings.

This might not seem very useful in "normal" files, where you could end your docstring, put a regular comment, then start your docstring again (even though I expect there will be some attachment issues when doing that). But there is currently no way to place a comment inside `.mld` files. Which seems more problematic.

**Comment by dbuenzli** [comment]
What happens at the moment if you put a [stop comment](https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sec360) inside a comment ?

**Comment by trefis** [comment]
I just tried putting one in a `.mld` file, and it was (unsurprisingly) printed as is.

**Comment by dbuenzli** [comment]
I was rather thinking: what does `ocamldoc` say.

**Comment by trefis** [comment]
Ah, :speak_no_evil:
