### ISSUE TITLE
CSS handling story

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#4]
Current CSS handling is sub-optimal, a link to a CSS file called `odoc.css` located above `--output-dir` is generated in the HTML. 

Here's a suggested approach:
1. By default the link to the CSS file should be `odoc.css` in the `--output-dir`. A default CSS file located in `etc` should be copied over in the `--output-dir`. [These instructions](http://erratique.ch/software/topkg/doc/Topkg.html#config_store) show how `topkg` can be used to work with an `etc` directory both in release and development mode.
2. A `--css-uri URI` option should be added to override the default CSS link (`odoc.css`) generated in the HTML.
3. A `--css-file FILE` option should be added to be able to specify the contents of the `odoc.css` file in `--output-dir`
4. A `--no-css-file` option should be added to specify that no CSS file should be copied over to `--output-dir`.

**Comment by trefis** [comment]
Just to make I understand, point 1 says that the default is to link to an `odoc.css` but leave it to the user to ensure that this file is present (e.g. through his build system), correct?

**Comment by dbuenzli** [comment]
No point 1. copies an `odoc.css` located in the `etc` dir. You'd need to use `--no-css-file` or provide one with `--css-file` if you don't want that file to be used.

**Comment by trefis** [comment]
Ah, right. Got it.

**Comment by dbuenzli** [comment]
N.B. 1. is similar to what `ocamldoc` does by default, it's useful when you want to quickly generate a doc set for a project.

**Comment by lpw25** [comment]
I think that 2 makes sense as part of the `link` command, but the others aren't quite right. We don't want to copy over a css file every time we `link` something. I think the best way to handle this is to add a `css` command or similar, which copies the default file or a specified file to the appropriate location.

**Comment by dbuenzli** [comment]
> We don't want to copy over a css file every time we link something.

But you only link once no ? I think that between all the file you'll generate once you do the indexing of values, copying a `css` file there will be negligible and the above has the advantage of making things simple by default.

**Comment by lpw25** [comment]
> But you only link once no ?

You link once per module (the compilation analogy breaks down a little there).

> negligible and the above has the advantage of making things simple by default

I'm not keen on compilation chains which can write the same file at different stages. It can screw up parallel build, and is generally hard to express to a build system. I'd rather that `odoc` was precise than convenient, the convenience is meant to be provided by tools like `opkg` or by build rules within a build system.

**Comment by dbuenzli** [comment]
> You link once per module (the compilation analogy breaks down a little there).

Ah yes, sorry I confused with the `ocamldoc` way. 

> I'm not keen on compilation chains which can write the same file at different stages.

Agreed. Would only have made sense if you linked once.

**Comment by trefis** [comment]
I added a `css` subcommand (with 178d5e4 ) and replaced all mentions of "link" with "html", which should make future discussions less confusing.

I will try and implement `2.` soon-ish.

**Comment by dbuenzli** [comment]
I think that once `2.` is in this can be closed.

**Comment by trefis** [comment]
I think this might have been closed by mistake when everything was moved to a single repository.
At least, I don't understand how 54791c7 fixes point 2.

**Comment by aantron** [comment]
Regarding 3 and 4, I think these can also be addressed by copying a CSS file manually, or running a command to delete the generated CSS file. Not sure if that is a burden in some environments, though. What is the use case for 2? I am imagining some centralized deployments where `odoc.css` can't just be overridden by a `cp` command, and is centrally hosted somewhere. What's an example of this?

**Comment by dbuenzli** [comment]
> Regarding 3 and 4, I think these can also be addressed by copying a CSS file manually, or running a command to delete the generated CSS file.

As I [mention](https://github.com/ocaml/odoc/issues/4#issuecomment-249439716) I think only 2. is needed; request for 3. and 4. are obsolete because css is only output during `odoc css`. But just in case:

3. Allows build procedures to not be aware of the way the `odoc` organises its files (abstraction). 

4. Running commands to delete stuff in build systems is quite annoying and again this means the build procedure needs to make assumptions about how `odoc` organises its files so this is 3. again. 

Now I think the one I really need is 2.,  2. is the way the www works ;-). It allows to refer either to a stylesheet that you maintain among many projects in a centralized way and/or link to a stylesheet somewhere else on the web.

In my particular case (`odig`'s `odoc` theming support) it allows me to specify the `odoc.css` file in a fixed particular directory which I will refer to relatively with `--css-uri` in all the compilations. This directory will hold the `odoc.css`  aswell as  all the assets (e.g. fonts etc.) mentioned from that file. Swapping themes can then simply be performed by swapping the contents of this directory.

**Comment by rizo** [comment]
I believe this is solved by https://github.com/ocaml/odoc/pull/154. @dbuenzli please let me know/reopen the issue if that's not entirely true.
