### ISSUE TITLE
Direct references to module specifications are not wrapped in a code tag

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#40]
That is when we write `{!M.x}` and `x` is the identifier of a module specification, the content of the link should be wrapped in a `code` element.

See also #37.

**Comment by trefis** [comment]
When the references are resolved, do you want
```html
<a><code>M.x</code></a>
```
or
```html
<code><a>M.x</a></code>
```
?

**Comment by dbuenzli** [comment]
> <a><code>M.x</code></a>

I think this one makes more sense.

**Comment by dbuenzli** [comment]
Don't know when it was fixed but this is fixed in `odoc` 1.4.1.
