### ISSUE TITLE
Release 1.5.0 around 25 December 2019

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#405]
The latest release, [1.4.2](https://github.com/ocaml/odoc/releases/tag/1.4.2), was three months ago. I suggest to release 1.5.0 in a week. This would include at least:

- https://github.com/ocaml/odoc/issues/391
- https://github.com/ocaml/odoc/pull/393
- `--warn-error`, #398, #400, #404.

**Comment by dbuenzli** [comment]
I think it would be nice to fix https://github.com/ocaml/odoc/issues/407 and https://github.com/ocaml/odoc/issues/388 along the way it's a bit annoying for `odig`ing switches (see original report [here](https://discuss.ocaml.org/t/odoc-and-odig-not-quite-working-for-me/4886/4)).

**Comment by jonludlam** [comment]
Thanks @dbuenzli - I've spent a few hours on one of those but didn't get to the bottom yet. I'll take another look tomorrow, but I'm reluctant to delay a release - we might as well get out the fixes we already have in master, even without those issues addressed.

**Comment by dbuenzli** [comment]
Well janestreet managed to produce their [v0.13.0 core_kernel](https://ocaml.janestreet.com/ocaml-core/latest/doc/core_kernel/index.html) documentation with `odig` so presumabely they have a patch for the problem no ? /cc @trefis

**Comment by trefis** [comment]
I didn't take care of this release, so I haven't seen this. @xclerc might know.
Also, not sure whether it matters, but I believe we generated the doc on 4.08, not 4.09.

**Comment by jonludlam** [comment]
It's possible they just provided a `mli` file for List0 - the 'trivial workaround' is to process a cmti rather than the cmt file, which is easy when it's your own source you're producing docs for :-)

**Comment by xclerc** [comment]
For what it's worth, I do not remember adding an `mli` file.

The bug is not clear to me: is a computation actually diverging,
or simply requiring a "large" stack? (I am asking because I
routinely `ulimit -s unlimited` for various tasks, so it is quite
possible the terminal used to generate the documentation
was configured this way.)

**Comment by jonludlam** [comment]
It's not the same as #388 - that's the one for which an mli would fix it. It looks to me like it's diverging, so no ulimit fix here. We should probably move this discussion to #407 in any case.

**Comment by aantron** [comment]
@jonludlam, I [added](https://github.com/ocaml/odoc/commit/238fae457e897cc2dc78eeae67d17d009defa1f1) a [build](https://travis-ci.org/ocaml/odoc/jobs/646837205) on 4.10.0+beta2 to `master` after #408, and it does pass. Is there anything left blocking a release?

**Comment by jonludlam** [comment]
Thanks @aantron - I think nothing is now blocking this, given that we've not been able to create a reliable repro of #407. I'll make a release!

**Comment by gmcninch** [comment]
> Thanks @aantron - I think nothing is now blocking this, given that we've not been able to create a reliable repro of #407. I'll make a release!

Hi @jonludlam -- I made this report

> https://discuss.ocaml.org/t/odoc-and-odig-not-quite-working-for-me/4886/4.

related to #407.

I don't see any change in that bug; I'm still unable to run "odig odoc" without seeing the reported error. Am I exceptional in this regard?

**Comment by jonludlam** [comment]
No, the bug is still definitely present - when I said we couldn't make a reliable repro I meant one that was small enough to be able to isolate the exact problem.

There is a new implementation of the internal model that odoc uses that won't have the same problem (at least, bit in the same way!) So rather than sink more time into figuring out #407 we're working hard to try and get the new model out instead.

**Comment by pmetzger** [comment]
Given that this tag exists: https://github.com/ocaml/odoc/releases/tag/1.5.0 ...
can this ticket now be closed?

**Comment by jonludlam** [comment]
Yep!

**Comment by gmcninch** [comment]
Jon Ludlam <notifications@github.com> writes:

> No, the bug is still definitely present - when I said we couldn't make a reliable repro I meant one that was small enough to be able to isolate the exact problem.
>
> There is a new implementation of the internal model that odoc uses that won't have the same problem (at least, bit in the same way!) So rather than sink more time into figuring out #407 we're working hard to try and get the new model out instead. 

Ah; I see. That makes sense; thanks!
