### ISSUE TITLE
indexlist is not supported?

### ISSUE THREAD

**Issue by c-cube** [ocaml/odoc#409]
http://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#sec357 mentions `{!indexlist}`. I'm just curious as if it's not planned to support it, or just overlooked.

**Comment by aantron** [comment]
I'm not completely sure about the decision in the internals of odoc about this (@jonludlam?). I deliberately left it out of the parser because we don't generate indexes at the moment. Perhaps we should at least parse `{!indexlist}` to warn about it.

**Comment by dbuenzli** [comment]
Note that https://github.com/ocaml/odoc/issues/52 tracks this.
