### ISSUE TITLE
Functor types aren't written correctly when empty params

### ISSUE THREAD

**Issue by giltho** [ocaml/odoc#410]
Hi ! 
This is a small thing but I have modules that have side-effect behaviours, and  a functor to instantiate them.
```ocaml
module Make () = struct ... end
```

However, odoc doesn't seem to be handling that well for some reason :
![image](https://user-images.githubusercontent.com/8451179/74752535-baa8fc00-5266-11ea-9322-39a4d4c57679.png)
It should be
```ocaml
module BasicIdentifier : functor () -> S_with_stringify with type t = int
```
Somehow the arrow disappears.
This doesn't happen if I add a dummy parameter
```ocaml
module BasicIdentifier : functor (Empty : sig end) -> S_with_stringify with type t = int
```
![image](https://user-images.githubusercontent.com/8451179/74752714-06f43c00-5267-11ea-8b8c-4487421edf93.png)

**Comment by giltho** [comment]
Unfortunately, I don't have time to understand the internals of odoc to fix this, but if someone has time and doesn't know how it works, my first instinct would be to look [here](https://github.com/ocaml/odoc/blob/master/src/html/generator.ml#L1518) where the behaviour of the `Unit` functor param is different

**Comment by jonludlam** [comment]
Maybe here: https://github.com/ocaml/odoc/blob/master/src/html/generator.ml#L1671 in contrast to here: https://github.com/ocaml/odoc/blob/master/src/html/generator.ml#L1687 - note the lack of `Syntax.Type.arrow`
