### ISSUE TITLE
Make [@@deriving bin_io] and similar produce nicer documentation

### ISSUE THREAD

**Issue by tomjridge** [ocaml/odoc#414]
The issue is that if I declare a type which derives eg bin_io, then I get lots of extra functions generated (good!) but they also pollute the documentation (bad!). I would prefer that the documentation just had: type t[@@deriving bin_io] without the extra generated functions.

**Comment by rizo** [comment]
I think this is not something that odoc could automatically detect for a particular ppx deriver. The ppx is expanded before odoc is called (at least with a typical dune project). The ppx derivers could decide to generate those functions and hide them with special ["stop comments"](https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#ss:ocamldoc-stop), but that's probably not a good idea.

The simplest solution is _not_ to use `[@@deriving bin_io]` in the interface files at all, and manually define any generated function declarations, if desired.

Does this make sense?

**Comment by tomjridge** [comment]
Yes, thanks. I understand the issue (which stage odoc runs at). I quite like the "stop comments" approach (particularly if they were preceded by a ppx-generated comment "NOTE: hidden [@@deriving bin_io] definitions for type t"). But I understand this is not really under odoc's purview.

Thanks, and closing
