### ISSUE TITLE
Miscellaneous fixes for OCaml 4.11

### ISSUE THREAD

**Issue by rwmjones** [ocaml/odoc#429]
Here are some fixes for OCaml 4.11 we are carrying in Fedora:

https://src.fedoraproject.org/rpms/ocaml-odoc/blob/master/f/odoc-1.5.0-ocaml411.patch

**Comment by rwmjones** [comment]
That patch is a bit of a hack to put it mildly, so best to treat it with caution!

**Comment by jonludlam** [comment]
I won't, no worries, it's good to know what's breaking though!

**Comment by jonludlam** [comment]
@kit-ty-kate beat me to it!
