### ISSUE TITLE
[Discussion] Functor output

### ISSUE THREAD

**Issue by Drup** [ocaml/odoc#430]
I'm unsatisfied with the state of the functor output. The current stable output is https://b0-system.github.io/odig/doc/containers/CCBijection/Make/index.html . Here is a simplified version:
```html
<h3>Parameters</h3>
<ul>
  <li>Mod1 : Sig1</li>
  <li>Mod2 : Sig2</li>
</ul>
<h3>Signature</h3>
```

The markup is highly irregular compare to other pages since it creates out-of-hierarchy headers out of thin air, and insert an `h3` title for the signature (why 3 ?). It also creates a list for some reasons.

I recently changed it to reuse the normal markup for declarations, so it gets the same goodies (anchors, styling, etc). A simplified version:

```html
<div class="spec parameter" id="argument-2-Arg2">
  module Arg1 : Sig1
</div>
...
```

This improves the list aspects, but does not improve the layout/hierarchy aspect. So:
- Where should the parameters be placed ? At the beginning, I put them in the header, but after experimentation, putting any kind of declaration in the header is just wrong
- What to do for heading/hierarchy ?
- Can we improve the documentability (for instance, pulling some documentation from somewhere) ?

**Comment by lpw25** [comment]
The markup seems bad at the moment, but I would like to keep the general notion that a module page is made up of an (optional) parameters section followed by a body section. I think that is what the headings are trying to achieve. Not sure how best to do that in the markup though.

For the documentability, we could pull the `@parameter` tags from the module's documentation, or we could try to add support upstream for putting doc comments on functor parameters. They are one of the last few places that you can name something but not document it. (Which reminds me -- we should really be printing the documentation for function parameters now that it exists).

**Comment by Drup** [comment]
What about creating a `<section>` for them in the body and have some styling make them standout ?

**Comment by lpw25** [comment]
That sounds reasonable. To be honest, I defer to you and others on how the actual markup should go.
