### ISSUE TITLE
Is highlight.js being used?

### ISSUE THREAD

**Issue by chrisnevers** [ocaml/odoc#432]
I'm currently messing around with the styling for docs, and it doesn't look like **highlight.js** is being used for syntax highlighting anywhere. Is this expected? Should this project start using the `hljs` classnames for syntax highlighting in code blocks?

I looked into adding the `hljs` classnames to the generated html through editing this [function](https://github.com/ocaml/odoc/blob/f30c9accf7e0dd4120d385f92a8e510aff1df1ba/src/document/codefmt.ml#L177-L178)
to:
```ocaml
let keyword keyword ppf =
  pf ppf "@{<hljs-keyword keyword>%s@}" keyword
```
and creating a new function for method names and other bindings:
```ocaml
let binding name ppf =
  pf ppf "@{<hljs-variable>%s@}" name
```

Additionally, I looked into adding syntax highlighting for types, and it was easy to add a class name to type variables through this [function](https://github.com/ocaml/odoc/blob/f30c9accf7e0dd4120d385f92a8e510aff1df1ba/src/document/generator.ml#L54-L55), but I'm lost when it comes to core types. How are core types represented in the generated output? Are they represented in `Lang.TypeExpr.t`? 

Lastly, just want to confirm whether `odoc` even _wants_ syntax highlighting? If not, are there any other ways I can contribute as a web developer familiar with html/css/etc.?

Thanks!

**Comment by Drup** [comment]
Hi @chrisnevers 

Thanks for looking at the rendering, it's always welcome. I'll let other people comment on hljs.

The rendering part of odoc has gone through changes in the last week, and the css and docs haven't been adapted just yet. This functions you are looking at are for use in all output of odoc, not exclusively the HTML one. You can add new tags (as you did for binding), but keep them generic (and not html-specific).

After that, you can put the HTML-specific stuff in `Odoc_html.Generator`. In this case, [here](https://github.com/ocaml/odoc/blob/f30c9accf7e0dd4120d385f92a8e510aff1df1ba/src/html/generator.ml#L47-L54).

**Comment by aantron** [comment]
To give more background, the last odoc release does use highlight.js. For example, see [these docs](https://aantron.github.io/luv/luv/index.html). So, yes, we want highlighting. As @Drup said, the output generator in `master` is currently undergoing big changes and the CSS and our usage of highlight.js are out of sync with it for the time being.

**Comment by jonludlam** [comment]
Looks like it's working to me in master.
