### ISSUE TITLE
Support signature local bindings (4.08+)

### ISSUE THREAD

**Issue by yawaramin** [ocaml/odoc#433]
Introduced in https://github.com/ocaml/ocaml/pull/2122 and shipped in OCaml 4.08+, signature local bindings are type and module bindings in signatures which are not exported as part of the signature. E.g. if I have:

```ocaml
(* foo.mli *)

type t
type u := t
```

Then the effective signature visible from other modules is just `sig type t end`.

Currently (as of odoc 1.5.0), I am seeing the `type u` binding in the odoc-generated HTML output of the module. Expected behaviour is that it should not be visible and any items which use it should be rendered as using the aliased exported type `t` only.

**Comment by lpw25** [comment]
I don't think that is the right expected behaviour. One use of local bindings is to make things easier to read, just removing them from documentation would defeat the point of that.

**Comment by yawaramin** [comment]
That's a good point. In that case I'm not sure what the expected behaviour is–is it status quo and let people figure out that e.g. `type u := t` is actually not exposed to other modules? Or should there be some more visual hints that it's private? I don't have a strong opinion either way but some folks might find the similarity to a normal binding confusing.

**Comment by CraigFe** [comment]
I've been using the current behaviour, but can think of cases where I'd want to hide such indirections from the documentation. One possible compromise might be to support the `(** @inline *)` attribute on signature local bindings. (I have no idea how feasible that would be from an implementation perspective however.)
