### ISSUE TITLE
New framework for integration tests

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#435]
odoc needs a testing framework that can run a complete invocation of the `odoc` command and check various parts of the output. We should probably add something similar to what Dune or the compiler have.

**Comment by Drup** [comment]
Don't we sort of have that ? Or do you mean that we shoudn't have to list the files to diff ?

**Comment by aantron** [comment]
I mean something more general, where we have a "sandboxed" full run of odoc (perhaps driven by Dune), and can compare `STDOUT`, `STDERR`, and/or arbitrary files from the output against expected output. By comparison, the HTML/man page setup always only runs the minimal commands needed to build an output page with mostly the same options, and we compare mostly one page.

A more general setup would allow us to test all the `odoc` subcommands, error output, etc., in a straightforward fashion.

**Comment by jonludlam** [comment]
Agreed - I like the [cram tests in dune's tree](https://github.com/ocaml/dune/tree/master/test/blackbox-tests). We could perhaps use [mdx](https://github.com/realworldocaml/mdx) which I've been using in the [next](https://github.com/jonludlam/odoc/tree/next/) branch.
