### ISSUE TITLE
odoc bug (Text_rebind) triggered by exception rebind

### ISSUE THREAD

**Issue by chetmurthy** [ocaml/odoc#436]
I'm using odoc 1.5.0 (but also checked against master: 9a9432418165fea582e189b2a94e7f282140da6a)
Ocaml: 4.10.0

I have code that rebinds exceptions, and triggers an assert failure at src/cmti.ml:291:
```
  match ext.ext_kind with
  | Text_rebind _ -> assert false
  | Text_decl(args, res) ->
```
I'll start looking at how to fix this, but thought I should report it.

**Comment by chetmurthy** [comment]
Looking at the code, it seems like a little bit of refactoring and introduction of a new type for extension-constructor-rebind will be necessary.  Is this something you're open to?

**Comment by jonludlam** [comment]
Almost certainly yes, but could you sketch out what you forsee it'll look like?

**Comment by chetmurthy** [comment]
Sure, here's some types (work in progress, please feel urged to course-correct me!)

(1) make a genericized type for extension-constructors that can be shared with exceptions. 
(2) pull out id, doc fields so they can be used without pattern-matching on the rest
(3) apply this refactoring eveyrwhere
[I -think- that the Path.Type.t is the bit I want from Text_rebind, but I haven't looked really closely ..... I'm assuming that by the time I get around to writing tests, I'll learn what precisely I need to be saving.]
```

and Extension : sig

  module Constructor : sig

    type rest_t =
      Decl of
        { args: TypeDecl.Constructor.argument;
          res: TypeExpr.t option; }
      | Rebind of Path.Type.t
    type 'a generic_t = 'a * Comment.docs * rest_t

    type t = Identifier.Extension.t generic_t

  end

  type t =
    { type_path: Path.Type.t;
      doc: Comment.docs;
      type_params: TypeDecl.param list;
      private_: bool;
      constructors: Constructor.t list; }

end = Extension

(** {3 Exception} *)
and Exception : sig

  type t = Identifier.Exception.t Extension.Constructor.generic_t

end = Exception

```

**Comment by chetmurthy** [comment]
Since I'm learning the odoc model as I do this, I'm sure I'm making tons of mistakes, too.  I suspect that the Path.Type.t above should probably be something else (for instance).

**Comment by jonludlam** [comment]
I'm a bit worried about the Path.Type.t as you say. Could you give me an example of the code that's causing the failure?

**Comment by chetmurthy** [comment]
Oh, that's easy:
```
    type t +=
      Help = Arg.Help | Bad = Arg.Bad | Finally_raised = Fun.Finally_raised |  .... etc, etc, etc ....
```
This is just an example of an extensible type.  `odoc` just doesn't support rebinding in extensible-variants (there are `assert false` in the relevant positions) and since exceptions are implemented via extensible variants, the same applies to them.

You're right, that as I explore the Path thing, it's clear that I have to add a new slot in the Env to hold constructors for lookup.  Maybe also in modules.

**Comment by chetmurthy** [comment]
Just a disclaimer: the reason I'm hacking on this is that it's blocking my ability to generate docs for my project; if you guys would rather take this over, I'm happy to back off.

**Comment by jonludlam** [comment]
Always happy to have more hands on deck :-)

Sorry, I should have been more explicit - I had got as far as rebinding in a structure item, but was getting stuck seeing whether it could be done in a signature. The failure you're pointing out is in reading the cmti, so on the surface it would seem that you can, but I couldn't immediately see a way!

**Comment by chetmurthy** [comment]
Oh wait [this is why it's good we're having this conversation!]  It's not supposed to be possible to rebind in an MLI (only in an ML); I have to run out and pickup some groceries, but after, I'll go look into this again.  Ugh: maybe I'm not seeing this right .....

**Comment by chetmurthy** [comment]
Yeah, OK, this is MY bad.  Sorry, man.  And thank you so much for your quick reply and our discussion, which saved me a -ton- of work.  A.  Ton.  Which would have been *completely* wasted.

**Comment by jonludlam** [comment]
It's a pleasure! Thanks for your interest :-)
