### ISSUE TITLE
generate links to exception definitions references in `@raise`

### ISSUE THREAD

**Issue by avsm** [ocaml/odoc#440]
This is an old feature request in ocamldoc which is still relevant to odoc.

See https://github.com/ocaml/ocaml/issues/6254

**Comment by dra27** [comment]
Specific use case in `Stream.next` in the standard library: `@raise Failure` would cross-reference to `Stream.Failure` (not `Stdlib.Failure`) and it would be nice if in that situation odoc displayed the full path as well (since `@raise Failure` can look like `@raise Stdlib.Failure` at a glance)

**Comment by dra27** [comment]
I'm not sure whether this is still an issue or not, @jonludlam?
