### ISSUE TITLE
Reference to replaced module/types

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#450]
In this example, in the doc for `Y.f`, `t` is correctly substituted in the function signature but not in the reference:

```ocaml
type t'

module type X = sig
  type t
  val f : t -> t (** {!t} *)
end

module type Y = X with type t := t'
```

An example with a module:

```ocaml
module type X = sig
  module M : sig type t end
  val f : M.t -> M.t (** {!M.t} *)
end

module M' : sig type t end

module Y : X with module M := M'
```

**Comment by Julow** [comment]
I can see that the "inline" substitutions don't have that problem:

```ocaml
module M : sig type t end

type t := M.t

val f : t -> t
(** {!t} *)
```

`type t := M.t` is shown in the output and the reference and the occurrences of `t` in `val f` are pointing to it.

What about, instead of removing destructively substituted items, replacing them with a `type t := ...` item ?
For example `Y` in the first example would be rendered like this:
```ocaml
type t := t'
val f : t -> t (** {!t} *)
```
That way, the output of `Y` looks more like `X` which may improves readability.

**Comment by CraigFe** [comment]
> What about, instead of removing destructively substituted items, replacing them with a `type t := ...` item ?

Please forgive the drive-by comment from a non-maintainer, but I'd really appreciate it if Odoc would _not_ go down this route.

- One of the big uses of destructive substitution for me is to allow highly-general module types to be specialised to simpler / more readable forms when necessary, and this would force exposing that complexity in documentation. See for instance the example presented in https://github.com/ocaml/odoc/issues/462.

- Adding fake local type substitutions creates a disconnect between the documentation and how users actually observe these types (for instance, Merlin inlines the substitution).

- I actually think local type substitutions should be inline-able in the same way as destructive subtitutions are (although likely only as an opt-in with a `(** @inline *)` annotation), as mentioned in https://github.com/ocaml/odoc/issues/433, which would result in the same problem as here.

I'd rather Odoc either (a) push substitutions into references in documentation comments or (b) simply consider destructive substitution + references to be unsupported.

**Comment by jonludlam** [comment]
I agree with @CraigFe about the `type t := ...` idea. We currently do keep track of the destructive type substitutions in the components, so it's possible to carry the substitution into the comments, but I think this is less important than some of our other issues, so I favour option (b) right now.
