### ISSUE TITLE
New model: Links to elements hidden via (**/**) are broken

### ISSUE THREAD

**Issue by jonludlam** [ocaml/odoc#456]
They should be marked as hidden and therefore not rendered as links

**Comment by dbuenzli** [comment]
If you could `class` them with say `hidden` that would be totally perfect.

**Comment by jonludlam** [comment]
My current plan is to make them unresolved, so they would render as spans with class `xref-unresolved` - would this be OK?

**Comment by dbuenzli** [comment]
I think it's better to be able to distinguish between symbols that actually do exist and those that do really not. 

It may not be an error refer to an undocumented symbol (or one that suddenly became in a package whose documentation you don't control).

**Comment by lpw25** [comment]
I would have thought that setting the `hidden` boolean to `true` in all the stuff within the stop comments was sufficient to get the right behaviour. I see that the boolean currently only exists for modules though. Is the issue just that it needs to be added to the other components as well? How is e.g. a type or value with `__` in its name handled at the moment?

**Comment by Julow** [comment]
This seems solved but the output is showing internal idents:

```ocaml
(** *)

(**/**)

type t = Foo

(**/**)

(** {!t} *)
val f : t
```

In this example, the reference to `t` doesn't resolve but the type of `f` renders like this (with an unresolved link):
```
val f : {t}1
```
