### ISSUE TITLE
Destructive substitution results in type variable name collision

### ISSUE THREAD

**Issue by CraigFe** [ocaml/odoc#462]
Using current Odoc master (`d70a0fc`), inlining of destructive type substitution can cause distinct type variables to be assigned the same name in generated documentation. For instance, in the following example:

```ocaml
module type Generic = sig
  type 'a t
  type 'a elt

  val map : ('a elt -> 'b elt) -> 'a t -> 'b t
end

module type Parametric = Generic with type 'a elt := 'a
```

the documentation of module type `Parametric` is as follows:

![image](https://user-images.githubusercontent.com/26125912/88847923-097c9980-d1e8-11ea-9787-c116ed727736.png)

where `map` gets given the wrong type (presumably due to an incorrect substitution `'b elt` → `'a`).

**Comment by jonludlam** [comment]
Thanks @CraigFe - that looks like it's going to be fun...!

**Comment by Julow** [comment]
This is fixed now.
