### ISSUE TITLE
Some odoc-generated files get mime-typed as application/xhmtl+xml rather than text/html

### ISSUE THREAD

**Issue by emengd** [ocaml/odoc#499]
Hi, I had [an issue](https://github.com/b0-system/odig/issues/60) where odig was opening certain files in the wrong browser and I realized it was because some odoc-generated files get classified as `application/xhtml+xml` rather than `text/html`.

On my system (Linux Mint 20) this (mis)classification only occurs when testing with `xdg-mime query filetype`, while `file --mime-type` will return `text/html`. So it might be a bug in `xdg-mime`. It appears to be caused by the `xlmns` attribute in the `<html>` tag (removing it fixes the issue).

I admit I don't really understand what these categories are supposed to mean, and what purpose the `xlmns` attribute has, but regardless of what is "correct" and assuming no adverse effect, I think it would make for a better user experience if `xmlns` was not included in generated files so that they are reliably classified as `text/html`. This would guarantee that `odig` or any other tool that relies on `xdg-open` (including the file explorer in particular) would open them in what the user perceive as their default browser. What do you think?

**Comment by IkkyOdufade** [comment]
Hello @Julow . My name is Iqmah, an outreachy applicant. I would like to work on this issue. Can it be assigned to me? Thank you.

**Comment by Julow** [comment]
Hi @IkkyOdufade !

If it's your first time working with OCaml, I'd suggest having a look at [Outreachy Applicants](https://github.com/ocaml/ocaml.org/issues/1245).

The code responsible for generating HTML pages is located here: https://github.com/ocaml/odoc/blob/master/src/html/tree.ml
However, the actual work is done by the `tyxml` library ([github repo](https://github.com/ocsigen/tyxml), [doc](https://ocsigen.org/tyxml/latest/manual/intro)). You'll need to dive into this library to either find the justification for the `xmlns` attribute or to find a way to remove it.

I do agree that the `xmlns` attribute is superfluous.

**Comment by dbuenzli** [comment]
> I do agree that the `xmlns` attribute is superfluous.

I don't think it is AFAIR it is mandated by the standard.
