### ISSUE TITLE
Type references can resolve to classes

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#530]
In the example below, `type-c` resolves to `` `Identifier (`Class (`Root (Common.root, Root), c)) `` but we'd expect a type.

```ocaml
class c : object
  method m : int
end
```

Currently `type-c.m` resolves but shouldn't because the type `c` would be an object type and not a class (https://github.com/ocaml/odoc/issues/525)

**Comment by lpw25** [comment]
This is the intended behaviour, or at least it was when I wrote it. The `Class` in the identifier refers to the definition that is actually in the file -- which is indeed a class. The "kinds" on identifiers and paths are actually slightly different concepts: the kind of an identifier refers to the nature of the definition that is referred to, whilst the kind of a path refers to the nature of the thing itself. For instance a type identifier refers to an actual type definition in the source, whilst a type path refers to a semantic type and may actually point to e.g. a class definition.

**Comment by lpw25** [comment]
(`type-c.m` resolving is indeed a bug though)

**Comment by Julow** [comment]
Let's leave this closed.

**Comment by panglesd** [comment]
> (`type-c.m` resolving is indeed a bug though)

This might be solved depending on how far https://github.com/ocaml/odoc/pull/933 goes
