### ISSUE TITLE
```class type``` header documentation being copied to implementation classes 

### ISSUE THREAD

**Issue by bikallem** [ocaml/odoc#535]
I am documenting the following:

```ocaml
(** Represents a generic converter. *)
class type a = object 
  method a : int -> string
end
```
```ocaml
(** Concrete string instance of a. *)
class b :string -> a 
``` 
In the generated documentation for ```class b```, the header contains both the header text for ```class type a``` and ```class b```, eg.

```
Concrete string instance of a.
Represents a generic converter.
```
Is there a way to stop inheriting the header comments? The member doc comments doesn't seem to have this issue.

**Comment by Julow** [comment]
I can't reproduce this issue, can you share more of your code ?

**Comment by bikallem** [comment]
Looks like this is fixed in the latest master. I am not able to reproduce again. Closing.
