### ISSUE TITLE
Wrong type after substitution

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#538]
In this example:

```ocaml
module type S' = sig
  type 'a t

  val map : 'a t -> ('a -> 'b) -> 'b t

  val join : 'a t t -> 'a t
end

module type S = sig
  type 'a t

  include S' with type 'a t := 'a t
end
```

The module type `S` renders like this:

```txt
type 'a t
> include S' with type 'a t := 'a t
val map : 'a t -> ('a -> 'b) -> 'a t
val join : 'a t -> 'a t
```

The types `'a t t` and `'b t` are turned into `'a t` during the compile phase (not link).
This seems to be here since a long time, I stopped bisecting when the `link` command was added.

**Comment by CraigFe** [comment]
May be related to https://github.com/ocaml/odoc/issues/462.

**Comment by Julow** [comment]
Indeed but it's worth keeping both issues open because your example may not be solved with the fix I'm implementing.
