### ISSUE TITLE
Alignment "styles" (Center, Left, Right) are not supported

### ISSUE THREAD

**Issue by daimrod** [ocaml/odoc#541]
The README.md points to https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html#s%3Aocamldoc-comments for the syntax of odoc.

However the following syntax elements supported by ocamldoc aren't supported by odoc:

```
    {C Center }
    {L Left }
    {R Right }
```

Are this styles expected to be supported in a short future or should the README be updated with a notice?

**Comment by Drup** [comment]
Eh, I wasn't even aware that was a thing.

It should be very easy to add. I'm tempted to tag that as a junior task :)

**Comment by daimrod** [comment]
Then I might have a go at it :)

**Comment by lubegasimon** [comment]
@daimrod, do you have any use case for this feature?

**Comment by daimrod** [comment]
No.  I simply encountered the case when I was browsing the documentation
of ocamldoc.

I started to work on it but didn't take time to make progress in the
last 2 months.

So, if you're thinking about making this a wontfix I won't be terribly
sad.  It was mostly a pretext to work on ocaml and odoc in particular :)

**Comment by lubegasimon** [comment]
Ah, thanks for your feedback!

**Comment by jonludlam** [comment]
The parser now parses these and emits a warning that we'll ignore them.
