### ISSUE TITLE
Local opens in class type declarations cause an assertion failure

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#543]
I think that the following mli will cause odoc to hit an assertion failure in `Cmti.read_class_signature`:

```ocaml
class type ct =
  let open Float in
  object
    method x : t
  end
```

(I've based this on a larger reproduction case, but haven't actually checked the smaller version. Let me know if it doesn't fail and I'll try to make a small case again).

**Comment by Julow** [comment]
This example does reproduce the issue. It seems to be not implemented, I'll investigate.
