### ISSUE TITLE
Long module types and types need better line breaks

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#565]
The line wrapping for long types and module types makes them very hard to read.  Even types that aren't that large (e.g. [here](http://hub2.cl.cam.ac.uk/packages/base/v0_14_0/Base/Array/index.html#val-binary_search) and [here](http://hub2.cl.cam.ac.uk/packages/base/v0_14_0/Base/Array/index.html#val-fold_until)) are much harder to parse in the docs than they are in their sources.

**Comment by Julow** [comment]
This is fixed with https://github.com/ocaml/odoc/pull/782, which works for every type expressions:

```ocaml
val binary_search : 
  ?pos:int ->
  ?len:int ->
  'a t ->
  compare:( 'a -> 'key -> int ) ->
  [ `Last_strictly_less_than
  | `Last_less_than_or_equal_to
  | `Last_equal_to
  | `First_equal_to
  | `First_greater_than_or_equal_to
  | `First_strictly_greater_than ] ->
  'key ->
  int option

type ('a, 'key) f =
  ?pos:int ->
  ?len:int ->
  'a t ->
  compare:( 'a -> 'key -> int ) ->
  [ `Last_strictly_less_than
  | `Last_less_than_or_equal_to
  | `Last_equal_to
  | `First_equal_to
  | `First_greater_than_or_equal_to
  | `First_strictly_greater_than ] ->
  'key ->
  int option

type u =
  < foo : [ `foo | `bar | `baz ]
  ; bar : [ `foo | `bar | `baz ]
  ; baz : [ `foo | `bar | `baz ] >
```

The next step is to improve the rendering in the HTML backend of type declarations with comments in them: https://github.com/ocaml/odoc/issues/614, https://github.com/ocaml/odoc/pull/673
