### ISSUE TITLE
Allow reordering of content or sections in some way

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [ocaml/odoc#581]
When documenting a `.ml` file with no associated `.mli` file (for whatever reason), there may be semantic restrictions on the ordering of items in the file; and that ordering may differ from the *conceptual* ordering, i.e. the order that you'd like readers browsing the documentation to see them.

(This may be somewhat low-priority of an Issue, as in some cases one may be able to work around the problem by adding an `.mli`, even if it's redundant and only necessary for the documentation purposes ...)

**Comment by lubegasimon** [comment]
> as in some cases one may be able to work around the problem by adding an .mli, even if it's redundant and only necessary for the documentation purposes ..

Sounds better

**Comment by ELLIOTTCABLE** [comment]
> > as in some cases one may be able to work around the problem by adding an .mli, even if it's redundant and only necessary for the documentation purposes ..
> 
> Sounds better

That's not always possible. Again, perhaps an edge-case, or perhaps out-of-scope for what odoc wishes to cover; but not always "better."

**Comment by Drup** [comment]
I'm curious how you imagine your reodering of content to be specified that doesn't end up being more or less an `.mli`

Anyway, I propose we close.

**Comment by lpw25** [comment]
For values you can work around these issues by redefining the value:
```ocaml
let foo x = ...

let bar y = ... foo ...

(** Documentation for foo *)
let foo = foo
```
For modules and types you can do the same but you will need to give the original definition a different name -- preferably one with a `_` at the start or a `__` in the middle so that all the OCaml tools know to try to hide that name.

Other than that, I think it's probably better to write an mli file. If you intend the file to have a well-documented interface then you should write down that interface explicitly.

**Comment by Octachron** [comment]
@ELLIOTTCABLE , writing an interface file should always be possible. What is this edge case that you are evoking?

**Comment by ELLIOTTCABLE** [comment]
Apologies for the slow replies; I haven't had a lot of time for FOSS stuff!

I don't think this is crucial; if it seems like a waste of time to everyone but me, feel free to close it. (=

@lpw25, that's a really, really helpful tip; it's almost certainly exactly what I would want out of this Issue *anyway*!

My particular edge-case from when I submitted this was related to fairly complicated generative-code stuff; producing *multiple* files, in different formats, at build-time would have added immense complexity (I don't have that project handy right this second, but I'll try and come back to drop a link when I have a moment <3)

**Comment by dbuenzli** [comment]
> I'm curious how you imagine your reodering of content to be specified that doesn't end up being more or less an `.mli`

I think this comment by @drup is spot on. Since everyone seems to be in agreement I'm closing this.
