### ISSUE TITLE
Images in documentation

### ISSUE THREAD

**Issue by shonfeder** [ocaml/odoc#582]
Including images (for diagrams, or terminal sessions, or illustrations) is very useful for effective documentation. I imagine there is already some mechanism for adding images to documentation, but I can't find any mention of it in the [document](https://caml.inria.fr/pub/docs/manual-ocaml/ocamldoc.html) or in issues here.

If there is already a mechanism for representing images, and I get some pointers on it, I'd be happy to make a PR into the docs to codify it there. Otherwise, if there's isn't currently a mechanism for this, I guess this is a feature request :)

**Comment by dbuenzli** [comment]
See https://github.com/ocaml/odoc/issues/59

**Comment by shonfeder** [comment]
Oh, that will do! And the link to issue should be enough to point future searches in the right direction. Thanks :)
