### ISSUE TITLE
Generate docs for predefined identifiers

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#60]
`doc-ock` has all the documentation for OCaml's predefined identifiers (e.g. `int`, `Not_found`) carefully transcribed into it, and can provide a module description for them. So we should have an `odoc predefined` command that outputs the same format as `odoc compile` but for the predefined module. We should also make predefined identifiers link to this module.

**Comment by dbuenzli** [comment]
> So we should have an odoc predefined command that outputs the same format as odoc compile but for the predefined module.

Wouldn't it be possible to bundle this as a `cmti` file installed by the compiler so that it hooks directly in the current infrastructure ?

**Comment by lpw25** [comment]
Not easily. It was hard enough typing out all the documentation by hand, building a module representation with accurate type info seems like a PITA.
