### ISSUE TITLE
open and references

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#62]
There is nothing to do to correctly handle `open`s for paths, as paths have been expanded (from longidents) by the compiler.
However references in doc strings haven't been expanded. It would be nice if odoc could remember opens when fed a `.cmt[i]` file so that it would try to resolve references with the opened modules in scope as well.

N.B. There is an example of at least one occurence of this in ocamlary.

**Comment by Julow** [comment]
This issue is not fixed. A new issue have been opened: https://github.com/ocaml/odoc/issues/594
