### ISSUE TITLE
Unintentional escape characters in odoc output (html)

### ISSUE THREAD

**Issue by jordwalke** [ocaml/odoc#620]
In this odoc output for [Unix](https://b0-system.github.io/odig/doc/ocaml/Unix/index.html), look at the function `val link`.
Here's what it looks like:
```
val link : ?⁠follow:bool -> string -> string -> unit
```
but copy and paste it into your clipboard, and assign it into a string in JavaScript, and look at the character position where `f` in "follow" _should_ be.

```javascript
var text = "val link : ?⁠follow:bool -> string -> string -> unit"
alert(text.charCodeAt(12));
```

It prints the char code `8288`. This means there's some non printable char codes which make copy/pasting items from the page into utop or a file frustratingly fail to compile (you'll get errors about weird characters but can't see with your eyes where they are until you inspect byte by byte).

I'm assuming there was some reason why these were in there? Does anyone know the back story there?

**Comment by dbuenzli** [comment]
> I'm assuming there was some reason why these were in there?

That's U+2060, it was a [failed attempt](https://github.com/ocaml/odoc/issues/19#issuecomment-307637452) at controlling breaking behaviour. It seems they were never removed in the end. They should be.

**Comment by jordwalke** [comment]
Cool. I also found some other ones in there.  (160 - non breaking space)

**Comment by dbuenzli** [comment]
> (160 - non breaking space)

But are these problematic for c&p ? I tested the other day and they were not on my side. 

I was actually planning to add more, since `inline-block`ing `span`s which made a very good job unfortunately has [usability issues](https://github.com/ocaml/odoc/issues/125#issuecomment-504468736).

**Comment by jordwalke** [comment]
Yes, in my case they were (but it was parsing the ocaml signature programmatically - perhaps there's something in the way I'm using the ocaml parser?). Do you expect ocaml to accept non-breaking spaces in ocaml files (non comment regions at least).

**Comment by dbuenzli** [comment]
The challenge is to have reasonably readable and responsive signatures while not breaking cut and paste.

I don't know exactly why you are parsing OCaml out of these HTML files which are aimed at *presentation*. But if you are doing this it shouldn't be too hard to filter out the nbsp characters outside from character literals before feeding them to the OCaml parser.

> Do you expect ocaml to accept non-breaking spaces in ocaml files (non comment regions at least).

No.

**Comment by jordwalke** [comment]
I agree it's reasonable to require anyone using the html output as a kind of input to another system to strip the characters (which is what I did and it's not hard) but copy/pasting is the more important use case.
