### ISSUE TITLE
Missing space between emphasis and code.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#64]
In https://github.com/ocaml-doc/doc-ock/commit/01327d2dc464af3f02a5a39a2d6530923a217c60 I added a sample to the ocamlary which marksup as: 

```html
<p>Here is some <em>emphasis</em><code class="code">followed by code</code>.</p>
```
It should be:
```html
<p>Here is some <em>emphasis</em> <code class="code">followed by code</code>.</p>
```

**Comment by trefis** [comment]
I think this might be an octavius error.
@lpw25 ?

**Comment by lpw25** [comment]
Doesn't seem to be an octavius problem. The `test` executable outputs:
```
Cinfo
  text
    [
      text_element
        Raw
        "Here is some "
      text_element
        Style SK_emphasize
        text
          [
            text_element
              Raw
              "emphasis"
          ]
      text_element
        Raw
        " "
      text_element
        Code
        "followed by code"
      text_element
        Raw
        "."
    ]
  []
```
for the comment Daniel linked to.

**Comment by dbuenzli** [comment]
The problem seems more general it also happens when you have a link before code. E.g. there is no space between `color stops` and `stops` [here](https://github.com/dbuenzli/vg/blob/3a7009fa877339e625056d81285dbd873cf79df1/src/vg.mli#L330-L331).
