### ISSUE TITLE
We need ModuleType 'aliases'

### ISSUE THREAD

**Issue by jonludlam** [ocaml/odoc#650]
Where we have

```
module type X = Y
```

we are currently expanding `X`. This leads to a large number of extra module types html pages being generated. Let's not do that and just link to `Y` instead, as we do for module aliases.

This is a breaking change obviously, so we should do this before releasing.

**Comment by Octachron** [comment]
Another motivation for such aliases would be that it makes odoc's behavior uniform in presence of abstract module types.
Currently,
```ocaml
module type Abstract
module type T = Abstract
```
emits an error message
>```
>Failed to compile expansion for module type expression identifier((root Test).Abstract, false) OpaqueModule
>```
because trying to expand`T` can only fail.

**Comment by lpw25** [comment]
That's interesting, we definitely shouldn't be giving an error there. Is there also an error for:
```ocaml
module type Abstract
module M : Abstract
```

**Comment by Octachron** [comment]
The same error is raised in this case too.

**Comment by jonludlam** [comment]
I think those warnings have now been squashed.
