### ISSUE TITLE
Resolution bug for sections

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#659]
There seem to be a resolution bug for sections on master: 

Consider: 

https://b0-system.github.io/odig/doc/brr/Brr/El/index.html#el_lookups

[`.mli` source](https://github.com/dbuenzli/brr/blob/83b2a3e3944378ea29dee62dda88a627239cd15a/src/brr.mli#L1901-L1911)

In this section the first reference gets linked on `Brr/index.html` instead of `Brr/Document/index.html`. Note that the references to the value `Document.root` just below are correctly linked.

**Comment by jonludlam** [comment]
Thanks @dbuenzli - we'll take a look.
