### ISSUE TITLE
Ocamldoc can't recognize types from others modules

### ISSUE THREAD

**Issue by raulpy271** [ocaml/odoc#663]
I have a package where all modules are in the path `lib`, and the files `lib/*.mli` are documented with comments. So I tried this command to generate docs in `docs` directory:

```shell
 ocamldoc -html -d docs lib/*.mli
```

The problem is that `ocamldoc` can't recognize types that came from others modules:

```
λ ocamldoc -html -d docs lib/*.mli
File "lib/data.mli", line 3, characters 43-57:
3 |   'state -> 'symbol -> ('state * 'symbol * Tape.shiftSide) option
                                               ^^^^^^^^^^^^^^
Error: Unbound module Tape
```
But the module `Tape` exist in `lib/tape.mli`, 

Any idea what to do? Thanks

**Comment by lubegasimon** [comment]
Indeed, I have been able to reproduce this using https://github.com/ocaml/odoc/blob/master/src/document/codefmt.ml, but, is there any good reason you would not wish to produce docs using `odoc` rather than `ocamldoc`(in good faith of course)?

**Comment by raulpy271** [comment]
Hi @lubegasimon!

I searched for the repo of the `ocamldoc` and don't found, so I have guessed that is the same of `odoc`. But now, I knew that `ocamldoc` is different of `odoc`. I tried using `odoc`, and it works!

Thanks for had replied to me, and apologies for a not related issue, I'll close it.

**Comment by lubegasimon** [comment]
Totally no problem, you can find [ocamldoc here](https://github.com/ocaml/ocaml/tree/trunk/ocamldoc)

**Comment by raulpy271** [comment]
Thanks for your kindness :star_struck:
