### ISSUE TITLE
Preserve code layout in .mli files

### ISSUE THREAD

**Issue by aantron** [ocaml/odoc#680]
While writing the [docs](https://aantron.github.io/dream/#types) for Dream, I needed control over width. For example, [this function](https://aantron.github.io/dream/#val-run)

```ocaml
val run :
  ?interface:string ->
  ?port:int ->
  ?stop:unit promise ->
  ?debug:bool ->
  ?error_handler:error_handler ->
  ?secret:string ->
  ?old_secrets:string list ->
  ?prefix:string ->
  ?https:true ->
  ?certificate_file:string ->
  ?key_file:string ->
  ?builtins:bool ->
  ?greeting:bool ->
  ?adjust_terminal:bool ->
    handler -> unit
```

ought to be set like that, or in some similar way. By contrast, current odoc sets functions on one wrapped line no matter how wide the signature is. See [here](https://aantron.github.io/luv/luv/Luv/Process/index.html#val-spawn) for an example. Ideally, I would have control over width even for the latter layout, the odoc default, but for Dream's two-column layout, width control is critical.

To work around this, Dream's doc generation process applies about 1400 lines of [hand-written patches](https://github.com/aantron/dream/blob/fa20aebf36307a07b59c9ea018c25e508415d91a/docs/web/postprocess/index.ml#L12-L1498) to odoc output.

It would be much more convenient if odoc would preserve the layout in the source to the greatest extent possible, since then the `.mli` file could be used to control and tweak the appearance of the docs.

**Comment by Julow** [comment]
Since https://github.com/ocaml/odoc/pull/782, the `run` function renders like this:
```ocaml
val run : 
  ?interface:string ->
  ?port:int ->
  ?stop:unit promise ->
  ?debug:bool ->
  ?error_handler:error_handler ->
  ?secret:string ->
  ?old_secrets:string list ->
  ?prefix:string ->
  ?https:bool ->
  ?certificate_file:string ->
  ?key_file:string ->
  ?builtins:bool ->
  ?greeting:bool ->
  ?adjust_terminal:bool ->
  handler ->
  unit
```

I believe this is better than preserving the original formatting because it makes the documentation easier to read (more consistency, less different layouts to worry about).

**Comment by Julow** [comment]
I consider the automatic formatting better than the original source for consistency. Do you still need a hand-made patch in Dream ?

**Comment by aantron** [comment]
Thanks @Julow! The formatting you've shown is an improvement and I could consider switching to it. I'll try it out for Dream.

**Comment by aantron** [comment]
I've decided to stick with manual formatting in Dream for now, as I find that setting the result type with more indentation than the arguments is more legible, and also that a function with a lot of rarely-used optionals benefits from having the final `foo -> bar -> baz` on one line. I have, however, applied the new odoc formatting in Luv's docs, where I don't rewrite them, and this is a huge improvement!
