### ISSUE TITLE
list item on comment's first line

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#69]
```
$ cat list
- foo
- bar
$ ./_build/test/main.native list
Cinfo
  text
    [
      text_element
        Raw
        "- foo
"
      text_element
        List
        [
          text
            [
              text_element
                Raw
                "bar"
            ]
        ]
    ]
  []
```

I would like `foo` to be inside the list as well instead of being `Raw "- foo\n"`.

**Comment by aantron** [comment]
This was resolved by the parser overhaul. We have this as a test case:

https://github.com/ocaml/odoc/blob/5a2afda0a60aa81ebeb8fe8ed14ef6f3b6f4fd6b/test/parser/test.ml#L388

the AST produced is:

https://github.com/ocaml/odoc/blob/5a2afda0a60aa81ebeb8fe8ed14ef6f3b6f4fd6b/test/parser/expect/shorthand-list/multiple-items.txt#L4-L6
