### ISSUE TITLE
Collapse padding between consecutive code fragments

### ISSUE THREAD

**Issue by favonia** [ocaml/odoc#696]
I have been looking for ways to add links to identities in code fragments, for example `f` in `f arg`. The best workaround I found is `{!val:f}[ arg]`, but the default theme unfortunately adds padding between `{!val:f}` and `[ arg]`.

~~Proposed workaround: annotate code using CSS classes (#863)~~

Based on the discussion in #863, we should come up with a cleaner solution.

**Comment by dbuenzli** [comment]
As mentioned there the clean solution would be https://github.com/ocaml/odoc/issues/756

**Comment by favonia** [comment]
Closing this in favor of #756.
