### ISSUE TITLE
Path via include losing documentation comments

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#712]
Given the following three files:
```ocaml
(* bar.ml *)

module type T = sig
  val value : string
end
```
```ocaml
(* bar.mli *)

module type T = sig

  (** Documentation comment *)
  val value : string
end
```
```ocaml
(* foo.ml *)

include Bar

module type S = sig

  module A : T

  module B : Bar.T

end
```
The documentation for `Foo.S.A.value` has lost its comment, whilst `Foo.S.B.value` still has its comment.

**Comment by panglesd** [comment]
I tried to reproduce the issue with `odoc.2.1.1`, but it seems to have been fixed.

**Comment by Julow** [comment]
I can confirm this is fixed.
