### ISSUE TITLE
Unqualified preamble references are not resolved when the preamble is outside the module.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#713]
In the following module the reference to type {!t} is resolved in the second case but not in the first case.

```ocaml
(** The module M. 

    Resolve type {!t}. *)
module M : sig 

  type t
end
```

```ocaml
module M : sig 
(** The module M. 

    Resolve type {!t}. *)

  type t
end
```

This seems to be a regression since I suddenly have quite a bunch of unresolved xrefs in my module preambles (example in astring [here](https://b0-system.github.io/odig/doc/astring/Astring/String/index.html), [src](https://github.com/dbuenzli/astring/blob/ec7a266a3a680e5d246689855c639da53d713428/src/astring.mli#L176-L187)).

**Comment by dbuenzli** [comment]
Could we also please have that in for 2.0.0 ? It breaks a lot of docs.

**Comment by jonludlam** [comment]
We have decided to resolve the links in the context of the parent module, partly because although fixing it does fix some unresolved references, it also breaks others, and is (in my opinion) a more surprising behaviour.
