### ISSUE TITLE
Documentation should expand or link to type parameter constraints/aliases [Bos.OS.Cmd.resolve]

### ISSUE THREAD

**Issue by edwintorok** [ocaml/odoc#722]
Compare the documentation at https://v3.ocaml.org/p/bos/0.2.0/doc/Bos/OS/Cmd/index.html#val-resolve and https://erratique.ch/software/bos/doc/Bos.OS.Cmd.html

The one on v3.ocaml.org (and confirmed with odoc 1.5.3 + OCaml 4.12) generates:
```ocaml
val resolve : ?⁠search:Fpath.t list -> Cmd.t -> (Cmd.t, 'e) result
```

What is `'e`? It is not defined on this documentation page, and there is no link to it.
One might be lead to believe this is just an arbitrary type parameter (which would be problematic because then how do I print it?).
But that is not the case if you ask the ocaml toplevel:
```
# #use "topfind";;
# #require "bos.setup";;
# open Bos_setup;;
# OS.Cmd.resolve;;
- : ?search:Fpath.t list ->
    Bos.Cmd.t -> (Bos.Cmd.t, [> Rresult.R.msg ]) Bos.OS.result
= <fun>
```

In fact if you click the `result` link you can see that `'e` is defined there as:
```ocaml
type ('a, 'e) result = ('a, [> Rresult.R.msg ] as 'e) Result.result
```

~FWIW I was not aware that the scope of `'e` is larger than the `type` itself, apparently `'e` is available in the entire module that defines that type result. (probably my confusion comes from using `'` in the name of a type alias, usually type aliases don't themselves contain `'`, thus distinguishing themselves from type parameters, but not in this case).~
It looks like that in this case `'e` is indeed just a type parameter, but the constraint on `type ('a, 'e) result` ensures that it is `[> Rresult.R.msg]`.

In the original upstream documentation `'e` is fully expanded, so it contains:
```
val resolve : ?search:Fpath.t list ->
       Bos.Cmd.t -> (Bos.Cmd.t, [> Rresult.R.msg ]) Bos.OS.result
```

I think that odoc should at least link to the ~definition~ constraint definition of `'e`, and I'd recommend that it fully expands it where possible (as apparently it - or ocamldoc - was able to do in the past when generating the original upstream docs)

**Comment by jonludlam** [comment]
Odoc's just doing here what's been explicitly written in the `mli` file [here](https://github.com/dbuenzli/bos/blob/61526bf67f218fd730db8ac19149945eb9c97d20/src/bos.mli#L1129).

It's a little dangerous to try to rewrite what's been hand-written -- I'd be more sympathetic if odoc were working from a cmt rather than cmti file. I'm not quite sure how @dbuenzli got the results on his site. Daniel?

**Comment by edwintorok** [comment]
I can reproduce the expanded version from @dbuenzli 's original docs by doing this:
```
opam source bos && cd bos*
opam install topkg-care
topkg doc
```

It runs these commands to generate the docs:
```
ocamlfind ocamldoc -dump src/bos.odoc -colorize-code -charset utf-8 -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -I src -I test src/bos.mli
ocamlfind ocamldoc -dump src/bos_setup.odoc -colorize-code -charset utf-8 -package fmt.tty -package logs.fmt -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -I src -I test src/bos_setup.mli
+ ocamlfind ocamldoc -dump src/bos_setup.odoc -colorize-code -charset utf-8 -package fmt.tty -package logs.fmt -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -I src -I test src/bos_setup.mli
+ ocamlfind ocamldoc -dump src/bos.odoc -colorize-code -charset utf-8 -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -I src -I test src/bos.mli
ocamlfind ocamldoc -load src/bos.odoc -load src/bos_setup.odoc -colorize-code -charset utf-8 -html -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -d doc/api.docdir
+ ocamlfind ocamldoc -load src/bos.odoc -load src/bos_setup.odoc -colorize-code -charset utf-8 -html -package bytes -package rresult -package astring -package fpath -package fmt -package logs -package unix -d doc/api.docdir
```

Whereas the odoc invocation looks like this (from `odig` logs):
```
[069:spawn 206ms bos e:8ba2251a39cf5a30] ['/home/edwin/.opam/4.12.0+domains/bin/odoc' 'compile' '--pkg' 'bos' '-o' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/bos/bos.odoc' '/home/edwin/.opam/4.12.0+domains/lib/bos/bos.cmti' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/astring/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/fmt/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/fpath/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/logs/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/ocaml/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/result/' '-I' '/home/edwin/.opam/4.12.0+domains/var/cache/odig/odoc/rresult/'][0]
```

**Comment by dbuenzli** [comment]
> I'm not quite sure how @dbuenzli got the results on his site. Daniel?

As can be seen in Edwin's that's an old `ocamldoc` docset (it means it has been a while since I didn't do a bos release).

**Comment by edwintorok** [comment]
Perhaps it'd be good to have both the original and the expanded version if possible, choose one to show as default based on what odoc deems to be the best, and link to the other one if different (or have some CSS to hide/show one based on a click, which IIRC can be done without javascript etc.). Or have a way for package authors to choose whether to fully expand or preserve originally written types?
FWIW ocaml-lsp-server is able to show the expanded version too, evn if I delete the .mli file, so I assume the .cmti would contain enough information to determine this?

**Comment by dbuenzli** [comment]
I have no strong opinion on the issue at hand. 

But I guess while the constraint in `bos`' case is small, renderings can quickly get overwhelming if it's not. Maybe in the name of consistency it's better to keep it this way.

**Comment by edwintorok** [comment]
Perhaps a simple improvement here would be to add a link from `'e` to the OS.Cmd.result type if odoc detects that the result type has additional constraints on that type parameter? That'll keep the documentation succint, doesn't require to change what the package author has written, while also guiding the user towards where it can learn more about the constraints for the type.

If there are multiple type parameters and types nested then I think the link from the type parameter should be to the immediately enclosing type. What do you think?

**Comment by lubegasimon** [comment]
> It's a little dangerous to try to rewrite what's been hand-written

I do agree with @jonludlam. Being that `odoc` prioritises looking at the `cmti` file unless it’s not provided then `cmt` file is considered. `odoc` assumes that all the information needed resides in the `mli` file. 

> Perhaps a simple improvement here would be to add a link from 'e to the OS.Cmd.result type if odoc detects that the result type has additional constraints on that type parameter?

I can imagine how this would be hard to implement and also make room for bugs. As a simple workaround, I would encourage package authors to annotate about the constrained type parameter.  I believe if “ `where [‘e] is [[> Rresult.R.msg ]]` “ was explicitly added to the doc comment, it would shade more light in this case.

**Comment by dbuenzli** [comment]
> I believe if “ `where [‘e] is [[> Rresult.R.msg ]]` “ was explicitly added to the doc comment, it would shade more light in this case.

You are generalizing over one occurence of the problem. You have to imagine more complex constraints, it would become both unreadable and harder to maintain.

**Comment by Julow** [comment]
The consensus seems to be that Odoc shouldn't rewrite types. I'll close.
