### ISSUE TITLE
feature request: indent nested includes

### ISSUE THREAD

**Issue by asavahista** [ocaml/odoc#734]
currently nested includes are not indented, meaning that it's not possible to tell what will be collapsed when collapsing the body of the include. it's not a big deal, but may be a small qol improvement.

an example is `Comparable.S` in [the base docs](https://v3.ocaml.org/p/base/v0.14.1/doc/Base/Identifiable/module-type-S/index.html)

something like this should work:
```css
.odoc-include .odoc-include {
    margin-left: 1em;
}
```
the amount of indentation can be changed - for reference rustdoc uses 20px/24px for indentation in its `<details>` ([example](https://doc.rust-lang.org/std/vec/struct.Vec.html#blanket-implementations)), haddock uses 0.5em ([example](https://hackage.haskell.org/package/base-4.15.0.0/docs/Control-Monad.html#v:-60--36-)). it may be worth checking out other documentation generators too

for convenience, the appropriate part of the css starts here:
https://github.com/ocaml/odoc/blob/79ee6133dd58ce2891eaa8f8a8de06cf7f9ba76b/src/odoc/etc/odoc.css#L466

**Comment by jonludlam** [comment]
This issue is known - it's something that needs fixing in v3.ocaml.org-server which uses custom CSS. The issue is tracked here: ocaml/v3.ocaml.org-server#54. Odoc's default CSS uses a shaded bar on the side to show what comes from the include.
