### ISSUE TITLE
Different handling of stop-comments on OCaml 4.03

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#737]
The "attaching" of stop-comments changed in OCaml 4.04.2: https://github.com/ocaml/ocaml/pull/872
With older versions, the module `X` won't be hidden in the following example because both stop-comments would be attached as attribute and would loose their relative positions:

```ocaml
(**/**)
module X : sig end
(**/**)
```

Was interpreted like:

```ocaml
(**/**)
(**/**)
module X : sig end
```

**Comment by jonludlam** [comment]
I don't think we need to fix this.

**Comment by asavahista** [comment]
makes sense but CI for tests should probably still be fixed somehow

**Comment by jonludlam** [comment]
Definitely, the fix for CI is straightforward!
