### ISSUE TITLE
Identifier shadowing of included signature is not handled correctly.

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#74]
Both identifier and their definition show up in the docs. See: 

  http://docs.mirage.io/fpath/Fpath/Map/index.html#val-find

and the other `find` just above [this def](http://docs.mirage.io/fpath/Fpath/Map/index.html#val-get). This also means that this document is invalid html (`id`s are not unique).

**Comment by jonludlam** [comment]
This no longer happens with the new model.
