### ISSUE TITLE
Understand line directives in .mld files

### ISSUE THREAD

**Issue by jeremiedimino** [ocaml/odoc#76]
It'd be nice if line directives in .mld files where supported, so that when a mld file is generated syntax errors point to the right place.

In jbuilder I'd like to generate .mld files that look like:

```
{%html:<nav><a href="..">Up</a></nav>%}
# 1 "foo.mld"
<contents of foo.mld, written by the user>
```

**Comment by trefis** [comment]
We might add this at some point, but I have no idea when.
Until then, perhaps you might want to call `octavius` (the executable) on `foo.mld`? You want to ignore what it prints on stdout but report what it prints on stderr (i.e. the errors, printed using `Location.report_error`).

**Comment by diml** [comment]
I guess I'll just wait, can't be bothered implementing hacks if there is a proper solution coming :stuck_out_tongue_closed_eyes:

**Comment by jeremiedimino** [comment]
I'm not particularly interested in this anymore, and this issue was never referenced. So it seems fair to close it.
