### ISSUE TITLE
Odoc does not support odoc code blocks within code blocks

### ISSUE THREAD

**Issue by NathanReb** [ocaml/odoc#776]
When writing an ocaml code block in odoc markup that itself contains an odoc code block, the first end of block delimiter is interpreted as closing the encompassing block.

For example:
```ocaml
(** Here is how to write odoc code blocks:
  {[
  (** Here is an ocaml code block:
    {[
    let x = 0
    ]}
  *)
  ]}
*)
```
Will not be rendered as:
![Screenshot from 2021-11-10 10-46-07](https://user-images.githubusercontent.com/7419360/141089966-740b9ece-f902-4acc-9f12-d801ddc14570.png)

Problem is, if you try to escape the characters, it is also not properly rendered:
![Screenshot from 2021-11-10 10-48-37](https://user-images.githubusercontent.com/7419360/141090294-662a5032-a94a-4c75-aba1-77f72f07f7cc.png)

It would be nice to have a way to get this to work both in `{[ ... ]}` and `{@ocaml[ ... ]}` code blocks or to have a way to escape those characters properly.

**Comment by NathanReb** [comment]
CC @Julow who helped me find out about this bug!

**Comment by panglesd** [comment]
This is fixed by the `{delim[ ... ]delim}` syntax!

**Comment by dbuenzli** [comment]
And nicely mentioned in the cheatsheet I should add…
