### ISSUE TITLE
Cross page section link using labels don't expand to the section title

### ISSUE THREAD

**Issue by NathanReb** [ocaml/odoc#779]
When cross referencing a section from a different page without a specified text for the link, the label will not be expanded into the corresponding section's title.
For example, if you define the following section in `a.mld`:
```
{1:some_label Some Grand Title}
```

And then later reference it from `b.mld` as follows:
```
See {!page-a.some_label}
```

The paragraph will read "See some_label".

**Comment by NathanReb** [comment]
This behaviour was originally described in the documentation added in #775. @Julow confirmed it was a bug and not intentional so I created this issue instead.

**Comment by dbuenzli** [comment]
Should be fixed by #1116
