### ISSUE TITLE
Raise in `Cmi_format.read_cmi` using odig

### ISSUE THREAD

**Issue by MisterDA** [ocaml/odoc#802]
I keep having this error on whatever package I tried to generate the documentation (on Arch Linux, ocaml and opam from the distro). Possibly related to odig, so I'm cc-ing @dbuenzli. Not sure how I give instructions to reproduce, I've just deleted my `.opam` and from a scratch install I get the error right away.

```
$ ~ odig doc ocaml
Updating documentation, this may take some time...
odig: [ERROR] Documentation might be incomplete (see: odig log -e).
$ ~ odig log -e
[FAILED 1024:spawn 12.3ms ocaml e:f0c6df3f1bb878ed] ['/home/antonin/.opam/default/bin/odoc' 'compile-deps' '/usr/lib/ocaml/brlapi/brlapi.cmi' > '/home/antonin/.opam/default/var/cache/odig/odoc/ocaml/brlapi/brlapi.odoc.deps'][2]
odoc: internal error, uncaught exception:
      Cmi_format.Error(_)
      Raised at Cmi_format.read_cmi in file "file_formats/cmi_format.ml", line 83, characters 6-21
      Called from Odoc_odoc__Depends.for_compile_step_cmi_or_cmti in file "src/odoc/depends.ml", line 37, characters 18-62
      Called from Dune__exe__Main.Depends.Compile.list_dependencies in file "src/odoc/bin/main.ml", line 578, characters 17-72
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 25, characters 19-24
      Called from Cmdliner.Term.run in file "cmdliner.ml", line 117, characters 32-39

$ ~ ocaml --version
The OCaml toplevel, version 4.13.1

$ ~ odig --version
v0.0.7
$ ~ odoc --version
2.0.2
```

**Comment by lubegasimon** [comment]
Just a hint, `odig` invokes `odoc` only on what you’ve got installed in your Opam switch.

**Comment by dbuenzli** [comment]
> '/usr/lib/ocaml/brlapi/brlapi.cmi'

Looks like `odoc` is being used on the system install which I suspect does not match the version `odoc` was compiled with.

**Comment by MisterDA** [comment]
> > '/usr/lib/ocaml/brlapi/brlapi.cmi'
> 
> Looks like `odoc` is being used on the system install which I suspect does not match the version `odoc` was compiled with.

Indeed, removing these packages `ocaml opam camlp4 ocaml-compiler-libs brltty` and reinstalling only `opam` and its dependencies fixed my problem. Looking at the prefix, `brltty` certainly was part of the issue. Thanks!

**Comment by dbuenzli** [comment]
Well `odoc` could provide a more user friendly error like the compiler does when it tries to read unknown compiler artefacts rather than blow in your face with a stacktrace.

Also I don't think you should have to remove any package. It looks more like a `PATH`/`opam env` issue.
