### ISSUE TITLE
Putting -open flags in dune breaks synopsis generation for module index

### ISSUE THREAD

**Issue by jorisgio** [ocaml/odoc#806]
See reproduction example : https://github.com/jorisgio/test-odoc
```dune build @doc``` generates the module list properly for `test_lib` modules if dune file does not contain `-open containers`, but it does not add synopsis when any `-open` flags are present

**Comment by Julow** [comment]
I fail to reproduce, I'm using Dune 2.9.1 and adding the open flag like this:
```diff
diff --git a/dune b/dune
index dddd8d9..8492d69 100644
--- a/dune
+++ b/dune
@@ -3,4 +3,4 @@
  (public_name test_lib)
  (modules foo)
  (libraries containers)
- )
+ (flags -open Containers))
```

**Comment by jorisgio** [comment]
Sorry indeed :( this was not the issue, i just failed to opam env properly.
