### ISSUE TITLE
Allow level-0 headings in mli

### ISSUE THREAD

**Issue by Julow** [ocaml/odoc#815]
Currently, level-`0` headings aren't allowed in `.mli` files at all. Odoc generates the equivalent of `{0 Module <module name>}` internally.
However, for `.mld` pages, it's the opposite, a title is always required. (https://github.com/ocaml/odoc/issues/220)

Should we allow titles at the very top of a `.mli` file ? (before any code or documentation)

I think no, because the name of a module is important and be better rendered in a consistent way. Customizing the title buries the name of the module without adding much more.

**Comment by Drup** [comment]
This has gone back and forth quite a while.

You give the arguments yourselves: Modules have a natural title, and shouldn't get one more. mld pages do have a natural title, and must get one.

**Comment by dbuenzli** [comment]
As @Drup mentions this has been discussed to death at [some point](https://github.com/ocaml/odoc/issues/141). I don't think it worth getting back to it. @Julow don't hesitate to reopen if you have a compelling argument but I think it's better not to run in circles here.
