### ISSUE TITLE
References not resolved within `@deprecated` and other tagged paragraphs

### ISSUE THREAD

**Issue by paurkedal** [ocaml/odoc#827]
Given an interface `two.mli`:
```ocaml
val y : unit
(** Nothing to see here. *)

val z : unit
(** Equivalent to {!One.x} and {!y}.

    @deprecated Move along to {!One.x} or {!y}.

    @return The same value as {!One.x} and {!y}.

    @raise Not_found if {!One.x} and {!y} are different. *)
```
the and a corresponding `one.mli` documenting `x`, neither of the references within the `@deprecated`, `@return` and `@raise` paragraphs are resolved by odoc 2.0.2, while the ones outside are.

The reference to the external module also shows the symptom reported in #816. The issue #818 might also be related.

**Comment by mattjbray** [comment]
I ran into the same when trying to add a cross-reference to a `@param` block tag.
