### ISSUE TITLE
Sum-types docs are glued to long sum types

### ISSUE THREAD

**Issue by MisterDA** [ocaml/odoc#834]
Using odoc.2.1.0 (and Firefox), when the constructor name and its type are long, it gets glued to the documentation. That's bad for readability.
I also think that the inter-line spacing between constructors is too wide.

![image](https://user-images.githubusercontent.com/1773581/155188129-91ca345e-e39a-4f8d-90ea-1a8f13d37300.png)

EDIT: ah, this is addressed by #830, right?

**Comment by panglesd** [comment]
> EDIT: ah, this is addressed by https://github.com/ocaml/odoc/pull/830, right?
Yes, exactly!

**Comment by dbuenzli** [comment]
#830 having been merged this should be solved.
