### ISSUE TITLE
Alignment issue with Fira Mono

### ISSUE THREAD

**Issue by vphantom** [ocaml/odoc#850]
Hello! This is related to #397. Here's what I see with Odoc's choice of `Fira Mono` for a `{v…v}` block:

![odoc_fira_mono16](https://user-images.githubusercontent.com/3063161/158398811-b277c1d5-dca0-426f-a30d-645f5d757e28.png)

If I change that font to `Fira Code` (which I happen to have installed), the ASCII art becomes seamless as expected:

![odoc_fira_code16](https://user-images.githubusercontent.com/3063161/158398923-88e02753-5fda-44ed-817b-fb094b8370cb.png)

Is `Fira Mono`, the CSS' assumptions around using it, or my system to blame?  Here's the source for reference:

```text
Module    │ Get (opt) │ Get (exn) │ Test
──────────┼───────────┼───────────┼───────
Hashtbl   │ .%()      │ .%^()     │ .%?()
StringSet │           │           │ .$?[]
StringMap │ .$()      │ .$^()     │ .$?()
IntMap    │ .!()      │ .!^()     │ .!?()
Custom... │ .@()      │           │
```

**Comment by Julow** [comment]
[Fira Code](https://github.com/tonsky/FiraCode) and [Fira Mono](https://github.com/mozilla/Fira) are very different fonts, the latter doesn't have ligatures. This is the expected result.

ASCII art in documentation is not ideal because it's hard to maintain and you can't use other markups in it (eg. references). It seems that you need a markup for drawing a table.

**Comment by dbuenzli** [comment]
> [Fira Code](https://github.com/tonsky/FiraCode) and [Fira Mono](https://github.com/mozilla/Fira) are very different fonts, the latter doesn't have ligatures.

Indeed. It seems Fira Code was used at some point but switched over to Fira Mono due to legibility concerns see https://github.com/ocaml/odoc/issues/248

So I'm afraid @Julow is right here:

> This is the expected result.

Regarding:

> ASCII art in documentation is not ideal because it's hard to maintain and you can't use other markups in it (eg. references). It seems that you need a markup for drawing a table.

An issue was opened for this in #864.
