### ISSUE TITLE
Add support for tables

### ISSUE THREAD

**Issue by MisterDA** [ocaml/odoc#864]
In documentation it can be really handy to have tables (for instance, for side-by-side comparison). It would be nice if odoc had a native syntax support for tables. For now I resort to using the `{%html: …%}` tag.

**Comment by jonludlam** [comment]
@gpetiot has made a draft PR with a suggestion for concrete syntax on the [odoc-parser](https://github.com/ocaml-doc/odoc-parser/pull/11) repository - I think it would be very useful to get some feedback there.

**Comment by panglesd** [comment]
Yes!
