### ISSUE TITLE
Drop OCaml < 4.08

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#868]
I think it's time to move away from 4.02 which was released in 2015, seven years ago. 4.08 is a reasonable version, one of which brought many stdlib improvement.

Here are a few arguments: 

1. It would also to use cmdliner without that [monkey dance](https://github.com/ocaml/odoc/blob/6ac97f3148f7791ec7451785ef4dbd9ca0daf2d1/src/compat/compatcmdliner.ml). 
2. I was looking at the use of `Astring` in the repo which I would like to remove as a *direct dependency* (`Fpath` unfortunately also depends on it but I'd like to drop that dep there at some point too and/or remove it here too). Most of the uses of `Astring` are to work around the `String.$(op)` vs `String.ascii_$op` warnings (introduced `4.03`). Other than that we have `Astring.String.cut` all of which use a single character and can be replaced by `String.split_on_char` (introduced `4.04`). After that it only `Astring.String.is_{prefix,affix}` remains which we can easily define in the repo itself.
3. I'm pretty sure the 4.02 `cmt[i]` files were broken in some way.

**Comment by jonludlam** [comment]
As I mentioned in #873:

"I'd quite like to see the features we know we want for the ocaml website to land before we drop support for the older versions - so for example the 'uses' work that will be used to drive search. That way, once we've got those bits and pieces in we can just have a maintenance branch that supports 4.02-4.07 that will hopefully be easy to manage, and we won't have to backport that sort of relatively large feature.

Of course, if it actually does become more of a burden then we can revisit this, but so far keeping our lower bound at 4.02 has only been a case of a few minor shims here and there."
