### ISSUE TITLE
Avoid grabbing all keys in JS, to support browser plugins

### ISSUE THREAD

**Issue by rand00** [ocaml/odoc#869]
I just tested out `odig odoc PKG`, but found that my firefox plugin `vimium` doesn't work in the documentation - as all keys are grabbed by som JS script in generated page. I can ofc. block JS via NoScript on `file:` - but is a hack, and applies to all files

**Comment by dbuenzli** [comment]
Ah you mean grabbing keyboard input. 

Well I'm afraid the problem must be elsewhere on your side. There's absolutely no JavaScript for input handling in `odoc`, only plain `html` generation (except for the syntax highlighting bit but I doubt it interacts with keyboard input).

**Comment by rand00** [comment]
Ah okay, you are correct - I tried modifying the odoc file and removed the script - and it still doesn't work.

**Comment by dbuenzli** [comment]
Which stylesheet are you using ?

**Comment by rand00** [comment]
Just the default, why?

**Comment by dbuenzli** [comment]
The default of `odoc` or `odig` ? I.e. what does 
```
odig odoc-theme get    
```
say.

> why?

It's unlikely the `odig/odoc` stylesheets are doing anything but you can actually do stuff with input in css.

**Comment by rand00** [comment]
> odig odoc-theme get    

It gives me `odig.default` 

Just disabled the stylesheet too - still doesn't work ... something weird is going on (:

**Comment by dbuenzli** [comment]
Ok. Basically I thought maybe there's something that grabs the focus via `tabindex` or something like that but it doesn't seem so.

Good luck, browser extensions are a nightmare. I once lost hours with a client trying to figure out a web app bug only to realize he had an extension that was interfering…

**Comment by rand00** [comment]
:P

**Comment by rand00** [comment]
Script for serving odoc @ port 8000:
``` bash
#! /bin/bash

ROOT="$(opam var prefix)/var/cache/odig/html"
python -m http.server --directory "$ROOT" 
```

**Comment by dbuenzli** [comment]
I wanted to suggest: 
```
php -S localhost:8000 -t $(dirname $(odig doc -f))
```
but I ran into an odig bug :-( https://github.com/b0-system/odig/issues/68

**Comment by rand00** [comment]
hehe

**Comment by rand00** [comment]
... hmm - I wonder why blocking JS on local files with NoScript worked... don't want to dive deeper into this now :/
