### ISSUE TITLE
Incorrect handling of shadowed elements of included module types

### ISSUE THREAD

**Issue by bluddy** [ocaml/odoc#875]
[Example from Containers](http://c-cube.github.io/ocaml-containers/dev/containers/CCRandom/index.html)

`Stdlib.Random` is included, but shadowed by functions with the same name but different types. (e.g. see `val int`). `odoc` displays the included module type as is , which is wrong because some of these functions are never exported as they are. It's even worse because the included module type starts open on the page, making it seem like this is the exported type, which is not the case.

**Comment by bluddy** [comment]
Huh -- I could have sworn I saw `val int` in there twice. Sorry for the noise.

**Comment by jonludlam** [comment]
Let's close this one - but we should check the other point about not having the doc strings - is that still the case in the master branch?
