### ISSUE TITLE
Support for `@perform` tag in odoc

### ISSUE THREAD

**Issue by raphael-proust** [ocaml/odoc#880]
Moved from https://github.com/ocaml/ocaml/issues/11327

The `ocamldoc` and `odoc` commands supports multiple tags for docstrings. They support `@raise` which is useful to document the exception raising behaviour of functions. It would be useful to have a similar `@perform` tag for effects.

Documenting which effects are performed by which function seems important for an API to be usable. It helps determine what handler is needed. Having an `@perform` tag would make such documentation more normalised, more greppable.

The format of the suggested tag can be similar to that of the exception raising one (`@perform` Effect text) and the rendering too.

------------------------------------

In https://github.com/ocaml/ocaml/issues/11327#issuecomment-1160207852 @Octachron says

> I am not sure that having a documentation tag for an experimental feature is a good idea.
> 
> Moreover, we plan to have a typed effect system by the time effect handlers are no longer experimental. This means that the tag would be only useful during the experimental phase of effects which seems not ideal.

And in https://github.com/ocaml/ocaml/issues/11327#issuecomment-1161348076 I reply

> I'm not sure that's true. Even if we had exception-tracking in the type system, it'd be useful to have the `@raise` tag. Specifically, it'd be useful so that you could indicate the conditions under which an exception is raised:
> 
> ```
> val make : int -> t with raise Invalid_argument
> ```
> 
> is less informative than
> 
> ```
> (** [make v] creates a new [t] blah blah balh
> 
>     @raise Invalid_argument if a prior call to [make u] was made where [u >= v]. *)
> val make : int -> t with raise Invalid_argument
> ```
> 
> For the same reason the `@perform` tag could still be useful. (It's similar to how we have the `@param` and `@return` tags even though those already appear in the type of the function.)

**Comment by dbuenzli** [comment]
FWIW I find myself in agreement with @Octachron here.

**Comment by dbuenzli** [comment]
Given the experimental nature of effects, this seems premature to me. I move on to close this.
