### ISSUE TITLE
Long filepaths on Windows

### ISSUE THREAD

**Issue by dybber** [ocaml/odoc#885]
Hi there!

We're having some issues with `odoc` on Ocaml for Windows (Cygwin), where we see errors such as the following:

```
odoc: internal error, uncaught exception:
Unix.Unix_error(Unix.ENOENT, "mkdir", "dimapi@26bb1931b3ad\\Scd_map_collections_and_grids\\MakeCollectionsAndGrids\\argument-1-X\\Trie\\module-type-IMPLEMENTATION\\Tree\\Annotated\\LinkWithForeignTree\\argument-1-ForeignTree\\Sequence\\")
      Raised by primitive operation at Odoc_odoc__Fs.Directory.mkdir_p.mkdir in file "src/vendor/odoc.2.1.0/src/odoc/fs.ml", line 129, characters 10-46
      Re-raised at Odoc_odoc__Fs.Directory.mkdir_p.mkdir in file "src/vendor/odoc.2.1.0/src/odoc/fs.ml", line 131, characters 15-24
      Called from Stdlib__List.iter in file "list.ml", line 128, characters 12-15
      Called from Odoc_odoc__Rendering.render_document.(fun) in file "src/vendor/odoc.2.1.0/src/odoc/rendering.ml", line 28, characters 6-36
      Called from Odoc_document__Renderer.traverse.aux in file "src/vendor/odoc.2.1.0/src/document/renderer.ml", line 15, characters 4-32
```

The problem being that the full path is too long for Windows to handle. The problem is not in `odoc` per se, as it is Windows that puts in this limitation, instead it's the way `odoc` sometimes generates these long paths, for instance if you have several nested modules/functors in one file, not only is an HTML file generated for the file, but for every nested module.

The weird thing is that we actually CAN create said directory manually from Cygwin or cmd.exe terminal, so Windows 10 actually supports such long path now adays, but somewhere the restriction on max 256 characters is still in place. Perhaps if `odoc` called `mkdir` with `Sys.command` this wouldn't be an issue.

**Comment by dbuenzli** [comment]
[This](https://github.com/ocaml/odoc/blob/d4a8c503da2a1bf87e9b8456b2442443784484ef/src/odoc/fs.ml#L127-L137) is the function throwing the error. I'm a bit surprised this would be a long path issue as no such limitation is documented in the [`Unix` library](https://v2.ocaml.org/manual/libunix.html) which that function uses. Does maybe @dra27 have an idea of what could be going on here ?

**Comment by dybber** [comment]
I tried calling exactly that function by itself, and when the full path was 256 characters it succeeded, when it reached 257 characters it failed.

**Comment by dybber** [comment]
You're right, maybe I should try writing a simple C program that calls `_wmkdir()` and report the error to the cygwin mailing list.
