### ISSUE TITLE
Add a `--fragment` option to `odoc html`

### ISSUE THREAD

**Issue by dbuenzli** [ocaml/odoc#89]
That outputs only the markup in the `body`, see https://github.com/ocaml-doc/odoc/issues/61#issuecomment-308731899. This is needed for https://github.com/dbuenzli/odig/issues/19 and https://github.com/dbuenzli/odig/issues/18.

**Comment by trefis** [comment]
Currently `odoc html foo.odoc` will output as many html files as there are (sub)modules in the unit `Foo`. What would you like the output to be when `--fragment` is passed?

**Comment by dbuenzli** [comment]
Each file with only the internal markup.

**Comment by dbuenzli** [comment]
Any news on that front ?

**Comment by rizo** [comment]
@dbuenzli I think I understand _what_ needs to be done but I'm not 100% sure _why_ this needs to be done. I did read all linked discussions but some comments seem a bit incomplete or outdated.

So please bare with me while I'm trying to understand this feature.

Here's the *what*:

- Add the `--fragment` option to `odoc html`.
- It will represent exactly the same HTML tree as the one generated currently.
- The same `--output-dir` will be used to save the files.
- Only the content of the `body` tag will be present (so no `head`, no CSS links. _etc_).

Here's my understanding of *why*:

- We want to add HTML items (like headers, sidebars, footers?) around the content.
- This will allow allow us to effectively inject the HTML tree into existing web templates.

Am I missing something? If the above is correct, I don't really understand how the complementary HTML items will be added. Will people have to provide a "chrome" file (as you called it) to `odig` during doc generation? Will this somehow impact the existing template (_e.g._ we already have a sidebar)?

**Comment by dbuenzli** [comment]
> Am I missing something? If the above is correct, I don't really understand how the complementary HTML items will be added.

Yes. However now that I'm thinking about we nowadays have `.mld` pages I may be able do without this, though I didn't look at how .mld generation works yet. 

At least for customized package landing pages, I think I can simply take the package's `$DOCDIR/$PKG/odoc-pages/index.mld` create a new mld document which surrounds that content with the `odig` chrome (that is package information as seen for example [here](https://docs.mirage.io/alcotest/index.html)) and render the result as the index page. That would do without `--fragment`.

For https://github.com/dbuenzli/odig/issues/19 that is replacing the first paragraph of this [page](https://docs.mirage.io/), the person running odig will have to provide a `.mld` file at generation time. Here again I may also be able to do it by generating a prop .mld file without --fragment if it is possible to generate one that is not tied to a package.

**Comment by rizo** [comment]
Regardless of the options I'm interested helping you with this (assuming you need help, that is :P). 

> I think I can simply take the package's $DOCDIR/$PKG/odoc-pages/index.mld create a new mld document which surrounds that content with the odig chrome

By this, do you literally mean appending/prepending a docstring to the original `index.mld` file?

>  I may also be able to do it by generating a prop .mld file without --fragment if it is possible to generate one that is not tied to a package.

In order to generate an `odoc` file for a `mld` file you can run: `odoc compile --package=PKG -o page-PAGE.odoc PAGE.mld`. As you can see the `package` is required and it's used to generate the navigation for the page and the title.

**Comment by dbuenzli** [comment]
> Regardless of the options I'm interested helping you with this (assuming you need help, that is :P).

Oh your help is very welcome. All this stuff has been lingering for way too long.

> By this, do you literally mean appending/prepending a docstring to the original index.mld file?

Yes. `sprintf "... %s ..." (string_of_file "$DOCDIR/$PKG/odoc-pages/index.mld")`

> In order to generate an odoc file for a mld file you can run: odoc compile --package=PKG -o page-PAGE.odoc PAGE.mld. As you can see the package is required and it's used to generate the navigation for the page and the title.

Aha then `--fragment` (or whatever that should be called) might be useful for that. In general it's useful if one is able to render a documentation language to html fragments. Maybe a first step would be to do this only for `.mld` file (but I don't know if `.odoc` files have the info).

**Comment by rizo** [comment]
I finally found some time to work on this. Here're some of my initial thoughts:

1. @dbuenzli is it ok if we rename the flag to `--body-only`? I think it's more clear and `--fragment` is already [used](https://developer.mozilla.org/en-US/docs/Web/API/Document/createDocumentFragment#Description) in the HTML to mean something else.
2. Since the generated output will only contain the body, how will you load the theme and support files in the parent document?

---

I also have some questions about the implementation. (CC @aantron and maybe @Drup)

The typed HTML in odoc is super rigid and leaves no space for flexibility. The fact that we might have two kinds of HTML trees (body/html) as an output means that everything else has to be aware of that. 

I've tried multiple solutions so far: my first naive approach resulted in a lot of duplication; the one that seems to be less boilerplaty is using GADTs for output selection. I've introduced the `Html_tree.root` type that decides whether an `` `Html `` or `` `Body `` tree will be generated. The problem is that this `~root` value needs to be threaded through all visiting functions in `to_html_tree`.

Do you think there's a better/simpler way to implement this?

Here's a simplified WIP diff for reference:
https://github.com/rizo/odoc/compare/html_body_only

**Comment by aantron** [comment]
I personally would be in favor of an untyped HTML representation.

For ensuring the generated HTML *tends* to be valid, we can run validators on test output during testing.

Having an untyped HTML representation could also help if we ever have other output targets, and need to, say, functorize the output type somehow. TyXML types are probably way too rich to do that with. But there may be designs that avoid this problem.

**Comment by Drup** [comment]
> Having an untyped HTML representation could also help if we ever have other output targets, and need to, say, functorize the output type somehow. TyXML types are probably way too rich to do that with. But there may be designs that avoid this problem.

What are you talking about. Tyxml already does that for you for free.

**Comment by dbuenzli** [comment]
@rizo `--body-only` seems fine, regarding 2. that should be most of the time only a css file so I'm fine with a status quo on that for now, unless you want to design something.

Though this is a bit OT re tyxml vs untyped representation. I know some people are very fond of the HTML typing *trick*, and I was very enthusiastic aswell when it first [came out](https://inbox.ocaml.org/caml-list/200304300120.h3U1KfL25181@wptx47.physik.uni-wuerzburg.de/) (yes that's 2003). However having tried it in a few private projects in the first decade of the century I nowadays think it's rather a pain to work with for little returns in practice.

I expressed my doubts to @trefis when he choose to use tyxml in the first place and to make my point in a sneaky way I showed him that the pages he generated were not validating (he'd generate multiple elements with the same id...). IIRC he later told me if he was to do it again he wouldn't use it -- he'll correct me if I'm wrong. 

In odig I quickly hacked a few [toy combinators](https://github.com/dbuenzli/odig/blob/66819154ae43a8fcca8a3857ca9851a058661ee4/src/odig.mli#L1187-L1271) for that ([implementation](https://github.com/dbuenzli/odig/blob/66819154ae43a8fcca8a3857ca9851a058661ee4/src/odig_html.ml) and [usage](https://github.com/dbuenzli/odig/blob/66819154ae43a8fcca8a3857ca9851a058661ee4/src/odig_api_doc.ml)), feel free to steal them and relicense them according to `odoc`'s license if you are interested in integrating them. 

In any case I think it would be good to have a real `tidy` validation check in the test suite and I personally think it's always good if we can trim as many dependencies as possible from `odoc`; but it's of course up to `odoc`'s main authors to choose the markup generation technology they wish.

**Comment by Drup** [comment]
@rizo I actually don't really disagree, tyxml is definitely a rough learning curve. However, the odoc implementation is also a bit to blame: odoc's code in general is pretty high-flying (it's not completely surprising, given the original authors :p). The tyxml code I have seen was really too entangled with some non-tyxml code.

Of course the code would be improved by rewriting it, because it's always better the second time, but I'm not sure the untyped aspect would gain you the most. Having an intermediate layer between the raw typing information and the actual HTML (similar to Outcometree in the compiler) would be a much more significant improvement in my opinion (and would ease writing other output modes).

**Comment by rizo** [comment]
Thanks for your suggestion @Drup. We should definitely consider cleaning up and simplifying the HTML generation (with or without tyxml). I might experiment with alternative approaches discussed here. To conclude this topic: it seems reasonable (to me) to finish the `--body-only` feature using a GADT to constrain the generated HTML tree, despite its complexity and boilerplate.

**Comment by aantron** [comment]
> Should we open an issue to discuss the HTML validation tooling?

Yes, I opened #165 for it.

**Comment by rizo** [comment]
Coming back to the feature design...

> --body-only (or --only-body ?) seems fine

@dbuenzli Other tools seem to favour the `--TARGET-only` convention (_e.g._ `opam install --deps-only`), but I'm fine with either.

> 2. that should be most of the time only a css file so I'm fine with a status quo on that for now, unless you want to design something.

Sorry, but I don't find this satisfactory... In addition to `odoc.css` we already have one JavaScript file and will have others in the future. Also is it desirable to have a sidebar in the produced HTML? An obvious design for this would be to introduce a complementary option that would generate the dependencies in the `head` element for CSS and JS includes (`--deps-only`?). But honestly, I don't feel particularly happy about that either.

Allow me to zoom out a bit to reconsider options. This feature is needed for two different use cases:

1. [Support for customizing the toplevel header of the package list](https://github.com/dbuenzli/odig/issues/19)
2. [Support for customizing the toplevel module list of a package](https://github.com/dbuenzli/odig/issues/18)


### Regarding the use case 1

Have you considered supporting HTML directly? I know it's not ideal but I don't see how having ocamldoc syntax is important here. This feature is needed for publishers (only) who want to customise their package documentation registry with custom branding, menus, _etc._ (_i.e._ not just markup!). 

Furthermore, assuming that one day we publish the package listing on https://ocaml.org (which I truly hope we will!), I imagine we'd want to keep the current navigation bar and other page elements, which is something completely incompatible with the current approach.

Thus, I suggest we take another route. I believe it would be more valuable to have the ability to embed odig's package listing into an HTML template. Something along the lines of:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="my_css.css">
    <title>My OCaml Package Registry</title>
    $ODIG_HEAD <!-- odig specific elements -->
  </head>
  <body>
    <div id="header">...</div>
    <div id="sidebar">...</div>
    $ODIG_BODY <!-- odig-generated content -->
    <div id="footer">...</div>
  </body>
</html>
```

In this approach odig defines a default template (equivalent to [dbuenzli/odig/src/odig_api_doc.ml#L398](https://github.com/dbuenzli/odig/blob/66819154ae43a8fcca8a3857ca9851a058661ee4/src/odig_api_doc.ml#L398)) and interpolates the variables with generated content when `odig odoc --template=PATH` is called.

Note that this idea is widely used in other documentation generators. For example pandoc supports custom templates for different output formats (see http://pandoc.org/MANUAL.html#templates).

@avsm you [showed interest](https://github.com/dbuenzli/odig/issues/19#issuecomment-288053227) in this feature a while ago, would the described approach work for you?

@dbuenzli Sorry for changing the direction of this issue but I believe my concerns justify it.

(I'll write my thoughts on the second use case later.)

**_P.S._** I think the proposed also applies to odoc. Currently the whole document is generated by odoc itself. That includes the actual documentation produced from ocamldoc syntax, signature items _and_ complementary page elements (we already have a fixed sidebar and will add a search bar in the future). That leaves no space for flexibility at all! Will we add `--no-FEATURE` flags to `odoc html` to keep the output embeddable? I suggest we add a default HTML template that renders the current output and allow people to customise it and enable complementary HTML elements with variables like `$ODOC_SIDEBAR`, `$ODOC_SEARCHBAR`, _etc_.

@aantron @ryyppy what do you think?

**Comment by dbuenzli** [comment]
> Sorry, but I don't find this satisfactory...

Let's keep simple things simple. There are two things that I conflated in this this issue:

1. The ability to render the markup associated to an arbitrary ocamldoc fragments (in other word what `odoc` manual pages provide but *without the surrounding chrome and document definition*). See for example the output of `omd` on markdown fragments.
2. The ability to include `odoc`'s output in another document. 

I thought it was possible to solve both issue toghether but now think it's not a good idea. I think we need a separate subcommand for 1. What I'd really like for now is 1., I don't really care about 2. 

> In addition to odoc.css we already have one JavaScript file and will have others in the future.

I personally think this is an issue. What this JavaScript file does should be done by `odoc` itself.

> Regarding the use case 1
> Have you considered supporting HTML directly?

Yes, the answer is no. Because you want to be able to link into the docset using ocamldoc's xref capabilities.

Regarding use case `2.` this issue is not needed. This should nowadays solved by the `index.mld` file installed by packages  which I'll simply `sprintf` in a larger `mld` document that adds the `odig` chrome before treating the result as a the proper `index.mld` file for the package.

Regarding templates that path was already taken once to the extreme in another iteration, could we please first finally have a decent markup finalized before we talk about this again ?

**Comment by rizo** [comment]
First of all, I agree that 1 is useful and we should implement it. Implementing it might be problematic because currently the HTML generation process currently assumes a full document output. This feature should ideally only work on mld files (as you mentioned somewhere above) and should not produce anything else (sidebars, etc). I'll investigate this!

> I personally think this is an issue. What this JavaScript file does should be done by odoc itself.

I don't see this as an issue. Javascript will be required for some of the odoc's features. But the good news is that it's not strictly needed for 1. The file we're currently including is [highlight.js](https://highlightjs.org/) which is only needed for syntax highlighting. When working with fragments that responsibility is delegated to the parent doc. I do encourage you to include it in odig's package listing page, but it's not critical if you don't.

(We can also consider adding syntax highlighting markdown for code blocks in odoc itself. The problem is that currently we make no assumptions about the content of `{[ ... ]}`.)

**Comment by rizo** [comment]
> Yes, the answer is no. Because you want to be able to link into the docset using ocamldoc's xref capabilities.

I honestly don't see this as a major limitation. Please correct me if I'm wrong, but the main user-oriented goal, in my understanding, is adding a custom chrome to the package listing page. Consider the https://ocaml.org or https://docs.mirage.io/ examples again, why would someone want to include documentation xref links in the chrome? Injecting an ocamldoc-based HTML into the listing page doesn't fully solve https://github.com/dbuenzli/odig/issues/19 IMO.

In practice I think we need both! The ability to inject a custom ocamldoc string in the toplevel header _and_ the ability to customise the chrome (by using a custom template as I suggested). I believe the second is more important.

**Comment by rizo** [comment]
> Regarding use case 2. this issue is not needed. This should nowadays solved by the index.mld file installed by packages which I'll simply sprintf in a larger mld document that adds the odig chrome before treating the result as a the proper index.mld file for the package.

So you would add the content of the `index.mld` file [here](https://github.com/dbuenzli/odig/blob/66819154ae43a8fcca8a3857ca9851a058661ee4/src/odig_api_doc.ml#L304), right?
I'm glad the fragment option is not needed. I still have some thoughts about that, but to avoid confusion and distractions, we can discuss it later/elsewhere.

**Comment by rizo** [comment]
> Regarding templates that path was already taken once to the extreme in another iteration, could we please first finally have a decent markup finalized before we talk about this again ?

I remember you mentioned this previously somewhere but I can't find the specific comment (there're too many issues discussing markup generation...). What would you say is missing before it's considered "decent"?

**Comment by rizo** [comment]
(@dbuenzli Sorry if it seems like I'm opposing your proposals – I'm not. It's just hard to understand how some specific features fit into the big picture.)

**Comment by dbuenzli** [comment]
> The file we're currently including is highlight.js which is only needed for syntax highlighting.

Precisely `odoc` can do that itself if it takes care to properly `span` the elements it's generating.

> (We can also consider adding syntax highlighting markdown for code blocks in odoc itself. The problem is that currently we make no assumptions about the content of {[ ... ]}.)

The convention from ocamldoc generation was that these were highlighted as ocaml code; you have verbatim fences for non-ocaml code.

> Injecting an ocamldoc-based HTML into the listing page doesn't fully solve dbuenzli/odig#19 IMO.

From my perspective it perfectly does. I do not want package to be able to tweak their landing's page chrome. That's a recipe for UI inconsistency.  I'm fine with package owners tweaking the presentation of their toplevel module list and pointers to their doc pages but I'm not with them tweaking the rest of the chrome.

> In practice I think we need both! The ability to inject a custom ocamldoc string in the toplevel header and the ability to customise the chrome (by using a custom template as I suggested). I believe the second is more important.

No, the first one is important so that package publishers can guide the user through the entry points of their packages to make more usable. Again I do not want each package to be able to customize the chrome by themselves, only the presentation of their content. 

Now you may want to customize the chrome globally but in practice the number of users that are going to do this is most certainly going to be very low. I think it would be better if we focus on the experience of the working programmer and hence the stock odoc/odig generation which is what for example `odig` or `dune` users will see rather than the ability to be able to inject odoc or odig results into other websites which can be solved later. 

> I remember you mentioned this previously somewhere but I can't find the specific comment (there're too many issues discussing markup generation...). What would you say is missing before it's considered "decent"?

The parenthesis you wrote should answer your question, these are the issues to work on; and I'm not even talking about the regression that were introduced by the new n+1 markup rewrite which I hadn't time to fully investigate so far because the current master also, it seems, completely broke odig generation for a reason unknown to me yet.

**Comment by dbuenzli** [comment]
> I honestly don't see this as a major limitation. Please correct me if I'm wrong, but the main user-oriented goal, in my understanding, is adding a custom chrome to the package listing page. Consider the https://ocaml.org or https://docs.mirage.io/ examples again, why would someone want to include documentation xref links in the chrome?

Forgot to answer that. This is not for customizing the chrome it's for customizing the introduction to the package list and hence you may want to link into packages for guidance on the package set.

**Comment by rizo** [comment]
> Precisely odoc can do that itself if it takes care to properly span the elements it's generating.

> The convention from ocamldoc generation was that these were highlighted as ocaml code; you have verbatim fences for non-ocaml code.

That is true, and as I said, we should consider doing it in odoc directly. I'm not sure if assuming that code blocks contain OCaml by default is a good idea (and you seemed to agree in a different issue https://github.com/ocaml/odoc/issues/130#issuecomment-409295820).

> From my perspective it perfectly does. I do not want package to be able to tweak their landing's page chrome. That's a recipe for UI inconsistency.

That's precisely where the misunderstanding came from: I was not thinking about the case of _individual_ publishers customising the chrome. I don't think it's important at all. For those – you're right – an introduction to the package list is more than enough.

My main motivation comes from [this comment](https://github.com/dbuenzli/odig/issues/19#issuecomment-288053227) and the potential customisation of the _chrome_ in https://ocaml.org or https://docs.mirage.io/ documentation registries. Yes, those are very specific cases but with huge impact. We should really have an official OCaml package documentation website with _all_ opam packages (and an official template/theme). I'm tired of pointing people to https://docs.mirage.io as an incomplete and unofficial alternative for that...

Anyway, I think I'm getting closer to implementing the option 1 you presented. I'll try to submit a PR for review soon.

**Comment by dbuenzli** [comment]
> That is true, and as I said, we should consider doing it in odoc directly. I'm not sure if assuming that code blocks contain OCaml by default is a good idea

That's how it has always been in ocamldoc and I think that's what should be done. 

>  (and you seemed to agree in a different issue #130 (comment)).

No you are making an inference that I'm not making there, I'm talking about code fences *and* verbatim. It's good to have code fences assumed to be OCaml *syntax* both because that's the language we are dealing with and it's therefore nice to be able to highlight it and because that's the reasonable convention established by ocamldoc for more than 15 years now.

However regarding extraction it's simply better not to assuming anything both about OCaml fences/and or verbatim and let the extractor interpret what it wants of the resulting pure textual extraction. In the particular case of OCaml code fences this could be signatures, module implementation and/or toplevel session fragments. 

> We should really have an official OCaml package documentation website with all opam packages (and an official template/theme). I'm tired of pointing people to https://docs.mirage.io as an incomplete and unofficial alternative for that...

Sure but just bear in mind that the main obstacles to this is *absolutely not* being able to customize the chrome...

**Comment by rizo** [comment]
> No you are making an inference that I'm not making there

I guess I misunderstood your point in that comment, sorry.

> It's good to have code fences assumed to be OCaml syntax both because that's the language we are dealing with and it's therefore nice to be able to highlight it and because that's the reasonable convention established by ocamldoc for more than 15 years now.

The only issue is that we also support the Reason syntax now. OCaml can still be the default for code fences but we should have a way to indicate an alternative syntax.

> However regarding extraction it's simply better not to assume anything both about OCaml fences/and or verbatim

Understood.

> Sure but just bear in mind that the main obstacles to this is absolutely not being able to customize the chrome...

What is it then? Having the tooling ready for this would certainly help start the conversation, no?

**Comment by rizo** [comment]
I've proposed a PR for the discussed design: https://github.com/ocaml/odoc/pull/166

Let me know what you think, @dbuenzli

**Comment by lpw25** [comment]
> Having the tooling ready for this would certainly help start the conversation, no?

To be fair the conversation has been going for 5 years.

> What is it then?

The underlying issue is that it is really hard to do it properly, and people are reluctant to make something official unless it is done properly.

By properly, I mean a documentation page for every version of every package and with cross-linking guaranteed not to fail spuriously. Doing this requires coming up with a notion of "version" of a package that includes all the information that affects its documentation -- which at the very least needs to include the versions of all its transitive dependencies -- and then trying to build enough of these "versions" so that every actual version of every package has a corresponding "version" that can be used as its documentation.

This also all needs to be automated so that things are updated automatically as new packages appear. 
Ideally it would also try not to build a huge number of packages over and over again, since that can quickly eat up a large amount of time/resources. That stuff probably requires someone who understands how to interface with the opam solvers.

**Comment by dbuenzli** [comment]
> The underlying issue is that it is really hard to do it properly, and people are reluctant to make something official unless it is done properly.

FWIW I still think this is a wrong way of approaching to the problem and the best way of nothing ever happening. One should start with a best-effort approach with the existing tooling. This would already significantly improve the life of programmers and the result can then gradually be refined as tooling evolves. That's exactly how `odig` proceeded by first using `ocamldoc` (and thus failing spectacularly on some packages but succeeding greatly on others) until `odoc` was sufficiently usable to make the switch to it.

> What is it then? Having the tooling ready for this would certainly help start the conversation, no?

Precisely and having the tooling ready means rather solving the *other* issues of odoc. Like stabilizing markup, stabilizing the linking scheme, making usable indexes, etc., etc.

**Comment by rizo** [comment]
> To be fair the conversation has been going for 5 years.

@lpw25 Oh, I'm aware that you, @dbuenzli and others have been working on documentation tooling for a long time and I truly appreciate all the work that has bee done so far.

What I'm not aware of is discussions about integrating the current efforts into the official OCaml website. I understand that this is the desirable ultimate goal, but I it's not clear what's the current status and what's missing.

My _subjective_ perception of the situation is that we have multiple excellent but fragmented tools and resources (odoc, odig, the online opam [package repository](https://opam.ocaml.org/packages/), dune (the odoc integration in particular)) that individually try to solve some problems, but there's no unified roadmap to get us to the final stage. As the result there seem to be inconsistencies, duplicated work, uncertainty and a high barrier for contributors that wont to improve the situation.

I don't want this to sound like purposeless criticism, I'm only trying to clarify the situation, stimulate coordination and help.

> The underlying issue is that it is really hard to do it properly, and people are reluctant to make something official unless it is done properly.

That's understandable. But I believe it's also possible to produce incremental solutions that simplify programmer's life. In the end the work is never done – it's a process.

> Precisely and having the tooling ready means rather solving the other issues of odoc. Like stabilizing markup, stabilizing the linking scheme, making usable indexes, etc., etc.

Let's do it! :)

It's hard for me to prioritise work (see my comments above), I have my own notion of "important" but to make visible progress we need coordination.

**Comment by pmetzger** [comment]
> That's understandable. But I believe it's also possible to produce incremental solutions that simplify programmers' life. In the end the work is never done – it's a process.

This.

**Comment by bluddy** [comment]
> It's hard for me to prioritise work (see the above), I have my own notion of "important" but to make visible progress we need coordination.

I think the lack of coordination is one of the missing ingredients in the OCaml ecosystem nowadays (aside from general lack of people). There are some discussions of coordination happening on the private ocamllabs Slack, some happening on discord, but those aren't persistent and can't be referred to later, and most plans still seem to be happening one-on-one in the real world, which doesn't help people who aren't present in those discussions.

We need a platform for both design and discussion. Github's tooling is improving -- they've basically stolen Trello's design for their projects page, and it may be worthwhile to use that feature to plan several steps ahead, especially at the umbrella level of multiple projects.

**Comment by rizo** [comment]
This went completely off-topic, sorry I have started that.

But the good news is that this feature is now implemented in https://github.com/ocaml/odoc/pull/166. @dbuenzli hope this will allow you to make progress on the odig's side.
