### ISSUE TITLE
Duplicate class attribute in html output

### ISSUE THREAD

**Issue by emillon** [ocaml/odoc#897]
Hi,
In some cases it looks like odoc is emitting invalid HTML, with duplicate attributes like:

```html
<div class="spec module" id="module-L" class="anchored">
```

This can be found by `git grep 'class=[^>]*class=' -- test/`:

https://github.com/ocaml/odoc/blob/a52dd8e960f99b38162d40311a9c4512d5741d43/test/generators/html/Ocamlary-module-type-With8-M-module-type-S.html#L21

I'm not familiar enough with odoc to help solve this, but from a quick look the part that generates `"anchored"` seems to do the right thing and merge the classes together.

**Comment by Julow** [comment]
This file is no longer part of the testsuite and is still here because the testsuite doesn't detect unecessary files. (https://github.com/ocaml/odoc/pull/902)
The duplicate attribute bug seems to be fixed since 03569db.
