### ISSUE TITLE
Disambiguating references

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#90]
Follow up to [#61](https://github.com/ocaml-doc/odoc/issues/61#issuecomment-319974223) : 

> This is a somewhat independent issue but: ocamldoc's syntax for references is vaguely broken as it doesn't (as far as we can see) allow to disambiguate the reference on the last line in the following:
> ```ocaml
> module M : sig
>   module type S : sig
>     type t
>   end
> 
>   module S : sig
>     type t
>   end
> end
> 
> (** Some reference to {!M.S.t} *)
> ```
> 
> Indeed the syntax ocamldoc provides only allows to disambiguate the last part of the reference, but not intermediate ones. So here one cannot say: "*I want `S` to be a module type*".
> 
> We're proposing to extend the syntax for references to be able to disambiguate intermediate parts of the path.
> In the previous example the fully disambiguated reference could look like this: `{!module-M.module-type-S.type-t}`.
> 
> N.B. An alternative syntax could be `{!M[module].S[module-type].t[type]}` but we have a preference for the first one (as it's closer to the urls generated by doc-ock-html). Or something better. Any ideas?

Actually, playing with pages and this new reference syntax, I realized that will using dashes to separate between the "kind" and the "identifier bit" is fine for any OCaml path, it might not be when referring to section labels, which might contain dashes.

There are a few options available:
1. use the other syntax mentioned previously (which I retrospectively find verbose and ugly)
2. use another separator (would `#` be OK? would we run into the same issues?)
3. keep using dashes for references and forbid it in section labels (erroring when we encounter one)

@aantron @dbuenzli @lpw25 : any preference?

**Comment by dbuenzli** [comment]
> it might not be when referring to section labels, which might contain dashes.

I don't think this is the case, IIRC section labels with dashes make `ocamldoc` choke, you have to use underscore (I always suspected it was in fact expecting a valid ocaml identifier for these labels) so it's unlikely you'll find many of these in the wild.

> I realized that will using dashes to separate between the "kind" and the "identifier bit" is fine for any OCaml path,

This looks consistent with the fragment identifiers generated in the markup so maybe we should go for this.

**Comment by trefis** [comment]
So, option 3 then?

**Comment by dbuenzli** [comment]
That's what I would say.

**Comment by aantron** [comment]
It seems that dashes can appear in operators: `{!(@->)}`. I [found this in Ctypes](https://github.com/ocamllabs/ocaml-ctypes/blob/67e711ec891e087fbe1e0b4665aa525af4eaa409/src/ctypes/ctypes_types.mli#L360-L363), and the new reference parser rejected it as with an invalid reference kind.

I guess the most direct way to address it is to make the parser aware of parentheses.

**Comment by trefis** [comment]
Yeah... IIRC the current "reference parser" is just a bunch of `String.rindex` and `String.sub` called recursively. Writing a proper lexer would be nice.

**Comment by aantron** [comment]
> it might not be when referring to section labels, which might contain dashes.

Right now, odoc auto-generates section labels, when not specified by the user, based on heading content, and replaces whitespace with dashes (this was an initial implementation). Leaving a note here (probably to myself) to either fix that, or to change the reference disambiguation syntax, or both.
