### ISSUE TITLE
build fails in ocaml 5.1+trunk

### ISSUE THREAD

**Issue by bikallem** [ocaml/odoc#900]
`opam install odoc` in ocaml-5.1+trunk fails with the following error,

```
# File "src/loader/cmi.ml", line 678, characters 19-41:
# Error: This expression has type bool * bool * bool
#        but an expression was expected of type 'a * 'b * 'c * 'd
```

**Comment by Julow** [comment]
A fix is in this PR: https://github.com/ocaml/odoc/pull/901 you can pin `git+https://github.com/Julow/odoc#compat_510` to try it now.
