### ISSUE TITLE
Modification to theme

### ISSUE THREAD

**Issue by AshineFoster** [ocaml/odoc#906]
![odoc-edited-theme](https://user-images.githubusercontent.com/40001976/202932616-d7358815-dcf2-490b-bf68-dc1fd3befbd0.png)

In the above image I made some changes to my odoc css theme file. 

1. Change the colors of the different types to make it easier to find types and modules when scrolling the docs
2. Add a background color and padding to the documentation to make it easier to read

I am not familiar with css but I made the previous changes and thought they might be useful to other users of odoc.
My edited theme file is below.
[odoc-edited.zip](https://github.com/ocaml/odoc/files/10051044/odoc-edited.zip)

**Comment by dbuenzli** [comment]
If you want to have these changes integrated in the default CSS theme please open a pull request. 

If you are interested in publishing your own theme to use for with odig then you can follow the [instructions here](https://erratique.ch/software/odig/doc/manual.html#odoc_themes). (I hope this eventually gets solved at the right level, i.e. the `odoc` level, see https://github.com/ocaml/odoc/issues/826).
