### ISSUE TITLE
Showing the source file that generated a page of documentation

### ISSUE THREAD

**Issue by jsomers** [ocaml/odoc#91]
It would be nice if the HTML that was generated from an ml file, for instance, contained a reference somewhere to the path of that file. That way, users of web-based documentation who wanted to make changes wouldn't have to grep around in their source tree looking for the right file.

**Comment by dbuenzli** [comment]
Maybe an option could be added for that. But in general this is not going to be very useful, e.g. when you run odoc for documenting all the packages of an opam switch these source files will be gone and/or in a different place.

**Comment by UnixJunkie** [comment]
maybe related, being able to jump to the particular implementation of a function from its doc is useful.
This is done by Haskell's hoogle.
It's a time saver when the doc is not precise enough.

**Comment by Drup** [comment]
I think this is a poor replacement to the more general feature of having odoc make pages for implementations. Let's close.
