### ISSUE TITLE
Anchors on function/type/etc.. entries of a module in the manual

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/odoc#916]
I'm not sure if this is the right repo to report this in, but pages such as https://v2.ocaml.org/api/Hashtbl.html do not offer a way to link to a certain function in the page.

**Comment by dbuenzli** [comment]
Nope. This is managed by `upstream`. It still uses `ocamldoc` you can link on a function by doing `#VALfunction`. E.g. https://v2.ocaml.org/api/Hashtbl.html#VALcreate
