### ISSUE TITLE
Flaky tests (false positives)

### ISSUE THREAD

**Issue by yawaramin** [ocaml/odoc#929]
E.g. https://ci.ocamllabs.io/github/ocaml/odoc/commit/8b5498b9054b8daa9412f090b38d7c596ae1b8ca/variant/ubuntu-22.10-5.0_opam-2.1

The expect tests seem to be failing purely based on formatting differences:

```diff
File "test/xref2/canonical_nested.t/run.t", line 1, characters 0-0:
/usr/bin/git --no-pager diff --no-index --color=always -u _build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t _build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t.corrected
diff --git a/_build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t b/_build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t.corrected
index 3f19c29..74eebe9 100644
--- a/_build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t
+++ b/_build/.sandbox/9b0ff5c1ace6dd295d3ba8a847500132/default/test/xref2/canonical_nested.t/run.t.corrected
@@ -55,7 +55,8 @@ unresolved in the paths though:
                   "`Module": [
                     {
                       "`Module": [
-                        { "`Root": [ "None", "Main__Container" ] }, "Test"
+                        { "`Root": [ "None", "Main__Container" ] },
+                        "Test"
                       ]
                     },
                     "A"
```

Blocking #928

**Comment by panglesd** [comment]
If I remember correctly, I also had this problem, and it is due to Yojson not having the same output with the `2.x` release.
Downgrade it to `1.7` and the test should no longer have false positives.

**Comment by yawaramin** [comment]
Thanks for the input. My thought here is that the test passing or failing depending on the version of Yojson makes it a flaky test. I can work around it by downgrading the Yojson version temporarily (not a great workaround but OK). Or we could update all the snapshot files in the repo so that my version of Yojson passes the CI (and break it for everyone who hasn't or won't upgrade Yojson).

I think the right way to fix it is to make the snapshots not depend on the version of Yojson. That way it should work universally.

**Comment by yawaramin** [comment]
This seems workable, I would be very surprised if `jq` pretty-printer formatting output is unstable.

Part of the problem is also that opam is not reliable at installing all dependencies and their requested versions. I just did the following to double-check:

```
# in the odoc project root directory
$ rm -rf _opam
$ opam switch create .
$ opam install --with-test --deps-only odoc
$ opam list | grep yojson # no output
```

Now obviously we know that `yojson` is a dependency: `"yojson" {< "2.0.0" & with-test}`

Now if I run `opam install yojson` it installs version 2.0.2.

**Comment by jonludlam** [comment]
I believe this to be fixed by https://github.com/ocaml/odoc/pull/964
