### ISSUE TITLE
Slightly confused by the section/label documentation for odoc

### ISSUE THREAD

**Issue by gasche** [ocaml/odoc#937]
I find the current content of [Odoc for authors > Sections and Headings](https://ocaml.github.io/odoc/odoc_for_authors.html#sections) confusing.

### Mysterious heading level 6

https://github.com/ocaml/odoc/blob/3d2e55582cccbb0314850356139bd0d6171ea2c8/doc/odoc_for_authors.mld#L717-L731

Confusing: the grammar mentions heading levels from 0 to 6, but the text only mentions levels from 1 to 5. Right below there is a mention of level 0, but no mention of level 6. Is the grammar wrong and 6 is not supported? If it is right, please mention it in the textual description somewhere.

### Confusion around variables: placeholders or fixed syntax?

https://github.com/ocaml/odoc/blob/3d2e55582cccbb0314850356139bd0d6171ea2c8/doc/odoc_for_authors.mld#L727-L744

In this example, `label` is used sometimes as a placeholder for arbitrary user-chosen content, `foobar` in the example, and sometimes as fixed keyword syntax I believe. This is very confusing! 

### Inconsistent syntax for placeholders

More generally, this documentation page is inconsistent in its handling of placeholders, which are sometimes written as plain variables (`{b text}`), sometimes using an implicit placeholder syntax using angle brackets; `{@<language>[`, `{m <latex>}`. I wish you would be consistent about the syntax of placeholders.

### Is it `label`, or `section`, or both?

The syntax summary *might* suggest that `label` or `section` are synonyms of each other. Or maybe it suggests that `section` can be used in a subset of cases, with `label` being the general construct. I don't know.

https://github.com/ocaml/odoc/blob/3d2e55582cccbb0314850356139bd0d6171ea2c8/doc/odoc_for_authors.mld#L393

But then the documentation I quoted above only mentions `label:foo` and never `section:foo`. This is confusing. If both are supported, could the documentation mention both?

**Comment by panglesd** [comment]
Thanks for the issue!

I'll try to fix those confusing parts soon.

About the mysterious heading level 6: I checked in the code, level 6 is not allowed/does not exists!

About `label` vs `section`: Again, reading the code, it seems that `label` is the deprecated version of `section`. Both are equivalent, but `label` will output a warning hinting to use `section` instead. Not really what the documentation conveys!
