### ISSUE TITLE
Allow pages outside of packages

### ISSUE THREAD

**Issue by lpw25** [ocaml/odoc#94]
We should support something like:

```
odoc compile --at-root foo.mld
```

which does the same as:

```
odoc compile --package bar foo.mld
```

but places the pages at the root of the tree rather than in a package. This should produce an `<root>/page-foo.odoc` file which in turn become `<root>/foo.html`.

This should mostly just be a change to the "root" type in odoc making the package name optional, and  using the appropriate URL for references to those roots.

**Comment by rizo** [comment]
@lpw25 In your example what is `<root>` exactly? It's the path to the docset where all actual packages are located, right? Seems slightly related to https://github.com/ocaml/odoc/issues/27.

I wasn't aware of this issue when I was working on https://github.com/ocaml/odoc/pull/166. HTML fragments are an example of an output without a package, I had to [use a dummy package name](https://github.com/ocaml/odoc/pull/166/files#diff-97dcad485808b851bebe5a10cccac4d7R5) for that as a workaround.

**Comment by dbuenzli** [comment]
This would certainly be useful for generating `odig`'s index page, IIRC for now I have to make assumption for in the linking structure of `odoc`.

**Comment by lpw25** [comment]
> It's the path to the docset where all actual packages are located, right?

That sounds right, yeah.

> This would certainly be useful for generating odig's index page

IIRC that was indeed the kind of use case I had in mind when I opened this issue.
