### ISSUE TITLE
Documentation: second level includes are not visible

### ISSUE THREAD

**Issue by Chris00** [ocaml/odoc#95]
When an included interface includes a second level one, the latter is not visible enough when it is open.
![32697375-45a9a756-c78f-11e7-9d90-eabd517aa7d6](https://user-images.githubusercontent.com/1255665/32702400-e74bbf0c-c7e6-11e7-8862-63d915f4f960.png)
A closed second level also changes the line width, which looks odd.

**Comment by dbuenzli** [comment]
I'm not sure I understand what the problem is here. And where does the line width change ? Could you please rather send a link on an example and also mention your browser.

**Comment by Chris00** [comment]
> And where does the line width change ?

In front of `include Base__.Monad_intf/S_without...`

**Comment by Chris00** [comment]
> what the problem is here.

Did you notice two braces are open?  If not, that's the problem — knowing what is the origin of each value.
