### ISSUE TITLE
`No newline at end of file` in html files

### ISSUE THREAD

**Issue by 3Rafal** [ocaml/odoc#952]
When generating test cases for #950 , I've found out that generated html files don't end with a new line.
This results in git warning: `No newline at end of file` and is shown as red marker on GitHub:  
![Screenshot 2023-04-05 at 10 22 05](https://user-images.githubusercontent.com/22241847/230024986-9724ae90-76dc-42ed-b5ad-efd40780c9d6.png)

The issue doesn't occur for other outputs (tex, man).

**Comment by Julow** [comment]
The problem seems to be located here: https://github.com/ocaml/odoc/blob/master/src/html/html_page.ml#L149
Tyxml's `pp` function doesn't output a newline so we need to output one in the `content` function. The same bug occurs for source pages below.
Would you be interested in fixing this ?

**Comment by 3Rafal** [comment]
Sure, I'll try to fix it. :) Thanks for heads up
