### ISSUE TITLE
Missing documentation for "sub-library"

### ISSUE THREAD

**Issue by Lupus** [ocaml/odoc#959]
I have this tiny project, that is a minimized version of a larger proprietary codebase: https://github.com/Lupus/odoc-issue-sample-repo

It contains two libraries - `x` and `x.c`, `x` depends on `x.c` and re-exports some of its modules.

In the generated documentation `x/X__c/index.html` is empty for some reason, and there are no `x/X__c/Baz/index.html` and `x/X__c/Qux/index.html`.

I managed to get documentation for `Baz` only with `module type of` hack:
![image](https://user-images.githubusercontent.com/105348/233843585-dd1bd003-6482-45b4-aff5-53c2e29af32f.png)

Both links to `X__c.*` result in 404 as corresponding files do not exist, and clicking on `Baz` link renders the documentation for that module.

Is this an expected behavior?

Software versions used:
ocaml 4.14.1
dune 3.7.1
odoc 2.2.0

**Comment by jonludlam** [comment]
odoc treats modules with double underscores in their names as hidden. Try calling it `X_c.ml` instead (single underscore) and see if that fixes it for you? There's some explanation of the rationale behind this [here](https://ocaml.github.io/odoc/dune.html) and at the 8 minute mark in this video: https://watch.ocaml.org/w/6hAk7gJcwxoKkT1Edq7rpF . That said, I think odoc ought to be handling this sort of thing more gracefully, and we definitely shouldn't be making links to things that won't exist, so there's likely some work we need to do here.

**Comment by Lupus** [comment]
Thanks for the hint, it works as expected with single underscore. This was very confusing, it used to work in 1.5 and then all our generated documentation broke apart. After couple days of debugging I gave up, created minimal repro and created this issue. Would be awesome if odoc warned me about having modules with double underscores in my source tree.

**Comment by Julow** [comment]
Modules with double underscores are very common with Dune. Perhaps Odoc could warn about modules with double understand *and* the `--hidden` option hasn't been passed ?

**Comment by Lupus** [comment]
Maybe it can actually error out in this case? odoc already produces a ton of warnings on our codebase, which do not seem to affect the output. and we generally just ignore them as they don't look much actionable. This case does affect the documentation - it will just be missing altogether...

**Comment by lpw25** [comment]
Using double underscores to indicate a hidden module is standard across OCaml tooling, even the compiler will try very hard never to print a name with `__` in it. I don't think odoc can reasonably do anything here other than treat `__` as hidden modules. An error or warning would almost entirely be false positives.

**Comment by Lupus** [comment]
I'm using OCaml for several years as of now and I wasn't aware of this. I knew that dune adds double underscore to the end of module names when wrapping libraries, but that didn't immediately hinted that any double underscores are treated specially by the toolchain.

OCaml tooling should probably communicate that idiom to the user loud and clear - if I define a library in dune and include double underscore in its name, dune should tell me that I'm doing something wrong. Otherwise I'm allowed to do that, and it can stop working at some random time in future when the tooling decides to change handling of those hidden modules.

**Comment by lpw25** [comment]
I don't disagree it's a badly documented convention and that something should perhaps be telling you about it. My point is more that I don't think odoc can be that something.

**Comment by panglesd** [comment]
I think this issue is not really actionable on the `odoc` side.
