### ISSUE TITLE
destructive substitution not being done

### ISSUE THREAD

**Issue by trefis** [ocaml/odoc#96]

**Comment by greedy** [comment]
This was bothering me in some work I'm doing so I thought I'd take a look at fixing this. I tried the simplest thing that could possibly work:

```patch
diff --git a/src/xref/expand.ml b/src/xref/expand.ml
index ba36e36..9062ed4 100644
--- a/src/xref/expand.ml
+++ b/src/xref/expand.ml
@@ -305,8 +305,8 @@ and expand_module_type_expr ({equal; _ } as t) root dest offset expr =
                match subst with
                | TypeEq(frag, eq) -> refine_type ex frag eq
                | ModuleEq(frag, eq) -> refine_module ex frag eq
-               | TypeSubst _ -> ex (* TODO perform substitution *)
-               | ModuleSubst _ -> ex (* TODO perform substitution *))
+               | TypeSubst(frag, eq) -> refine_type ex frag eq
+               | ModuleSubst(frag, eq) -> refine_module ex frag (Module.Alias eq))
             ex substs
     | TypeOf decl ->
         expand_module_decl t root dest offset decl (* TODO perform weakening *)
```

Somewhat surprisingly, this seems to work right for my usecase. It even removes the substituted types and modules from the expansion. I imagine that it isn't actually this easy and there are cases which won't work right. If anyone could show some examples where this doesn't produce the desired results maybe I could make a more correct fix.

**Comment by avsm** [comment]
That diff seems like a step forward even if it only works for structures! Would you like to convert it into a PR to this repo?

**Comment by greedy** [comment]
I found out that the reason it seems to do something useful for includes at the top-level of a module interface is that the problem in #343 causes `refine_type` to fall into the \`Dot case and return None which seems probably incorrect. Note that this also happens with a non-destructive refinement in released odoc.

**Comment by jonludlam** [comment]
Fixed with new model.
