### ISSUE TITLE
Details are not expanded in import of List in Irmin.Export_for_backends.List

### ISSUE THREAD

**Issue by sabine** [ocaml/odoc#963]
The include of `List` in `Irmin.Export_for_backends.List` on `irmin.3.7.0` is closed when the page loads. It should be open.

See https://ocaml.org/p/irmin/3.7.0/doc/Irmin/Export_for_backends/List/index.html#val-cons (raw odoc output: https://docs-data.ocaml.org/live/p/irmin/3.7.0/doc/Irmin/Export_for_backends/List/index.html.json)

I can see that includes are opened as expected in other packages, e.g. https://ocaml.org/p/core_unix/v0.14.0/doc/Filename_unix/index.html (raw odoc output https://docs-data.ocaml.org/live/p/core_unix/v0.14.0/doc/Filename_unix/index.html.json).

Both renderings use the same [odoc options in voodoo](https://github.com/ocaml-doc/voodoo/blob/bae863ef0188d9817940cfdd8b805dfd4614790a/src/voodoo-gen/rendering.ml#L30):

```
Odoc_html.Config.v ~semantic_uris:false ~indent:false ~flat:false
            ~open_details:true ~as_json:true ()
```

UX problem on ocaml.org: When searching for definitions within closed details, we cannot jump to the exact definition.

**Comment by jonludlam** [comment]
It's marked as closed in the source: https://github.com/mirage/irmin/blob/00751984e65f3e34142a198db33d07b3bb5bc382/src/irmin/import.ml#L43

**Comment by sabine** [comment]
Thank you @jonludlam, that does explain the behavior.

This ability to override in the sources the closedness state looks like a feature that conflicts with a good search UX.

**Comment by sabine** [comment]
Yes, that would work. We can add that on ocaml.org, and odoc would do the same.

**Comment by jonludlam** [comment]
There's a bit more detail and investigation in #1048, so I'm going to close this in favour of that one.

**Comment by jonludlam** [comment]
Oops, should have closed as duplicate rather than completed.
