### ISSUE TITLE
Define a CSS class for labels

### ISSUE THREAD

**Issue by Chris00** [ocaml/odoc#97]
It would be nice from a readability point of view if labels in function signatures could receive a special CSS style.  For example:
```ocaml
external hyperg_2F1_renorm : a:float ‑> b:float ‑> c:float ‑> float ‑> float = "ml_gsl_sf_hyperg_2F1_renorm" 
``` 
it would help the reader if `a`, `b` and `c` could be highlighted somewhat.  Of course no actual style would be associated by default for backward compatibility.

**Comment by dbuenzli** [comment]
This should certainly be done in the context of https://github.com/ocaml-doc/odoc/issues/19

**Comment by UnixJunkie** [comment]
related to  https://github.com/ocaml-doc/odoc/issues/100
