### ISSUE TITLE
Unequal table cells for some generated tables.

### ISSUE THREAD

**Issue by lubegasimon** [ocaml/odoc#989]
I think it would be nice if table cell sizes were flexible for tables generated. For example, this code snippet would generate cells of different sizes even when perhaps the author didn't intend so;
```
{t
  foo | foo bar | foo bar baz
  --|---|--
  1 | 2 | 3
}
```
Generated table;
![Screenshot 2023-08-18 at 22 14 42](https://github.com/ocaml/odoc/assets/34124177/7c635d14-a25c-4d5d-9fac-ed6d198473c2)

**Comment by panglesd** [comment]
On the other hand, the author might not intend to have cells of equal size.

For instance:

  Name | Description
  --|--
  Foo | A very long description which includes a lot of words made of letters themselves made of bezier curves.

would look strange with equally sized columns, in my opinion.

As a point of reference, github renders unequally sized table cells, as demonstrated above.

**Comment by dbuenzli** [comment]
I don't think you need a new setting. You can likely set the column width you want by simply inserting an appropriate number of U+00A0 (NO-BREAK SPACE) in your column header.

**Comment by lubegasimon** [comment]
Thank you @panglesd and @dbuenzli. I am closing this then!
