### ISSUE TITLE
Many links in `CONTRIBUTING.md` become invalid.

### ISSUE THREAD

**Issue by arbipher** [ocaml/odoc#995]
I guess the root website url may be misused somewhat.

https://github.com/ocaml/odoc/blob/master/CONTRIBUTING.md

**Comment by jonludlam** [comment]
Hmm, they all seem to work for me. Perhaps it was a transient issue? I'll close this, but feel free to reopen if it's still broken for you (and if so, please point out examples of the broken links!)

**Comment by arbipher** [comment]
Indeed. You're right and now it also works for me. Time can heal many things.
